### ISSUE TITLE
Automatic deployment (with or without ES)

### ISSUE THREAD

**Issue by blavenie** [duniter/cesium#10]
cgeek: dans l'idéal, faudrait que quand tu push, ça mette automatiquement à jour cesium2 et cesium avec les dernières modifs, tout en ayant bien 2 builds différents
comme ça : hey tu veux un outil avec l'annuaire ? go cesium2. Tu préfères sans ? Go cesium1.

**Comment by mcl1234** [comment]
ES : elastic search ?

**Comment by blavenie** [comment]
Oui, ES = ElasticSearch. 

J'ai un cluster ES qui tourne. Je suis en plein travail dessus... 
cf ce projet  : https://github.com/duniter/duniter4j  (c'est du Java + Maven)

Quand le cluster est UP, Cesium pourra avoir de nouvelles fonctionnalités (ajout d'avatar et d'infos sur les user, place de marché, annuaires des professionels, etc.)

Le cluster indexe également les blocks de la blockchain, pour permettre à terme un requêtage plus rapide (pour les graphs, etc.)

**Comment by mcl1234** [comment]
Ca m'intéresse , surtout pour les graphiques réseau de certifications entre les humains.

Dans les informations utilisateur on peut ajouter 
des adresses d'autres réseaux comme IPFS , de ce fait , cela permet à l'utilisateur d'indiquer un dépôt - stockage de fichiers ( codes source )
- une application en JavaScript - HTML5 ( IPFS , Zeronet , autre )

Je pense qu'à terme l'identification par Duniter permet à chacun d'avoir un identifiant pour commenter sur un forum ( application en JavaScript - HTML5 )
