### ISSUE TITLE
Add more languages for translations

### ISSUE THREAD

**Issue by M5oul** [duniter/cesium#100]
Like for Sakia:         
- German (de_DE)  
- Italian (it_IT)  
- Polish (pl_PL)  
- Portuguese (Brazil)  
- Russian (ru_RU)  
- Spanish (es_ES)

**Comment by mcl1234** [comment]
+1

**Comment by blavenie** [comment]
@mcl1234 Could you try to translate ?
Files are here : https://github.com/duniter/cesium/tree/master/www/i18n
and here : https://github.com/duniter/cesium/tree/master/www/plugins/es/i18n

**Comment by M5oul** [comment]
I was asking to add them on [Weblate](https://weblate.duniter.org) that way many contributors could do it.
