### ISSUE TITLE
Add a manifest.json to make Cesium a native app in Android

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#101]
Information taken from this link: http://frank.taillandier.me/2016/06/28/que-sont-les-progressive-web-apps/

To understand what I am talking about, you can visit https://forum.duniter.org with an Android phone and select the option "Add a shortcut to the HomeScreen" (Ajouter à l'écran d'accueil) to have the forum as a "native app".

If you click on the newly created shortcut, you can see the forum opened like a native app, however it is opened in a fullscreen mode without the browser toolbars.

Like a native app.

**Comment by mcl1234** [comment]
application*

**Comment by blavenie** [comment]
Full documentation for manifest.json : https://developers.google.com/web/updates/2014/11/Support-for-installable-web-apps-with-webapp-manifest-in-chrome-38-for-Android
