### ISSUE TITLE
Affichage des prix dans le Market Place

### ISSUE THREAD

**Issue by vincentux** [duniter/cesium#104]
Penser à configurer l'affichage des prix (DU, TestNet, ...) avec aussi l'option pour choisir quelle unité on veut.
Merci
![capture d ecran_2016-08-18_22-44-59](https://cloud.githubusercontent.com/assets/11737560/17790395/874eaa0a-6596-11e6-9ea3-8d5a4c0d3446.png)

**Comment by blavenie** [comment]
Oui, je dois utiliser les péréfrences pour savoir comment afficher, en fonction de comment la saisisseur à publier l'annonce...
