### ISSUE TITLE
L'annuaire ne fonctionne plus

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#106]
En faisant une recherche classique, aucun résultat ne s'affiche, ça tourne en boucle.

En déboguant dans le navigateur, je peux voir cette erreur : 

```
vendor-3519d1c2ce.js:12 OPTIONS http://test-net.duniter.fr:9203/user/profile/_search?pretty net::ERR_CONNECTION_REFUSED
```

J'imagine que cela vient du plugin ES, mais alors, est-ce que ça signifie que Cesium devient dépendant d'un service tiers pour fonctionner ? Ou bien est-ce simplement l'algorithme qui devrait gérer un basculement en mode dégradé en cas d'indisponibilité du serveur ES ?

**Comment by blavenie** [comment]
Il faut sans doute que je gère une basculement en mode dégradé, oui.

**Comment by blavenie** [comment]
Pour désactiver le plugin ES; i lfaut retirer le bloc `plugins {... }` dans le fichier `config.js`
