### ISSUE TITLE
ReferenceError: constants is not defined

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#108]
Lors du clic sur le bouton "Envoyer" pour transférer de la monnaie, je tombe sur cette erreur : 

![image](https://cloud.githubusercontent.com/assets/969136/17850080/d931d000-685b-11e6-924a-4142cd7f32a6.png)

**Comment by blavenie** [comment]
dans  Cesium 0.2.1 ?

**Comment by c-geek** [comment]
Oui, entre 2 transactions que je t'ai envoyé (0.003 DU et 0.004 DU).

J'ai trouvé le bug étrange, mais bon je l'ai mis pour tracer.

**Comment by c-geek** [comment]
A nouveau à l'instant, je me suis connecté uniquement pour envoyer 1 DU à vit : 

![image](https://cloud.githubusercontent.com/assets/969136/17863028/39be67bc-6898-11e6-8f79-3dfc7800bb62.png)

**Comment by blavenie** [comment]
oui, j'avais pas tout corrigé ;( 
C'est bon en 0.2.3

merci
