### ISSUE TITLE
Cesium ne permet pas d'envoyer de la monnaie à Remuniter (ou une clé publique)

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#114]
Quand j'essaie d'envoyer de la monnaie à la clé de http://remuniter.cgeek.fr `TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS`, j'obtiens ceci : 

![image](https://cloud.githubusercontent.com/assets/969136/17931469/ead0596a-6a0b-11e6-96d4-9f2cb029a18e.png)

Et donc je ne peux pas envoyer de la monnaie à une clé via Cesium, mais uniquement à des membres. Ce serait mieux de pouvoir le faire.

**Comment by blavenie** [comment]
duplicate #95
