### ISSUE TITLE
A transaction in compact format cannot measure more than 100 lines

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#118]
This is a V3 rule: https://github.com/duniter/duniter/blob/master/doc/Protocol.md#transactions

I am not sure Cesium respect this rule, but from Duniter 0.30.13 this kind of transaction will be refused.

**Comment by blavenie** [comment]
@c-geek non, cela n'est pas gérer ;)
Du coup le mieux c'est de découper en plusieurs TX de 100 lines max ?

**Comment by c-geek** [comment]
De manière générale, pour éviter ce problème il faut réduire la fragmentation. Car l'utilisation d'une source compte pour 2 lignes , c'est ce qui pêche le plus.

Donc dès que possible, il faut fusionner un maximum de sources entre elles.

**Comment by blavenie** [comment]
Je viens d'avoir le pb, dans un virement de seulement 2 DU ;)

**Comment by blavenie** [comment]
@c-geek le document que je viens d'envoyer à surtout beaucoup de lignes unlock (autant que de sources).
Du coup j'imaginais un truc (tu y as peut-etre déjà pensé ?) : remplacer les lignes :

```
unlocks:
0:SIG(0)
1:SIG(0)
...
50:SIG(0)
```

par :
```
unlocks:
0-50:SIG(0)
```
Dans le cas précédent, on réduirait de 49 lignes...
Qu'en penses tu ?

**Comment by c-geek** [comment]
Peux-tu me montrer l'entièreté de la transaction stp ?

**Comment by c-geek** [comment]
Car il faut bien comprendre que cette limite de 100 lignes n'a pas de rapport avec une problématique de stockage, mais simplement de définir "en gros" le nombre de sources qu'on peut utiliser par transaction, soit environ une bonne quarantaine.

Et par ailleurs oui, ce serait une très bonne solution de compression que d'indiquer `0-50:SIG(0)` pour définir les 50 lignes d'Unlocks. Mais ce serait pour régler une problématique de stockage ou de transfert réseau.

Là par exemple, la solution que je préconiserais pour envoyer 2 DU (sacrée somme quand même, ça représente 20% de ton épargne moyenne à 10 ans), c'est de préparer le montant avec une ou plusieurs transactions qui rassembleraient les sommes en moins de sources.

**Comment by blavenie** [comment]
> Mais ce serait pour régler une problématique de stockage ou de transfert réseau (ce qui n'est pas le cas ici).

ok, j'avais mal compris.

> Là par exemple, la solution que je préconiserais pour envoyer 2 DU (sacrée somme quand même, ça représente 20% de ton épargne moyenne à 10 ans), c'est de préparer le montant avec une ou plusieurs transactions qui rassembleraient les sommes en moins de sources.

Je vais faire ca.

**Comment by blavenie** [comment]
Linked to https://github.com/duniter/duniter/issues/657

**Comment by blavenie** [comment]
Fixed in v0.3.17
