### ISSUE TITLE
Add a confirm dialog when certifying someone

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#12]
The certification process is working, but it should be more controlled: today if we click by inadvertance on the certification button (and this is very probable with the 2 buttons side by side) the certification is immediately sent without any confirmation.

![image](https://cloud.githubusercontent.com/assets/969136/15008272/6462a740-11df-11e6-9e82-3e7569bd18e6.png)

**Comment by galuel** [comment]
il devrait y avoir à terme un message lors de la certification d'un membre du type : "Attention, ne certifiez pas un membre que vous ne connaissez pas physiquement, ne certifiez pas un membre avec qui vous n'etes pas en présence physique, que vous connaissez, et en présence d'autres membres de la monnaie, ceci pourra vous être reproché et pourra être considéré comme un défaut protocolaire de votre part" ou ce genre d'avertissement.

+ aussi des confirmations avec CAPTCHA ou ce genre de choses, de manière à s'assurer que l'opération est bien parfaitement consciente de la part de l'utilisateur.

Ces messages et avertissements ainsi que contrôles CAPTCHA ou autres, pourraient faire partie du "protocole humain", non-inscrits techniquement dans Duniter, mais Duniter pouvant y faire référence pour dire : tout procédé technique de certification n'assurant pas la conformité avec ce protocole humain devrait être rejeté par les membres de la monnaie comme étant incomplet et incorrect.

**Comment by Insoleet** [comment]
Le message coté Sakia est le suivant : https://github.com/duniter/sakia/blob/master/src/sakia/gui/certification.py#L204

+1 pour un CAPTCHA

**Comment by blavenie** [comment]
Done ! (sera visible en 0.1.17)

![spectacle d25680](https://cloud.githubusercontent.com/assets/5269556/16022373/d413a93e-31b7-11e6-896c-878b189453e2.png)

@Insoleet j'ai adapté le message de Sakia à la taille de l'écran. ;o)
