### ISSUE TITLE
HTTPS on cesium.duniter.fr

### ISSUE THREAD

**Issue by M5oul** [duniter/cesium#122]
There is critical informations going through Internet like:
- credentials.
- …

**Comment by blavenie** [comment]
no, credentials ar enever transmitted on internet.
Only BMA REST API is used, or signed document fir the ES dataStore extension.

But, yes, i should do that anyway... ;)

**Comment by blavenie** [comment]
Done here : https://duniter.fr/cesium

but warning : duniter node (in settings) MUST be a https node...
