### ISSUE TITLE
ES: For some reason, I can't edit my announcements after some time

### ISSUE THREAD

**Issue by M5oul** [duniter/cesium#123]

**Comment by blavenie** [comment]
Hum, bizarre...  quelle annonce exactement ? As tu utiliser le meme compte (pubkey) ?

**Comment by M5oul** [comment]
Biensûr, avec la même clée.

Il y avait l’appartement sur Paris.
Bizarrement, maintenant, je peux de nouveau l’éditer.

Maintenant, c’est l’[annonce "Self-hosting for you mom!"](http://cesium.duniter.fr/#/app/market/view/AVazPY9-up9uzWgKipp0/selfhosting-for-you-mom) que je ne peux plus éditer.
