### ISSUE TITLE
ES: Can't create an offer

### ISSUE THREAD

**Issue by M5oul** [duniter/cesium#124]
With Cesium 0.2.9, I get `Could not save esMarket`.

**Comment by blavenie** [comment]
Je viens d'en créer une : http://cesium.duniter.fr/#/app/market/view/AVbWfBe3up9uzWgKiprG/recherche-vendeuse-hf-saveurs-bio-evron-53

Ca marche pour toi !

**Comment by M5oul** [comment]
Je viens de réessayer.
Je ne peux toujours pas en créer.

**Comment by blavenie** [comment]
hum... je vais avoir besoin de plus d'info, genre tes log console, etc. Tu as une erreur dans les log ?

**Comment by M5oul** [comment]
Lors de la création d’offre j’ai dans la console web :
```web
Error from node (-1)cesium-4e48d4adf8.js:2:26800
f/<()cesium-4e48d4adf8.js:2
s()vendor-10e07a1f77.js:12
c/<()vendor-10e07a1f77.js:12
$n/this.$get</h.prototype.$eval()vendor-10e07a1f77.js:13
$n/this.$get</h.prototype.$digest()vendor-10e07a1f77.js:13
$n/this.$get</h.prototype.$apply()vendor-10e07a1f77.js:13
o()vendor-10e07a1f77.js:12
v()vendor-10e07a1f77.js:12
Bt/</$()vendor-10e07a1f77.js:12
p()vendor-10e07a1f77.js:12
i()vendor-10e07a1f77.js:11
ut/u.defer/n<()vendor-10e07a1f77.js:11
```

**Comment by blavenie** [comment]
@M5oul peux tu refaire le test (avec la version actuelle de Cesium) et me redonner l'erreur console ?
Merci

**Comment by M5oul** [comment]
![capture du 2016-09-12 16-29-15](https://cloud.githubusercontent.com/assets/4758871/18439794/f1d92d04-7906-11e6-828f-260712b5d707.png)

**Comment by M5oul** [comment]
Voici l’annonce que j’essaye de poster :
![capture d ecran 2016-09-12 a 16 36 53](https://cloud.githubusercontent.com/assets/4758871/18439840/234e7632-7907-11e6-8438-f032816fb748.png)

**Comment by blavenie** [comment]
Merci @M5oul . Peux tu me donner ta version de browser ?

**Comment by M5oul** [comment]
Firefox 48.0.1, je pense que c’était déjà présent en v47.0.

**Comment by blavenie** [comment]
OK j'ai trouvé : c'est à cause du "0,02" : ES plante car l'index est un décimale( erreur java : For input string: "0,02").

Avec un "0.02" ca passe
