### ISSUE TITLE
[Cesium] Transaction issue...

### ISSUE THREAD

**Issue by modulix** [duniter/cesium#126]
Hi,

I got this message on http://cesium.duniter.fr/#/app/registry/view/AVa71832VNaLy5n_s86y/remuniter
when trying to send money (around 21:14 today)...It is not the first time. Have someone idea from where can come this issue ?
![capture d ecran de 2016-08-27 21-16-53](https://cloud.githubusercontent.com/assets/14559496/18029672/bf7145f0-6c9e-11e6-801d-c3b688cd1477.png)

**Comment by modulix** [comment]
![capture d ecran de 2016-08-27 21-43-42](https://cloud.githubusercontent.com/assets/14559496/18029702/b13d6882-6c9f-11e6-8575-46cdcd818604.png)

**Comment by blavenie** [comment]
Yes, i know this issue. The problem is that you don't have enough money changes : e.g. you have only one bill, to pay a small think. So you need to wait that the BlockChain give your money back, until you could use it for another payment.

@c-geek @Insoleet  Ce problème risque d'arriver souvent (surtout au début), et il empeche de faire deux paiement sucessif en moins de 10 minutes...  On ne va pas pouvoir faire sans la fonctionnalités de change pour fractionner les sources... non ?

**Comment by blavenie** [comment]
OK je viens de voir la réponse de @cgeek [sur le forum](https://forum.duniter.org/t/transaction-issue-with-cesium/1204/3?u=kimamila):

> However Cesium could chain the transactions offline since protocol V0.2, so this error has no reason to exist.

Est-ce que tu parles d'une TX avec la source future (hash récupérée des pendings), et l'utilisation du paramètre `locktime` ? Ou bien y a t'il autre chose à faire ?

**Comment by c-geek** [comment]
Je parle d'une TX avec la source future oui, en récupérant le hash des pendings ou (c'est mieux) en le calculant toi-même. Les inputs des transactions font référence à des transactions précédentes simplement par leur hash, d'où le fait qu'elles peuvent être chaînées offline.

**Comment by blavenie** [comment]
>  en récupérant le hash des pendings ou (c'est mieux) en le calculant toi-même.

Oui c'est bon je le calcul déjà moi meme (je m'en sers pour conserver l'heure de soumission d'une TX - d'ailleurs il faut que je le retire maintenant qu'on a lheure dans les pendings).

Ok donc avec un locktime, les noeuds ne va pas les rejetter (genre invalid source/input) ? Ils vont etre conserver dans la piscine ?
Est-on d'ailleurs obligé de mettre un locktime, du coup ?

**Comment by c-geek** [comment]
Non, pas de locktime, elles seront intégrées l'une après l'autre dans la blockchain. En théorie elles pourraient même l'être simultanément (en les rangeant dans le bon ordre), mais on n'en est pas encore là !

**Comment by blavenie** [comment]
Link to https://github.com/duniter/duniter/issues/657
(need chained TX to be resolved)
