### ISSUE TITLE
[ES] Currencies > Message d'erreur incorrect 

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#13]
"Impossible de chargement la liste des monnaies"

D'ailleurs je me demande bien pourquoi il met ça, un F5 et ça passe. Ca à l'air un peu aléatoire, il affiche aussi ">>>> Error from uCoin node" dans la console.

**Comment by blavenie** [comment]
Cela est lié au registre des monnaies, stocké dans le noeud ElasticSearch, qui est protégé par un Apache capricieux...
Si on configure Cesium sans ES, l'erreur n'apparait plus (la liste des noeuds est alors en dure).
