### ISSUE TITLE
Visualisation of numbers in TN units

### ISSUE THREAD

**Issue by frederiiiic** [duniter/cesium#132]
Hi there,

I've seen on my cesium web client account, that the amout of TN units is viewed strangly.

Actually in the currency page (Same for all the other pages showing TN units) in french, for Monetary mass there is wrote this "736 377,754,512" when i choose TN units.

![untitled-1](https://cloud.githubusercontent.com/assets/10772930/18174111/9b02dc48-706c-11e6-87e5-04ee0f680ae5.jpg).

But i think this should be : 
- in french "736 377 754 512"
- in english "736,377,754,512"

thanks,
Fred.

**Comment by M5oul** [comment]
It's missing a comma.

**Comment by frederiiiic** [comment]
the last comma need to be a point, unless this numbers are not decimals.

**Comment by blavenie** [comment]
In TN unit => no comma need, because all amount are integer.  (only need in UD)

**Comment by frederiiiic** [comment]
Ok so i edit my first post to be clear.
