### ISSUE TITLE
"passer un virement" au lieu de "payer"

### ISSUE THREAD

**Issue by galuel** [duniter/cesium#133]
"passer un virement" ou "virement" serait plus précis que "payer". Car "payer" suppose un règlement "en échange de quelque chose", or un don par exemple n'est pas un "paiement".

En anglais "make a transfer" ou "transfer" tout court.

Je ne pense pas que ce soit nécessaire non plus de faire le bouton en rouge agressif, ça peut très bien être en vert ou bleu ciel, tranquille quoi...

**Comment by M5oul** [comment]
Following of https://github.com/duniter/cesium/issues/24.

**Comment by blavenie** [comment]
Ca une issue comme je les aime : avec une proposition précise ;)
Pas de soucis pour faire ca.
merci
