### ISSUE TITLE
incompatibilité firefox

### ISSUE THREAD

**Issue by PierreYvesC** [duniter/cesium#134]
depuis quelque temps je ne peux plus suivre Testnet depuis cesium avec Firefox comme navigateur (je précise la version est à jours (23 Aout)):
ni mon compte, ni les données générales de la monnaie, ni l'annuaire , en fait seul l'icone "professionnels" fonctionne (j'ai acces à la liste des dernieres annonces.)
le message d'erreur: "chargement de la monnaie impossible" apparait.
si je fait "ok", le rond bleu d'attente tourne infiniment.

par contre ça marche avec Safari.

**Comment by blavenie** [comment]
Tiens, bizarre...
Peux tu s'il te plait : 
 - ouvrir Firefox
 - ouvrir la console : "Ctrl + Maj + K"  (les 3 touches en meme temps)
 - taper l'adresse de cesium
 - Copier/coller le contenu de ta console, dans cette iddue github

Merci ;)

**Comment by PierreYvesC** [comment]
j'ai pas compris ce que je dois faire...
Que veux tu dire par "ouvrir la console"?
Je précise que j'utilise un mac, Ctrl+Maj+K ne donne rien.
:-/

**Comment by M5oul** [comment]
Essaye avec `F12`.

**Comment by PierreYvesC** [comment]
F12 ouvre une fenêtre de réglage de son...

**Comment by M5oul** [comment]
Ok, :dancer: Bah, ça semble être [Ctrl + Maj + k](https://developer.mozilla.org/fr/docs/Outils/Console_Web/Opening_the_Web_Console).

**Comment by PierreYvesC** [comment]
ok, merci moul pour le lien, j'ai compris.
Voila ce qui est écrit dans la console web quand je vais sur cesium et que je clic sur "mon compte".

t?vendor-10e07a1f77.js:27:15609
TypeError: asm.js type error: multiply operands must be both int, both double? or both float?vendor-10e07a1f77.js:38:19135
[app] Locale [fr-FR]cesium-427be824d1.js:9:25267
[http] will cache [http://null/wot/members] 3600000mscesium-427be824d1.js:3:2197
[http] will cache [http://null/blockchain/with/ud] 3600000mscesium-427be824d1.js:3:2197
[http] will cache [http://null/blockchain/block/:block] 3600000mscesium-427be824d1.js:3:2197
[http] will cache [http://null/blockchain/parameters] 3600000mscesium-427be824d1.js:3:2197
[http] will cache [http://null/tx/history/:pubkey/times/:from/:to] 3600000mscesium-427be824d1.js:3:2197
[http] will cache [http://null/tx/history/:pubkey/blocks/:from/:to] 3600000mscesium-427be824d1.js:3:2197
[ES] Enable contribution to Wallet and Wot servicescesium-427be824d1.js:9:12819
Device service disable (no camera)cesium-427be824d1.js:3:5855
Error from node (http://null/blockchain/parameters)cesium-427be824d1.js:2:28451

**Comment by PierreYvesC** [comment]
C'est peut être plus lisible sur cette capture d'écran:

![console](https://cloud.githubusercontent.com/assets/19892806/18319354/99fac1ae-7525-11e6-8783-510a1bc9f69c.jpg)

**Comment by blavenie** [comment]
Peux aller dans "Paramètres" et faire une réinitialisation (dans le menu "trois points verticaux", en haut à droite).
Puis retester.

merci

**Comment by PierreYvesC** [comment]
de nouveau, j'ai pas compris ce que je dois faire... :-/
j'ai pas de rubrique "parametres" dans le menu de firefox, ni 3 pt verticaux...
halala...
:-/

**Comment by blavenie** [comment]
Non, je parle u menu à gauche, dans le site Cesium  (sous "Annuaire", "Professionels", "Annonces", etc.).
Tu peux cliquer ici si tu prefères : http://cesium.duniter.fr/#/app/settings

Puis tu trouvera dans la barre noir en haut, le bouton "trois points verticaux".
;)

**Comment by PierreYvesC** [comment]
ha oui!!
ça marche maintenant normalement!
...sauf mes "transactions" qui n'apparaissent pas, ni même les DU (si je reparamètre "voir les dividendes reçus".)
bon, merci Benoit, merci Moul... Là, j'aimerai être sûr que "mes petits problèmes" avec Césium ont un intérêt pour votre travail de développement, sinon dites le moi svp et laissez tomber, mon intention et de contribuer  :-)   !
biz

**Comment by M5oul** [comment]
C’est super que tu contribues, et que tu remontes les problèmes que tu rencontres :+1:

**Comment by blavenie** [comment]
Tu ne vois oujours pas les transactions dans "Mon compte" ?

Peux tu : 
 - rafraichir la page depuis ton navigateur, puis retester.
 - Si le problème est toujours là, peux tu ouvrir la console (comme tu avais fait plus haut : Ctrl + Maj + k) *puis* rafaichir à nouveau. Et nous donner le contenu de la console ?

Merci

**Comment by blavenie** [comment]
je ferme l'issue. A priori il y avait un probleme de compabilité dans les paramètres enregistrés dans le navigateur (suite au changement de format en v0.2).
On ne devrait plus avoir le soucis après le contournement (réinitialisation des paramètres)
