### ISSUE TITLE
Nombre de transactions envoyées / max

### ISSUE THREAD

**Issue by galuel** [duniter/cesium#135]
Dans "mon compte", on devrait différencier : 
- Monnaie
- Toile de confiance

Qui sont tout de même des notions différentes.

Dans "Toile de confiance", il ne suffit pas d'afficher "nombre de certifications reçues", mais il faudrait afficher : 
- nombre de certifications reçues
- nombre de certifications émises : x sur max possibles
- membre de contrôle : oui / non - nécessite x certifications émises

**Comment by blavenie** [comment]
les "membres de contrôle" sont les sentries, c'est ca ?

**Comment by c-geek** [comment]
Oui, ce sont les sentries.

**Comment by blavenie** [comment]
Voila un premier résultat : http://cesium.duniter.fr/#/app/wot/cert/lg/GtKkDbqAWqUSEsrjFmRAPMT3mr85EgQ4RPc26emVmYz9/Doudou
(en plein écran c'est mieux)

@c-geek  Pour les sentries : faut-il juste avoirle nombre de certification requis pour le devenir, ou bien y a t il autre chose ? (en gros est-ce que je peux le déterminer juste en comptant les certifications recues ?)

**Comment by blavenie** [comment]
`dSen = 1.2 x CEIL(EXP(LN(membersCount)/stepMax))`

https://github.com/duniter/duniter/blob/master/doc/Protocol.md#computed-variables

**Comment by blavenie** [comment]
A ca a changé en v0.40 : `CEIL(membersCount ^ (1 / stepMax))`
