### ISSUE TITLE
virements automatique

### ISSUE THREAD

**Issue by PierreYvesC** [duniter/cesium#136]
Dans la fenêtre de paiement, ça serais pratique de pouvoir entrer une fois pour toute un virement régulier (loyer par exemple).
Il faudrait pouvoir également, l'annuler ou le modifier facilement.
... ceci suggéré avec toute l'humilité possible (je n'ai aucune idée du travail que ça suppose!), dans l'intention de contribuer et très reconnaissant du travail déjà accompli!

**Comment by M5oul** [comment]
Could be done via a crontab?

**Comment by blavenie** [comment]
Salut Pierre-Yves ! 
Et merci, nous sommes preneur de toutes les idées.

cela étant, pour le moment en effet, pour ne pas compromettre la sécurité de la monnaie, cela ne parait pas simple. En effet, Cesium n'utilise pas de "serveur" tiers (ou intermédiaire de paiement) comme nous le faisons avec les banques (les banques sont des prestataire de services, qui se charge par exemple des virements).
Cesium (pour le moment) se connecte directement au réseau de la monnaie, sans intermédaire.
Ce serait donc à Cesium de déclencher le virement...  difficile à faire sauf sur les téléphone, ou il est possible de garder une "tache de fond" qui tourne est fait des opérations.

Cela étant, pour le moment, cela me parait dangereux...

Ce que nous voyons arrivez là, comme besoin, c'est un intermédiaire, prestataire de services, qui pourrait par exemple  :
 - faire des virements,
 - garantir les fonds, typiquement avec une assurance,
 - offrir de nouveaux moyens de paiement

Ce sont, pourquoi pas, des services qui pourraient etre effectués de manière décentralisé, par des noeuds spécialisés, dont l'identité est connue. Du meme style que les noeuds de stockage des infos de la place de amrché, qui commence à voir le jour.
On pourrait imaginer qu'un noeud de ce type offre de faire le virement, en proposant un cout pour la prestatation (en monnaie libre), ou mieux un service comme [remuniter](http://remuniter.cgeek.fr).

**Comment by blavenie** [comment]
Je ferme pour le moment. Ce sera l'objet d'autre développement (hors Cesium), via service tiers.
