### ISSUE TITLE
ma photo et mon nom sur le compte de mon fils!

### ISSUE THREAD

**Issue by PierreYvesC** [duniter/cesium#138]
Quand j'ouvre le compte de mon fils Malo (cYc12Q96...), tout est parfait sauf que c'est ma tronche et mon nom (mon "profil") qui intitule le compte.
J'ai renseigné le "profil" de Malo, nom et photo, ça ne change rien.
Si je déclic "se souvenir de moi" dans les paramètres j’obtiens : Malo comme nom, mais tjrs ma photo :-)
Plus drole, si maintenant je ferme ce compte hybride puis ouvre le compte Estelle (un autre compte de la famille), j'obtiens bien le compte d'Estelle (solde, DU, certifications..) mais avec comme nom "Malo" et comme Photo: moi!    :-D
Si je consulte le "Profil" c'est bien "Estelle".
Tout va bien par contre si je change d'onglet en même temps que de compte.

**Comment by blavenie** [comment]
Oui, j'ai corrigé ce bug de rafraichissement dans une autre anomalie.
La correction sera visible tout à l'heure ;)
