### ISSUE TITLE
Liste des dernières transactions vides

### ISSUE THREAD

**Issue by G4dter** [duniter/cesium#14]
La liste des dernières transactions est vide alors qu'il y a de l'argent sur le compte.
La demande d'adhésion est également en cours ce qui ne semble pas logique.

![1](https://cloud.githubusercontent.com/assets/19184728/15009868/4fb091c2-11e9-11e6-8a67-fe750e50bdb2.png)

**Comment by blavenie** [comment]
@ G4dter Merci pour ta remarque.
As tu constaté le bug ensuite ?
Peux tu le reproduire ?

**Comment by G4dter** [comment]
Et non, malheureusement, je n'ai jamais re-eu le bug ni pu le reproduire …
