### ISSUE TITLE
Impossible de s'identifier quand il y a remplissage automatique des champs "login" et "mot de passe"

### ISSUE THREAD

**Issue by G4dter** [duniter/cesium#15]
Les messages d'erreurs s'affichent et quand on clique sur le bouton "Se connecter", il ne se passe rien.

![2](https://cloud.githubusercontent.com/assets/19184728/15010202/2c35e2e0-11eb-11e6-8da3-e900194e9b66.png)

**Comment by Thatoo** [comment]
Je n'ai pas ce problème moi...

**Comment by G4dter** [comment]
J'utilise Secure Login. Peut-etre que cela joue.

**Comment by blavenie** [comment]
Oui, a priori, on ne pourra pas faire grand chose...

**Comment by G4dter** [comment]
En plus, ca fonctionne maintenant donc doublement clos :).
