### ISSUE TITLE
échec chargement données portefeuille sur cesium.glibre.org/ 

### ISSUE THREAD

**Issue by JeanFe** [duniter/cesium#153]
Attention il s'agit bien de **cesium.glibre.org**
À chaque connexion j'ai le message "échec chargement données portefeuille".
Tentatives:
- Changement adresse de nœud. 
- Désactivé "se souvenir de moi" sur: cesium.duniter.fr et duniter.glibre.org
- Désactivé stokage local
- Bien vérifié la pubkey à chaque tentative.
-version firefox mise à jour de 48.0 à 49.0

nota:
cesium.duniter.fr fonctionne parfaitement.
OS: Ubuntu 16.04

**Comment by galuel** [comment]
J'ai eu ce message aussi lors des premières tentatives, puis cela a fonctionné après que j'aie activé ou désactivé "stockage local", mais je n'ai pas plus d'informations.

**Comment by blavenie** [comment]
@JeanFe  peux tu retester et sortir la console depuis cette page : http://cesium.duniter.fr/debug.html ?
Merci

**Comment by blavenie** [comment]
D'après JeanFe, ca marche sans erreur sur duniter.fr. Je ferme l'issue
