### ISSUE TITLE
Rester authentifier avec des cookies de sessions

### ISSUE THREAD

**Issue by Thatoo** [duniter/cesium#16]
Quand je recharge la page, et donc si j’éteins mon ordinateur, mais surtout si je ré-ouvre l'app depuis mon ordipoche, je ne suis plus authentifié. Je dois réécrire mon login et mot de passe.
C'est surtout ennuyant sur ordiphoche. Sur ordinateur, firefox garde en mémoire le login et mot de passe, il n'y a qu'à cliquer sur login.

**Comment by blavenie** [comment]
Oui, tout en uniquement en mémoire.
Une F5/rafraichir fait une deconnexion...

Tu verras cela en option ou en standard ? 
A quel moment ptoposé à l'utilisateur, selon toi ?

**Comment by Thatoo** [comment]
Traditionnellement, c'est en option, sous la forme d'une case à cocher juste en dessous du login/mot de passe à entrer lorsqu'on se connecte.

**Comment by c-geek** [comment]
Cela pourrait stocker le trousseau privée/publique dans le localStorage (et non pas le salt/password), et reviendrait à faire confiance au navigateur pour son stockage et sa non divulgation.

Cela ne me choquerait pas.

**Comment by blavenie** [comment]
Done ! 
Is option "use local storage" is enable : store keypair and setting in browser local storage.

**Comment by Thatoo** [comment]
Ça ne marche pas chez moi. Le problème est le même sous Firefox desktop et sous Firefox OS.
Quand je vais dans paramètres, il y  a bien "Activer le stockage local" que je peux activer, mais si je me rends sur mon compte ou une autre page de Cesium et que je reviens ensuite sur Paramètres, l'option n'est plus activé. Et si je fais un F5, je dois réécrire mes identifiants/mot de passe.
