### ISSUE TITLE
orthographe dans onglet "monnaie"

### ISSUE THREAD

**Issue by JeanFe** [duniter/cesium#168]
![selection_017](https://cloud.githubusercontent.com/assets/19825127/19131871/7bd997a8-8b51-11e6-96b6-03959a7d829f.jpg)

**Comment by blavenie** [comment]
@JeanFe c'ets pas le nombre qui est reqquis ?
(bon je suis nul en orthographe, faut dire...)

**Comment by JeanFe** [comment]
"requises" s'accorde avec "certifications", par contre et je ne l'avais pas remarqué à la ligne en dessous "maximal" s'accorde avec "mombre" donc ne prend pas de "e".
