### ISSUE TITLE
Unhosted link?

### ISSUE THREAD

**Issue by Thatoo** [duniter/cesium#17]
Je découvre dans github que Césium est une app unhosted... cool!
Je ne trouve pas où entrer mon Remote Storage id comme on peut trouver dans d'autre unhosted webapp. Normalement, il y a une emplacement comme celui sur cette photo : http://www.servicedenuages.fr/images/remotestorage-widget.png

Cesium n'est pas non plus dans la liste des app sur le site https://unhosted.org/apps/.

**Comment by blavenie** [comment]
Merci @Thatoo pour cette remarque.

Oui, il faut qu'on ajoute une emplacement pour définir le noeud.

Concernant le site unhosted.org : ne faut il pas attendre que ce soit stable ?
Peux tu te charger d'ajouter l'App dans leur référencement ?

**Comment by Thatoo** [comment]
@blavenie : J'ai essayé de le faire mais il reste un petit problème à résoudre. On me demande la question suivante : 
"Can you link to a URL on which this app is hosted? You can for instance deploy it using 5apps.com or host it on gh-pages, and then link to that URL instead of to the URL of the source code repo."
Moi j'ai pointé vers https://github.com/duniter/cesium , il faudrait que je donne quoi comme URL du coup?

http://cesium.duniter.fr/  ?

Et sinon, avez-vous ajouter l'emplacement pour définir le noeud (comme dis ci-dessus)?

**Comment by blavenie** [comment]
Oui, tu peux mettre : http://cesium.duniter.fr/
C'est une adresse stable.

Pour le moment, pas d'emplacement pour saisir le noeud. Mais pourquoi pas le faire lors des RML7 ? ;o)

**Comment by Thatoo** [comment]
Autre question qui m'est posé : 
"
Just to be clear, this app does not use remoteStorage or 5apps, right?
"
Ça veut dire quoi?

**Comment by blavenie** [comment]
It does not use remote storage, nor 5apps, but send signed document to a node network (using protocole of Duniter : http://github.com/duniter/duniter).

**Comment by Thatoo** [comment]
thank you.

**Comment by Thatoo** [comment]
Voila c'est fait.
https://unhosted.org/apps/
