### ISSUE TITLE
Is a new member really a member ?

### ISSUE THREAD

**Issue by galuel** [duniter/cesium#176]
Cesium doesn't give the information about the fact one new member who received certifications is really a member or not (for instance due to distance > stepmax) study [this forum line to obtain one case in test-net](https://forum.duniter.org/t/demande-dadhesion-envoyee-en-attente-dacceptation/1309).

**Comment by blavenie** [comment]
Done in Cesium v0.3.17
Now you can see a "not member" text, under the user UID
