### ISSUE TITLE
problème à l'inscription

### ISSUE THREAD

**Issue by interlodeve** [duniter/cesium#180]
le 12/10/16
message d’erreur à la validation : “échec du chargement des données du portefeuille” . impossible d’accéder à " mon compte, mon profil et message".
coté syncro : e.walletData is nul

https://framasphere.org/posts/9f9b97a071070134b9262a0000053625#81cf1f50728c0134b9dc2a0000053625

**Comment by interlodeve** [comment]
la suite...
je me connecte, entre temps quelqu'un m'a certifié. là je n'arrive pas à mettre mon profil à jour...

**Comment by blavenie** [comment]
Bonjour à toi @interlodeve : oui, mes serveurs ont eu un peu de mal la semaine dernière.
C'est rentré dans l'ordre !

par ailleurs, une nouvelle version de Csium corrige pas mal de truc
