### ISSUE TITLE
Une alternative à la Connexion Salt sur Cesium ?

### ISSUE THREAD

**Issue by pifpafpof-thomasL** [duniter/cesium#181]
Bonjour,

Lors des réunions préparatoires aux RML8 sur Toulouse, nous avons rediscuter de la connexion sur Cesium.
Ce mode d'authentification via un double password (phrase secrete/salt + password) semble surprendre un peu tout le monde. 
Pour ma part, j'ai peur que cela entraine pas mal de confusions auprès des utilisateurs.
J'ai moi même eu bien du mal avec la phrase impossible a retrouver.

Et au final il est recommandé d'utilisé son email en guise de salt ce que j'ai fait.

Il ne faut pas oublier que les navigateurs sauvegardent les mots de passe, du coup ça met en péril l'authentification Cesium qu'il s'agissent d'un salt ou UID ou email.

Les quelques banques en ligne que je connais, demandent un code PIN numérique (6 ou 8 chiffres la galère!)  qu'il faut forcement taper car le navigateur ne peut pas mémoriser les positions des chiffres qui changent d'une session à l'autre.
Mais on peut conseiller aux utilisateurs d'utiliser leur code PIN de leur CB actuelle (+code immeuble ou ou carte SIM pour arriver à 8 chiffres) pour qu'ils retrouvent facilement leur code PIN numérique Cesium.

Bref en résumé: 
email (pour identifier de façon unique et simple, et éviter à Cesium de générer un code client) + code PIN 8 chiffres (ou autre solution non mémorisable par le navigateur, mais relativement facile pour l'utilisateur).

Qu'en pensez-vous ?

**Comment by galuel** [comment]
Ces deux champs génèrent la clé privée, qu'il ne faut en aucune façon communiquer. Ce qui revient à générer un password - clé, en deux parties. il ne faut certainement pas dire que le premier password doit être le mail qui serait alors connu, ne resterait plus que le second à trouver pour connaître la clé privée.

Qui plus le mail a une durée de vie limitée aléatoire, tandis qu'un compte de monnaie libre doit pouvoir durer au moins la durée minimum de vie par certifications valides, qui est d'environ 3 ans, avant d'envisager de changer de clé.

**Comment by pifpafpof** [comment]
> Ces deux champs génèrent la clé privée, qu'il ne faut en aucune façon communiquer. Ce qui revient à générer un password - clé, en deux parties. il ne faut certainement pas dire que le premier password doit être le mail qui serait alors connu, ne resterait plus que le second à trouver pour connaître la clé privée.

Bonsoir, oui j'avais bien compris le principe, il y a un double password ce qui génère la clé unique. J'avais lu que l'email était suggéré en salt dans un tuto pour le test je suppose. 
Et à mon avis beaucoup de personnes risquent d'utiliser leur email... (par habitude, pour avoir la similitude avec le UID + password proposé sur la majorité des sites web).

> 
Qui plus est le mail a une durée de vie limitée aléatoire, tandis qu'un compte de monnaie libre doit pouvoir durer au moins la durée minimum de vie par certifications valides, qui est d'environ 3 ans, avant d'envisager de changer de clé.

Ok autant garder le salt alors...
Le problème c'est surtout  le navigateur qui peut enregistrer n'importe quel mot de passe.

> 
Aucun des deux passwords ne devrait être stocké par le navigateur, mais être gardé en lieux sûrs, en deux parties bien séparées (ce qui augmente la sécurité).

Encore une fois, je ne crois pas en la sagesse des utilisateurs à ce propos. Je pense que pour le coup de copier la méthode utilisée par les banques (et d'autres organismes) assure un masquage accru du password (enfin du PIN number en l’occurrence).
Par exemple:
https://voscomptesenligne.labanquepostale.fr/wsost/OstBrokerWeb/loginform?TAM_OP=login&ERROR_CODE=0x00000000&URL=%2Fvoscomptes%2FcanalXHTML%2Fidentif.ea%3Forigin%3Dparticuliers

A chaque chargement de ces pages l'emplacement des chiffres est changé.
Pour info, il s'agit d'un PIN à 6 chiffres.

En s’inspirant de cet authentification, l'usage du Wallet Cesium serait plus immédiat tout en étant correctement sécurisé il me semble. Quitte à passer à 8 chiffres...

L’association de l'identifiant_salt + pin_code permettant la génération de la clé privé habituelle.

**Comment by c-geek** [comment]
Une chose a bien comprendre le "salt" n'est pas juste un mot de passe, c'est aussi et surtout un identifiant. Je préfère parler d'*identifiant secret* pour parler du salt désormais.

A noter que rien n'oblige les clients tels Cesium/Sakia a utiliser ce mécanisme d'identifiant + mot de passe secrets. Il est tout à fait possible d'utiliser un trousseau fichier, enregistré sur son disque dur ou une clé usb. Mais jusqu'à maintenant, on a utilisé le 1er mécanisme. Pourquoi pas en proposer le 2ème ? Car il peut alors être protégé par mot de passe, code PIN, code-ce-qu'on-veut et qui surtout peut être changé, contrairement aux identifiant+mot de passe secrets de la 1ère méthode.

**Comment by pifpafpof** [comment]
Bonjour,

Le salt est l'identifiant ? Je pensais que c'était la clé l'identifiant, ok oui c'est logique sinon on ne pourrait pas changer le mot de passe. Merci pour la précision.
Oui autant parler identifiant secret c'est plus clair ! :-)

Le 2ième mécansime ça serait d'enregistrer sur le disque ou clé USB le mot de passe? C'est un complément du 1er alors ? Mais quid des smartphones qui devrait être une cible importante en terme d'usage de porte-monnaie ? Je ne comprends pas très bien. Les gens utilisent de plus en plus plusieurs PC, smartphone. Donc il faudrait un mécanisme de synchro des trousseaux de fichiers. N'est ce pas un peu lourd ? 

Ma proposition "simpliste" c'est :
identifiant secret (mais warning utilisateur car le navigateur peut l'enregistrer c'est à la responsabilité de l'utilisateur)
+ code PIN (8 chiffres à affichage aléatoire).

**Comment by galuel** [comment]
Rien ne dit que la connexion depuis un terminal douteux (les smartphones sont des terminaux douteux en terme de sécurité) doive être une connexion directe vers le réseau monétaire. Tout indique a contrario que les applications tournant sur des terminaux douteux envoient des propositions transactionnelles qui pourront être validées ultérieurement sur des terminaux de confiance.

**Comment by c-geek** [comment]
@pifpafpof-thomasL On ne peut pas changer le mot de passe quand on utilise la génération à la volée de la clé, comme c'est le cas dans Sakia / Cesium aujourd'hui.

C'est simple : l'identifiant secret et la clé secrète sont fusionnés ensembles et l'on applique sur cet agrégat une fonction de dérivation (un truc mathématique) qui génère alors notre trousseau final, trousseau qui lui peut être stocké quelque part sous forme de fichier, *et éventuellement protégé par un mot de passe*.

Mais tu comprends bien que, si le trousseau est le résultat de l'agrégation de l'identifiant + mot de passe secrets, alors changer l'un ou l'autre déforme totalement le trousseau, qui n'est alors plus le même. Donc, à ceux qui souhaitent utiliser la génération de trousseau à la volée : il faut juste qu'ils comprennent que cette mécanique empêche le changement de leur mot de passe.

Je le répète : cela ne les empêche pas de transformer leur trousseau "mémoire" en fichier, sur lequel il est possible d'appliquer un mot de passe, que l'on peut changer à l'envi.

N'hésites pas à relire plusieurs fois ce message pour bien comprendre.

**Comment by Tortue95** [comment]
Personnellement, pour les cryptomonnaies, la seule méthode qui me permet d’être confiant sur la sécurité dès mes unités de monnaie est le "Cold Paper Wallet" 
Pour ceux qui ne connaisse pas, l'idée est de générer une paire de clef Privée/Publique sur un ordi sans internet puis de l'imprimer sur papier (la clef privée peut-être également chiffrer par un mot de passe [bip38 pour le bitcoin]) 
Puis on envoie la plus grande partie de notre monnaie que l'ont désire placer en sécurité sur la clef publique du paper wallet. (et on garde une partie sur son compte pour les petites transactions courantes) lorsque l'on désire dépenser la monnaie présente sur le paper wallet, il suffit alors de rentrer la clef privée sur notre application cliente préférée (ou scan du Q. Rcode) afin de l'importer.
il n'y a donc aucun risque de piratage. (il faut juste bien mettre le paper wallet dans quelque chose d’étanche, et a l'abri des flammes)

Je ne sais pas ce que vous en pensez, mais du coup il pourrait être sympa d’intégrer dans cessium la possibilité d'importer des clefs publique à son compte. (pour connaitre la quantité de monnaie présente sur le paper wallet)
puis également d'importer des clef privé pour pouvoir dépensé la monnaie présente sur le paper wallet.

comme cela risque de ne pas être simple à implémenter rapidement, permettre simplement le login par clef privée (avec la possibilité de déchiffrer le bip38) serait sympathique.
