### ISSUE TITLE
Nombre de certifications reçues

### ISSUE THREAD

**Issue by vincentux** [duniter/cesium#182]
Dans l'onglet des certifications reçues ... le "compteur" n'a pas l'aire de fonctionner ...
C'est affiché 0 alors que trois personnes m'ont certifié.
![selection_009](https://cloud.githubusercontent.com/assets/11737560/19627309/58fcbbc4-9944-11e6-9457-48f310e07fda.jpg)

**Comment by blavenie** [comment]
@vincentux cela signifie que ces certifications ne sont pas encore inscrites dans la BlockChain.

Quele comportement / affichage pourrais-tu imaginer pour que cela te soit plus compréhensible ?

**Comment by vincentux** [comment]
> Quel comportement / affichage pourrais-tu imaginer pour que cela te soit plus compréhensible ?

Je sais pas, c'est juste que c'est pas très claire ... maintenant j'ai une notif :p 
![selection_011](https://cloud.githubusercontent.com/assets/11737560/19645855/307291f2-99f7-11e6-90bf-a2ffd60427df.jpg)

**Comment by vincentux** [comment]
Et sur la page d’accueil de mon compte par contre je suis toujours à zéro ... 

![selection_012](https://cloud.githubusercontent.com/assets/11737560/19646188/921cc69c-99f8-11e6-856d-33497ac96ecd.jpg)
