### ISSUE TITLE
Login: pubkey computation too long on smartphone

### ISSUE THREAD

**Issue by blavenie** [duniter/cesium#185]

**Comment by antoniovictor** [comment]
Sur mon PC, Cesium fonctionne bien. Je l’ai, avec votre aide, installé aux RML7 sur mon smartphone Wiko Lenny (Android 5,1). Ce n’est pas très puissant mais Cesium a fonctionné jusqu’à il y a au moins une semaine. J’étais alors sur la version v0.4.5. Aujourd’hui je suis passé à la v0.5.0 mais j’ai toujours le même problème ;
Quand je tente de me connecter à Cesium j’arrive à écrire ma «Phrase de protection» mais arrivé vers la moitié du « Mot de passe » la lettres que je tape ne s’affichent plus et ne sont plus remplacées par des points et le téléphone rame puis passe sur un écran noir dans les 5 à 10 secondes.
J’ai décoché  « Voir la phrase de protection » ;  dans un premier temps, Cesium n’affichait pas de clef publique à mesure que je tapais mon code. J’ai coché cette case et retenté ...échec. J’ai ensuite redécoché cette case mais un nouveau code s’affiche à chaque lettre tapée sans que je puisse rentrer le code complet. 
Si je commence par taper le mot de passe c’est, cette fois, au milieu de la phrase de protection que ça plante.
Sur l’écran d’accueil, avant la connexion, je vais dans « paramètres » ;   la section « Annonces, professionnels et messages privés » est marquée « désactivé ».  
Plus ou moins 15 tentatives de connection.
Bonsoir à vous tous.
Mententon 03

**Comment by JeanFe** [comment]
Je relance aussi pour le problème de connection au compte.
Je test une connexion via tablette à Cesium pour android téléchargé sur playstore. 
je me retrouve avec sablier infini: Echec du chargement des données du portefeuille.

À noter aussi que l'actualisation à la frappe du mot de passe ralenti très sensiblement la saisie.
