### ISSUE TITLE
Bizarre connexions settings and result

### ISSUE THREAD

**Issue by galuel** [duniter/cesium#19]
When trying to connect to Cesium : 

Why is there "adresse email" ? What does it mean ? When connecting to Sakia, I only can see : password required at the connection, choosing my account by my ID = Galuel. Why using different concepts ? A user could see what is needed : ID and password. If what you call "salt" has the same use than "ID", why not define technically "salt" as the "ID" ? It should be transparent for the end user.

When connecting with my "salt - email" + password, it seems to work, I'm then directed to what seems to be "account" page (not clear, no information just a logo and URL finishes with /wallet), and I can see a curious number "5uEpE9mN" that seems to be the "public key", but it doesn't match the public key in Sakia, so I suppose it is not correct.

No UD, and no transactions, it seems it is not at all the good account. But then : what is this account ? A new one ? A false one ? Not an account ? No information at all about what it is...

**Comment by galuel** [comment]
Il ne faut pas orienter l'utilisateur vers on email, car on donne des indications sur une partie de la clé, il vaut mieux dire la vérité : clé secrète + password = passphrase secrète en deux parties, à conserver séparément en deux parties distinctes (ce qui augmente la sécurité).

**Comment by galuel** [comment]
+ dans Cesium ce qui est appelé "email" devrait donc s'appeler "clé secrète" et ne pas apparaître en clair !

**Comment by M5oul** [comment]
> dans Cesium ce qui est appelé "email" devrait donc s'appeler "clé secrète" et ne pas apparaître en clair !

I don't find that shocking that the email parameter is displayed in clear.
I care a bit if someone know it.
This is a double authentication system like bank card + password.
If someone found my bank card (or my email address), it won't be easy to retrieve money from distributors without the password.
(I don't talk about online purchase which use an other authentication system).

**Comment by galuel** [comment]
`don't find that shocking that the email parameter is displayed in clear.`

It is not an "email parameter or ID" it is the salt. And salt+password = key phrase = secret crypto key. There is no sense to give any part of the crypto key. Better to keep all secret.

**Comment by M5oul** [comment]
Yep, you are right to use `salt` to name that parameter.

> There is no sense to give any part of the crypto key. Better to keep all secret.

Agreed.

There must be things to enhance security about salt + password parameters.
I found this authentication system a bit weak.
But I don't know more.
