### ISSUE TITLE
Message "demande d'adhésion invalide"

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#194]
Une personne désormais membre se voit afficher le message "demande d'adhésion invalide".

Le message est très bien, cela aide beaucoup l'utilisateur. Mais en l'occurrence il avait ce message depuis sa 1ère inscription (il était alors non-membre) puis a actualisé son adhésion et est désormais membre. Mais le message s'affiche toujours.

![image](https://cloud.githubusercontent.com/assets/969136/19959278/c689ecf2-a1a5-11e6-8e2b-be399994ac63.png)

**Comment by blavenie** [comment]
@c-geek c'est effectivement un nouveau message, depuis la détection du problème de document d'identité avec un mauvais `hash`.

Oui, je devrais donc considéré ce message inutile si la personne est membre.
Merci pour la remontée d'info.
