### ISSUE TITLE
To not allow to certify an identity twice

### ISSUE THREAD

**Issue by blavenie** [duniter/cesium#196]
A priori, si une identité a déja été certifiée, aucun intéret de la certifier encore ?
Du moins si la certification en encore valide.

@c-geek tu confirmes ?
Ou bien peut on renouveller une certification avant qu'elle ne prenne fin ?

**Comment by c-geek** [comment]
Tant qu'il existe une certification en cours de validité de la blockchain, il n'y a pas de rejeu possible.

On peut émettre de nouveau la même certification `sigWindow` temps avant la fin de validité de la précédente, pour espérer avoir une chance de l'écrire. Mais pas avant.

**Comment by blavenie** [comment]
> On peut émettre de nouveau la même certification sigWindow temps avant la fin de validité de la précédente, pour espérer avoir une chance de l'écrire. Mais pas avant.
Bien vu !
