### ISSUE TITLE
incorrect balance when using "refresh" button just after a transfer 

### ISSUE THREAD

**Issue by greyzlii** [duniter/cesium#20]
This bug can be reproduced with these steps : 
1/ Check your balance. The amount is «initial balance»
2/ Spend money «transfer amount»
At this time, the balance is correct. («initial balance» - «transfer amount»)

3/ Refresh your balance.
The balance is now incorrect. Its value comes back to «initial value» until new block generation.

**Comment by blavenie** [comment]
Fix in v0.1.6
