### ISSUE TITLE
Timelapse to see the peers !?

### ISSUE THREAD

**Issue by galuel** [duniter/cesium#204]
During 10 minutes or more fresh install of Cesium 0.50 didn't show the network (but I was able to see my account) : 

![cesium1](https://cloud.githubusercontent.com/assets/5245398/20205790/e876f3dc-a7db-11e6-81e2-6821fe27a8e2.png)

And then, suddenly when I was making the screen capture, the network of peers appeared : 

![cesium2](https://cloud.githubusercontent.com/assets/5245398/20205802/0784e4c8-a7dc-11e6-9dfb-3e382801e7b2.png)

This seems very strange to me, because to be sure I can see my account, I must suppose the client is connected to a large number of money peers, in order to be sure I'm on the main blockchain, and not on a fork who could give me wrong information about my balance and transactions.

So I must suppose that to be able to see my account, the client first establishes the network, and so the network should be shown first, before any information on my personal account.

**Comment by blavenie** [comment]
@galuel si je comprends bien tu as utilisé Cesium depuis ton navigateur. As tu gardé la configuration par défaut (sur le noeud e cgeek.fr:9330) ou bien était-ce sur un noeud à toi ?

Cesium ne récupère que les noeuds que lui donne le noeud avec lequel il communique. Si ce noeud (cgeek.fr:9330 ou autre) ne renvoi rien, alors impossible d'afficher quoi que ce soit...
