### ISSUE TITLE
bizarrerie au niveau de l'ergonomie du site

### ISSUE THREAD

**Issue by petiteberger** [duniter/cesium#212]
Quand on se connecte à son compte et qu'on met un mot de passe incorrect, le système, au lieu de signifier à l'utilisateur que le mot de passe est incorrect, crée une clé et donne l'impression qu'un nouveau compte est créé. Ca crée pas mal de confusion...

**Comment by blavenie** [comment]
Oui, il doit y avoir une régression sur ce point. Logiquement un avertissement devrait s'ouvrir, indiquant qu'une erreur a peut etre eu lieu dans la saisie des identifiants.

**Comment by blavenie** [comment]
Il y a bien un avertissement qui indique à l'utilisateur que le compte est vide, en lui demandant s'il veut continuer
