### ISSUE TITLE
Impoosible "d'acheter" une annonce

### ISSUE THREAD

**Issue by pifpafpof-thomasL** [duniter/cesium#216]
Pendant les RML8 j'ai vu que je ne pouvais pas payer le verre d'eau depuis mon mobile:

![screenshot_2016-11-19-16-31-03](https://cloud.githubusercontent.com/assets/22238028/20456375/dfbfdb50-ae75-11e6-9bb9-b743c4d3ea7c.png)

Pourtant depuis Firefox je peux bien payer:
![copie ecran cesium](https://cloud.githubusercontent.com/assets/22238028/20456413/919e2a98-ae76-11e6-8e7e-85f2ab615f5b.png)

**Comment by blavenie** [comment]
Bien vu l'ami ! ;)
