### ISSUE TITLE
Connexion: Mauvais remplissage automatique par le navigateur

### ISSUE THREAD

**Issue by blavenie** [duniter/cesium#220]
Petit bug remonté par [Cédric Liardet](http://cesium.duniter.fr/#/app/wot/z7iFQvEWw8NVtfGfhxpgpRqLGYDLbeKqkUsf15CV1bs/C%C3%A9dric%20Liardet) : 

> Quand je rentre la phrase de protection, on me propose de prendre celle qui est enregistrée et étrangement il n'y a pas le nombre de caractères correct, donc j'ai cliqué "voir la phrase de protection" et là il m'affiche mon mot de passe !

Navigateur utilisé : chrome

**Comment by Pafzedog** [comment]
Salut,
je venais justement pour déclarer ce problème.
J'ai l'impression que le navigateur confond le champ phrase de protection "salt" avec le champ "password" .
dès que le switch "afficher ce champ en clair" est activé, le navigateur reprend un comportement normal
et ne propose pas le mot de passe en lieu et place de la phrase secrète.

navigateur : Firefox 52

**Comment by blavenie** [comment]
duplicated of #228
