### ISSUE TITLE
Problème demande de membre

### ISSUE THREAD

**Issue by jacques74** [duniter/cesium#221]
Bonjour.
Nous nous sommes croisés à Toulouse, ma demande de membre n'avait pas été prise en compte et tu avais pris note.

Depuis quand je clique sur "Devenir membre" Cesium me demande mon login, le champs est pré-rempli, et quand je clic sur ok j'ai un message "Veuillez patienter" et rien ne se passe.

Voilà merci encore pour ton travail!
Bonne journée!

Jacques

**Comment by blavenie** [comment]
@jacques74 Bonjour Jacques ! As tu toujours le problème ?
Si oui, peux tu me contacter (par téléphone). Je t'envoi mes coordonnées par message privé.

**Comment by jacques74** [comment]
Non! J'ai pu m'inscrire le 14 décembre!
