### ISSUE TITLE
Support BMAS endpoints

### ISSUE THREAD

**Issue by Insoleet** [duniter/cesium#222]
Hi,

I think Cesium should support BMAS endpoints as soon as possible. Because without HTTPS,  an online Cesium  version can be injected with javascript by a malicious attacker. The user could see his private key get stolen for example.

I added a BMAS endpoint on my node (which is using a local Autority of Certification but you get the idea : http://testnet.duniter.inso.ovh/network/peering)
The format I used is the following : 

```BMAS [ipv4] [ipv6] [dns] [port]```

I think this is a critical issue since we want to start soon a production-ready currency. Using Cesium for new users would put them at a great risk. Plus, major browsers will soon start to flag [HTTP web pages as unsecured](https://www.theedesign.com/blog/2016/2017-year-ssl-https-websites).

**Comment by c-geek** [comment]
I suggest to add an optional `[path]` parameter at the end of the BMAS spec.
