### ISSUE TITLE
Retour suite à l'install party de Bordeaux

### ISSUE THREAD

**Issue by blavenie** [duniter/cesium#227]
See chat log : https://logs.duniter.org/duniter/2016-12-21/

**Comment by blavenie** [comment]
A priori les problèmes ont été : 
 - impossible de renveller un compte dont l'adhésion est expiré. Ceci vient d'une problème du CSS, dans Cesium 0.5.2. Le bouton est visible pour les petits écrans (masqué pour les grands).
Ce point est corrigé pour la v0.5.3
 - Erreur "maximum reached URL" : provient sans doute du fait qu'ils utilisait la même IP publique. Le noeud Duniter les a jetter par protection de deny de service.

**Comment by galuel** [comment]
Non il s'agissait de création de nouveaux comptes. Impossible de trouver le bouton "renouvellement" qui doit être utilisé pour demander l'adhésion avec des certifications (ou avant, j'en sais rien...)

**Comment by blavenie** [comment]
@galuel logiquement, il n'y a pas besoin de renouveller si on vient de créé un compte.

Lors de l'inscription par l'assistant "[Créer un compte](http://cesium.duniter.fr/#app/join)") (l'avez-vous utilisé ?) la demande d'adhésion est envoyé en même temps que la publication de l'identité.

Il doit y avoir un autre problème... peut-etre coté noeud Duniter. Je vais chercher.

**Comment by galuel** [comment]
"Lors de l'inscription par l'assistant "Créer un compte") (l'avez-vous utilisé ?) la demande d'adhésion est envoyé en même temps que la publication de l'identité"

Mais c'est pas du tout le protocole de Sakia !? Si ? Ne faut-il pas ici réaliser une demande volontaire, qui implique une signature ? Cela signifie-t-il que Cesium garde la clé secrète en mémoire !???
