### ISSUE TITLE
Connection > salt automatically filled by browser, with the password value

### ISSUE THREAD

**Issue by galuel** [duniter/cesium#228]
Quand on se connecte sur Cesium, il propose toujours "précisez pour quel utilisateur vous changez le mot de passe : xxx" où xxx est en fait la passphrase secrète, qu'il met en clair, et qu'il ne devrait en aucun cas pré-enregistrer !?

Les deux champs devraient être invisibles par défaut et non-enregistrés (il faudrait les saisir à chaque fois).

**Comment by galuel** [comment]
Ubuntu 16.04 / Firefox 50.1

**Comment by blavenie** [comment]
lié à https://github.com/duniter/cesium/issues/220 (sous chrome)

**Comment by blavenie** [comment]
Could probably be fixed using [attribute `autocomplete=off`](https://www.w3schools.com/tags/att_input_autocomplete.asp) on the `<form>` tag
