### ISSUE TITLE
Duniter shows me a weird account, it isn't mine

### ISSUE THREAD

**Issue by vindarel** [duniter/cesium#231]
Hi,
a few weeks ago I created an account, but someday I had a hard time logging in and finally I was logged to an empty account, with a weird name like "GBeuFD98". 

I had put personal settings, asked for the account validation, and everything disappeared.

Can I do something to recover my account ? is it lost ?

**Comment by blavenie** [comment]
Yes, this is a common issue. You may have used bad passphrase or passord. (Please not that the username should NOT be used for login : only pass phrase + password)

**Comment by vindarel** [comment]
Ok thanks, I got it, I think firefox went on my way by saving a bad passphrase or sthg.
