### ISSUE TITLE
Better french term to emit money

### ISSUE THREAD

**Issue by M5oul** [duniter/cesium#24]
Use an other term than `Payer` because we could also give money for donation…etc
`Émettre une transaction` could be a better term.

**Comment by blavenie** [comment]
ou `Envoyer` ?

**Comment by blavenie** [comment]
je ne trouve pas d'autre terme. Je ferme l'issue.
On verra si quelqu'une à une idée

**Comment by M5oul** [comment]
`Envoyer` c’est bien.
