### ISSUE TITLE
Transfer (virement) aborted

### ISSUE THREAD

**Issue by yann1108** [duniter/cesium#243]
version 0.9.2
Virement abort due to unknown fields or wrong line ending format
![screenshot-cesium monnaielibreoccitanie org 2017-01-13 01-27-30](https://cloud.githubusercontent.com/assets/272091/21913978/7b058aa8-d930-11e6-9790-cdbb3915b098.png)

**Comment by blavenie** [comment]
@yann1108 Sur quelle monnaie as tu essayer ?
La version 0.9.x de Cesium ne sont pas compatible avec Test_Net, mais seuklement avec les monnaie en protocole Duniter v0.90 ou +.

**Comment by blavenie** [comment]
Ajout d'une option de compatibilité (pour Duniter < 0.90), dans `config.js`: 
```json
   "compatProtocol_0_80": true,
```

**Comment by blavenie** [comment]
fixed in release 0.9.5
