### ISSUE TITLE
Ne pas afficher la puissance de 10 dans les mouvements

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#247]
J'ai fait cette remarque pour Sakia [ici (point 2.)](https://github.com/duniter/sakia/issues/552#issue-200866316).

Cela me paraît plus clair de ne pas afficher la puissance de façon répétitive, mais plutôt compter dans la base courante (qui ne change que tous les 23 ans).

**Comment by c-geek** [comment]
Note : cela demande d'afficher la base courante quelque part, et aussi d'afficher tous les mouvements dans la même base.

**Comment by c-geek** [comment]
Et le point 3 est aussi valable. Par exemple j'ai dû saisir le nombre 12000000000000 (12 x10¹²) dans TestNet pour faire une transaction en quantitatif, alors que la base courante étant 9, j'aurais pu simplement saisir 12000.

**Comment by blavenie** [comment]
> qui ne change que tous les 23 ans

@c-geek je me tromps où du coup on a 23 an pour résoudre ce bug ? ;)  (hors monnaie de test).

**Comment by c-geek** [comment]
Non je pense qu'on a moins que ça, car le `c` réel est > 10 au début de la monnaie tant que N n'est pas stable. Mais bon, ça se compte probablement en années quand même je pense.

**Comment by blavenie** [comment]
let's fix this in 10 years ;)
