### ISSUE TITLE
Nombre de noeuds membre

### ISSUE THREAD

**Issue by vincentux** [duniter/cesium#261]
Sur Cesium, je ne vois pas le même nombre de nœuds membre que sur Sakia : 

Cesium : 
![selection_036](https://cloud.githubusercontent.com/assets/11737560/22220968/3077790e-e1b1-11e6-9e2b-a2f519241e5f.jpg)

Sakia : 
![selection_034](https://cloud.githubusercontent.com/assets/11737560/22220981/4003f19a-e1b1-11e6-96ae-7cb2477efe6c.jpg)

**Comment by blavenie** [comment]
Oui, en l'occurance Cesium test ton noeud sur : http://10.2.126.5:8999/blockchain/current
alors qu'il n'est accessible que via : http://gtest.vincentux.fr:8999/blockchain/current

Il doit y avoir une erreur dans ta config : http://gtest.vincentux.fr:8999/network/peering
