### ISSUE TITLE
Flow/logic issue on new account

### ISSUE THREAD

**Issue by RavanH** [duniter/cesium#262]
After creating a new account in Cesium, the page Mon Profil cannot be opened. It shows "Erreur de chargement de profil utilisateur" which might seem logical since the account is not a user yet. But...

... after following the "Devenir membre" link in the Options menu on the account page, there is a new message in the Events list: "Pour obtenir vos certifications plus rapidement, completez votre profil utilisateur." with a link to... the profile page, which results in the error above.

**Comment by blavenie** [comment]
Could you check that "Settings > Cesium+ > node address" use "data.gtest.duniter.fr:80" ?

**Comment by blavenie** [comment]
cc @RavanH
