### ISSUE TITLE
Cesium : Affichage trompeur des certifications / Misleading certification informations

### ISSUE THREAD

**Issue by Darunya** [duniter/cesium#269]
Bonjour à tous,
Hi everyone,

---------------------

Sous Cesium, l'état des certifications validées / en attente est trompeur. Voici une capture d'écran pour vous illustrer cela :
Using Cesium, validated / pending certifications are misleading. Here a screenshot to show you that : 
![compte cesium](https://cloud.githubusercontent.com/assets/25332357/22268985/dc45837e-e289-11e6-8748-8b789984892b.jpg)
En effet "**Certifications reçues : 1 + :clock1: 1**" signifie naturellement "1 certification + 1 en attente". Or, il n'y a aucune certification de validée, ce devrait donc être "**0 + :clock1: 1**"
As you can see, "**Received certifications : 1 + :clock1: 1**" means ""1 certification + 1 pending". But there is no validated certification here, so it should be "**0 + :clock1: 1**"

Ou bien est-ce parce que les noeuds ne sont pas encore à jour, et qu'il y a bien 1 certification validée + 1 en attente ? Mais alors, si le compte a reçu l'information "1 certification validée", il devrait avoir également reçu les information concernant sont émetteur, non ? >< Parce que la ligne "Détail des certifications reçues" est vide...
Or maybe this is because blocks are not updated, and there is indeed 1 validated certification + 1 pending certification ? But then, if the account received "1 validated certification", it should have received all the sending informations right ? >< Because the "Received certifications detail" is empty...

---------------------

Et enfin, une suggestion mais peut-être pas réalisable : Transformer "Détail des certifications _reçues_" en "Détail des certifications **validées**", et rajouter une autre ligne qui serait "Détail des certifications en attente".
At least, maybe a suggestion, i don't know how hard it is to make that : Modify "_Received_ certifications detail" into "**Validated** certifications detail", and add another line named "Pending certifications detail".

---------------------

Voilà, si ce n'est pas le moment pour de telles remontées (ou si ça ne vous intéresse pas -mais ça serait surprenant lol), surtout n'hésitez pas à me le dire :)
If this is not the right time to give you such feedbacks (or if you're not interested in -which would be surprising lol), please let me know :)

En tout cas, bravo pour votre travail !!
Anyway, big up for your job !!

**Comment by blavenie** [comment]
Merci @Darunya. Oui, j'avais vu ce bug d'affichage, lié à un changement dans ce que renvoi les noeuds Duniter dans les dernières versions.
Ca va être corrigé, patience ;)

**Comment by Darunya** [comment]
Yes pas de souci, je ne suis pas stressé (ni particulièrement pressé) et puis ça ne fait pas partie des "priorités", ça c'est plus pour rendre le truc plus compréhensible pour l'utilisateur :)

Simplement je vous remonte l'info au cas où ;)
...C'est ma maigre façon de participer au projet :D
