### ISSUE TITLE
Bad timestamp for transaction

### ISSUE THREAD

**Issue by fluidlog** [duniter/cesium#27]
![bad timestamp cesium](https://cloud.githubusercontent.com/assets/6891994/15783529/d0b54cae-29ae-11e6-83cd-2cabbe99add8.png)
A "last transaction" 2 hour ago appear with 2H+12H = 14 hours ago.
It seems there is 12h of offset when record a transaction.
For example, In real life, Galuel has give me money at 15h (approximatively)

**Comment by M5oul** [comment]
Moved to https://github.com/duniter/duniter/issues/470.
