### ISSUE TITLE
Encadré didactitiel mal positionné

### ISSUE THREAD

**Issue by fiatou** [duniter/cesium#270]
Tout est dit dans le titre, voici la photo : 
![capture d ecran 2017-01-25 a 00 23 33](https://cloud.githubusercontent.com/assets/23424058/22271403/a946b64a-e294-11e6-9af8-ce536f5b75f3.png)

**Comment by fiatou** [comment]
La je chipote mais, ne sachant pas quel est votre degré de perfectionnisme dans votre travail... ;-)
![capture d ecran 2017-01-25 a 00 27 03](https://cloud.githubusercontent.com/assets/23424058/22271494/1988f54e-e295-11e6-8160-63dcd9c18363.png)

**Comment by blavenie** [comment]
Salut @fiatou : bravo pour la soumission sous GitHub ! Pour l'occasion je t'envoi des Gtest :)

Niveau perfectionnisme, je suis pas mal... mais j'essai de me contenir sinon rien n'avance.
Par exemple je connais ce problème dont tu parles, mais faire mieux me prendrait du temps que ne mettrais pas dans des point plus essentiel.

Bref, je le ferai... plus tard :)  

Ceci étant c'est c'est bien de le noter, pour ne pas l'oublier.

**Comment by blavenie** [comment]
@fiatou question, as tu vu que tu pouvais passer l'interface en Français ? (dans les paramètres)

**Comment by fiatou** [comment]
Oui super !! 👍 
Je commence ce soir la traduction de Cesium en Espagnol ;-)
