### ISSUE TITLE
Network peers order

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#283]
This is an enhancement I would love to see: today, peers are sorted `branch, member ASC`. What would be super cool would be to have `branch, member ASC, difficulty ASC`. So that the most probable peers to find the next block are listed first.

**Comment by blavenie** [comment]
One example :) 

![cesium_sort_peers](https://cloud.githubusercontent.com/assets/5269556/22344296/f0c9f320-e3fb-11e6-9997-dfd7bc7d8535.png)

**Comment by c-geek** [comment]
Wow! I want this :grinning:

**Comment by c-geek** [comment]
Good, I've tested on cesium@0.9.13. But the ordering does not work: I've clicked on "Difficulté" and never get a the difficulty ordered:

![image](https://cloud.githubusercontent.com/assets/969136/22368520/33dedc12-e487-11e6-9bd6-ce30446a92c2.png)
