### ISSUE TITLE
Network: the more we wait, the less we have peers

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#284]
After 20-30 minute, this is what Cesium shows me:

![image](https://cloud.githubusercontent.com/assets/969136/22334283/75b134b2-e3da-11e6-86ba-af344571dc92.png)

The more you wait, the less you have nodes displayed.

**Comment by blavenie** [comment]
@c-geek y a t'il eu des redémarrage de ton noeud gtest.duniter.org:10900 ?

En effet, lorsque la connection WebSocket est plantée, elle n'est pas aujourd'hui relancée....

Mais bon j'ai corriger encore des trucs. je relivre une 0.9.13 sous peu

**Comment by c-geek** [comment]
Non aucun, pas que je sache.

**Comment by c-geek** [comment]
Still occuring, unfortunately:

![image](https://cloud.githubusercontent.com/assets/969136/22369163/9142a5ca-e48a-11e6-9742-779737309b57.png)

**Comment by blavenie** [comment]
Je penses avoir trouvé : sans dote la protection liée à trop de requetes sur une noeud : 

```
[peers] Updating UI
cesium-6ab5804fa8.js:4 [network] Receiving block: 1257-00001DA89653405
cesium-6ab5804fa8.js:4 [network] new block received by WS: will refresh peers
vendor-6c17aa25da.js:12 GET http://gtest.duniter.org:10900/network/peering/peers?leaf=115E85D91F8C72475E4CAC3D09EEE26FEF473AE41248F49ACF95B3F1E1EE6CE9 503 (Service Unavailable)
```
