### ISSUE TITLE
Plantages en tout genre

### ISSUE THREAD

**Issue by fiatou** [duniter/cesium#289]
J'ai tenté d'envoyer un message sans insérer de destinataire (quoi de plus logique ?), et Cesium a planté juste après avoir affiché l'encadré "veuillez patienter..." :  
![capture du 2017-01-28 23-23-57](https://cloud.githubusercontent.com/assets/23424058/22400335/1227a3a2-e5b2-11e6-9991-aa94492b2099.png)

**Comment by Candidesk8** [comment]
j'ai la même !
merci fiatou d'avoir déjà remonté :)
