### ISSUE TITLE
Display medianTime in top header ?

### ISSUE THREAD

**Issue by vincentux** [duniter/cesium#290]
Moi je trouverai ça bien de mettre la date et l'heure blockchain dans le bandeau du haut, à coté des notifs de messagerie:

![selection_041](https://cloud.githubusercontent.com/assets/11737560/22432923/de54a654-e716-11e6-9eae-adb0cb0926c1.jpg)

Comme ça on l'aurait à chaque page. Qu'en penses-tu ?

**Comment by blavenie** [comment]
Oui, j'y ai pensé. Merci de me confirmer que cela serait une bonne idée ;)
Peut-etre seulement en mode expert, par contre, non ?

**Comment by vincentux** [comment]
Oui comme tu veux ;)

**Comment by blavenie** [comment]
Done in next release
But using a popup (in expert mode only)
![image](https://user-images.githubusercontent.com/5269556/27080076-9fe02190-503a-11e7-9718-3da042f4f983.png)
