### ISSUE TITLE
Android : open external links (e.g. Profile) in external browser

### ISSUE THREAD

**Issue by Candidesk8** [duniter/cesium#292]
In the profile page, there are external link, in order to proove that people are real.
I would like to be able to open this link in another app/browser

I've been browsing a picture site and coming back to cesium was a mess, because you can only jump from one page to the previous one.
with a 'open this link in another app/browser' option, i could have closed the other browser and be back to cesium in one triger

another idea is to have 'back to cesium' button....

**Comment by blavenie** [comment]
@Candidesk8 peux tu réexpliquer en Français ? Je ne suis pas sur de comprendre...
Merci ;)

**Comment by Candidesk8** [comment]
dans les pages de profil, il peut y avoir un lien externe, qui sert à prouver que les personnes sont bien réelles.
Je voudrai être en mesure d'ouvrir ce liens dans un autre navigateur.

Sur un  profil, le lien externe était un portfolio, j'ai parcouru plusieurs images et revenir au profil était long car je ne pouvais revenir que d'une page à la précédente.
Avec une option 'ouvrir ce lien dans un autre navigateur', j’aurais put fermer le navigateur et revenir à cesium en un click.

Une autre idée serait d'avoir un bouton, 'retour à cesium' ...

**Comment by blavenie** [comment]
@Candidesk8 actuellement, par exemple [sur ce profil](http://gtest.duniter.fr/#/app/wot/8KTEFQS78HwEz1NK627rNsYwENxNXJyvtyMAyfKPXZRB/gege53), si tu cliques sur le lien, cela ne t'ouvre pas un nouvelle page de ton navigateur ?

**Comment by Candidesk8** [comment]
Bonjour Kima
pour mémoire, mon tel est un FP1U sous Androïd 4.2.2
Voila pour te montrer que non, la page ne s'ouvre pas dans un nouveau navigateur, mais bien sous cesium v0.9.18 :)
![](https://framapic.org/pl4M36ql6ZT9/dUHp5abC3fCu)

**Comment by blavenie** [comment]
ok je comprend mieux, cela m'avait échapper que tu parlais d'un problème sur téléphone, et non via cesium-web. ;)
Je vais regarder comment faire.
merci !
