### ISSUE TITLE
proposition de reformulation

### ISSUE THREAD

**Issue by fiatou** [duniter/cesium#294]
Nous avons été plusieurs à trouver que la deuxième règle des règles de la toile de confiance lisible dans la rubrique "Monnaie" de cesium n'est pas juste comme il semble que les certifications ne soient valables que pour une période de 7 jours après quoi elle perdent leur validité. La voici suivit de la reformulation proposée :  "Délai maximal d’attente avant prise en compte d’une certification => Délai limite de prise en compte d’une certification".

**Comment by blavenie** [comment]
très bien, je vais intégré cela. VOici une proposition clairement formulée et concrète, donc facile à mettre en oeuvre ;)
