### ISSUE TITLE
taille des intitulés de membre sur page certification

### ISSUE THREAD

**Issue by Candidesk8** [duniter/cesium#295]
Bonjour,

Yann-Lug à un intitulé de membre très long (+ de 89 caractères)
à une trentaines de caractère, on est rendu à la fin du sous titre (raccourcit de clefs publique et timestamp)

Est il possible de n'afficher qu'un "extrait" des noms trop long afin de garder une vue sur les certifications données?

**Comment by blavenie** [comment]
fixed. Merci @Candidesk8 !
