### ISSUE TITLE
Remove old/error TX ?

### ISSUE THREAD

**Issue by blavenie** [duniter/cesium#298]
See https://forum.duniter.org/t/transaction-avortee/1714/13?u=kimamila

**Comment by PierreYvesC** [comment]
Maintenant 8 jours que les transactions avortées sont affichées "en cours de traitements" sur mon compte Césium.
:-)

**Comment by blavenie** [comment]
@PierreYvesC je te réponds "à la Stéphane" : _et qui sait combien de temps elles resteront ainsi, si tu ne trouves pas de nouveaux informaticiens pour résoudre ton problème. Il doit bien y en avoir en ardèche ?
Allez hop, zou, on se bouge !  bande de ..._    oups, non la j'exagère quand même ! arf ;)

**Comment by blavenie** [comment]
solve in Cesium 0.12.7 : tx not need to be kept in local storage
