### ISSUE TITLE
bug "se souvenir de moi" à la connexion

### ISSUE THREAD

**Issue by fiatou** [duniter/cesium#299]
Quand je me déconnecte puis me reconnecte en ayant sélectionné au préalable l'option "se souvenir de moi", je retrouve mon mot de passe à la place de la phrase de protection et donc plus de phrase de protection. 
Petite photo, c'est plus joli :+1: 
![capture du 2017-02-02 23-07-30](https://cloud.githubusercontent.com/assets/23424058/22570770/faf9eade-e99c-11e6-8460-699078da64f6.png)

**Comment by blavenie** [comment]
duplicate of https://github.com/duniter/cesium/issues/228
