### ISSUE TITLE
[ES] Search on registry : enable search on WOT

### ISSUE THREAD

**Issue by blavenie** [duniter/cesium#3]
Search on registry : enable search on WOT (by pubkey, uid.)

**Comment by mcl1234** [comment]
it seems to be done

**Comment by blavenie** [comment]
non, ce n'est pas encore réalisé pour la version de Cesium avec ES : la reche doit pouvoir ajouter des éléments du profile, qui ne sont pas dans le protocole, telles que : nom, prénom, infos de réseaux sociaux, etc. 
Mais c'est en bonne voie :)
