### ISSUE TITLE
Network: other icons

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#300]
Here is a suggestion to better differenciate visually members and mirror nodes:

![image](https://cloud.githubusercontent.com/assets/969136/22594674/5a8b5046-ea24-11e6-8b39-ca8d301b7fc4.png)

**Comment by blavenie** [comment]
@c-geek so you suggest to not use "globe" icon anymore ?
That fine for me

**Comment by c-geek** [comment]
Yes, exactly. The globe icon is cool, but does not carry useful information. Let's prefer a significant one!

**Comment by c-geek** [comment]
I don't know if you noticed: I removed the "member" or "mirror" icon near the uid/pubkey as a consequence of putting it at the place of the globe.

**Comment by blavenie** [comment]
Let's try like this : 
![image](https://cloud.githubusercontent.com/assets/5269556/22698672/7b01a0e4-ed55-11e6-8a2f-15a4199c7f56.png)

**Comment by c-geek** [comment]
Good idea :+1:
