### ISSUE TITLE
Default browser language not detected

### ISSUE THREAD

**Issue by blavenie** [duniter/cesium#317]
See @devingfx post : https://forum.duniter.org/t/demande-de-certification-thomas-alias-di-g/1778

> Sur Césium app Android, j'avais l'affichage en EN (par default) et puis je suis passé au FR dans Cesium web, de retour dans l'app Android, dans les settings je suis bien FR, mais les textes sont en anglais, il faut re switcher en EN, puis FR pour avoir l'interface en FR ...

**Comment by devingfx** [comment]
J'ai pu remarqué hier aussi que à l'inverse, sur Cesium web (desktop) j'avais l'interface en FR, mais dans la page des options le select était chargé sur Anglais.
Il y'a un soucis au niveau de la synchro des paramètres, en tout cas de langues!

Plus de détails si ca aide: 
je suis sous ChromeOS
Plate-forme 8872.76.0 (Official Build) stable-channel peppy
Micrologiciel Google_Peppy.4389.93.0
Donc avec Chrome Version 55.0.2883.105 (64-bit)

**Comment by blavenie** [comment]
Problème reproduit quand la locale du navigateur est `fr` et non `fr-FR`
