### ISSUE TITLE
probleme s/ commentaire dans message d'un virement

### ISSUE THREAD

**Issue by yann1108** [duniter/cesium#319]
Il y a rejet des commentaires dans le message lié à un virement
sur cesium.monnaielibreoccitanie.org --> version 0.9.20
(avec ou sans accent - le texte est rejeté (aka on peut pas envoyer le virement avec un commentaire - ça marche si on efface le commentaire et on envoie à vide)

![screenshot-cesium monnaielibreoccitanie org 2017-02-09 17-37-23](https://cloud.githubusercontent.com/assets/272091/22793045/f607a8de-eeee-11e6-85a1-46440c58a92e.png)

**Comment by blavenie** [comment]
Salut @yann1108  !
Non, c'ets la virgule je penses qui pose problème. tu peux essayer sans.

Je vais changer le message pour etre plus clair

**Comment by yann1108** [comment]
Effectivement j'avais raté la virgule,
je ferais attention 
- quelle est la raison technique pour cela ? (ancien ASCII ?)

**Comment by blavenie** [comment]
la raison: le procotole duniter ; )  
Il s'agit en fait plus d'une référence que d'un commentaire.

par ailleurs, avec @inso, nous devons mettre en place un chiffrement de ce champs. Cela devrait aussi régler le problème des virgules/accents, etc. puisqu'une fois encoder il ne sont plus visible par Duniter.

**Comment by blavenie** [comment]
> Je vais changer le message pour etre plus clair

Ah non en fait le message était déjà bon : les virgules étaient déjà indiquées dedans

**Comment by yann1108** [comment]
non, c'est moi qui vais changer de cerveau, pour être plus clair ;-)

**Comment by yann1108** [comment]
Au fait, on peut se parler par téléphone aujourd'hui ?

j'ai 3 sujets sur le feu :

1) je cherche encore quelqu'un pour la conférence qu'on a proposé à
Vincent (mais malade il ne peut la faire) sur Carrieres sous Poissy (une
journée sur la Monnaie) le 18 février.

2) perspective besoin codeurs et équipes de maintenance

3) Gchange [et autre "leboncoin.fr" ] la suite ? quels besoins?

a+
