### ISSUE TITLE
Cesium 0.9.24 mobile missing certify button

### ISSUE THREAD

**Issue by gpsqueeek** [duniter/cesium#323]
The certify button is not visible on my Android phone (Samsung Galaxy Note 1 - CyanogenMod 10.2 based on Android 4.3.1), neither in the app from the Google Store, nor in Firefox 51.0.3 for Android) so I could not certify anyone from my mobile phone... I looked in my certifications (sent / received) and in the person's certifications (sent / received) and could not find the white and red icon.

**Comment by blavenie** [comment]
@gpsqueeek dans quel page ? la page de certification ?
