### ISSUE TITLE
Cesium webapp : transfering monney

### ISSUE THREAD

**Issue by Candidesk8** [duniter/cesium#325]
from my account, ordering a monney transfert, cannot choose the recipient.

**Comment by blavenie** [comment]
@Candidesk8 peux tu m'en dire plus ?
Peux tu tester sur l'adresse : gtest.duniter.fr/debug.html  et me dire ce qu'il y a dans la console javascript ?

merci

**Comment by Candidesk8** [comment]
Bonjour KIMA,

j'ai lut récement le tutoriel n°1 ; si j'ai bien suivit, c'est dans chrome qu'on trouve la console JS?

**Comment by Candidesk8** [comment]
Adding String.prototype.format() -> was missing on this platform  cesium.js:21767:3
[settings] Trying to restore settings...  cesium.js:120:11
[settings] Restored  cesium.js:124:13
[ES] [user] Enable  cesium.js:16483:7
[ES] [notification] Enable  cesium.js:16811:7
[ES] Enable message extension  cesium.js:17326:7
[ES] [blockchain] Enable  cesium.js:17592:7
[app] Locale [fr-FR]  cesium.js:21698:5
Device service disable (no camera)  cesium.js:2406:7
Loading NaCl...  cesium.js:1035:9
Loaded NaCl in 52ms  cesium.js:1048:11
[ES] [user] Loading user data from ES node...  cesium.js:16183:7
[ES] [notification] Loading count from ES node...  cesium.js:16775:7
[ES] [notification] Successfully load count from ES node  cesium.js:16786:11
[ES] [message] Detecting 0 unread messages  cesium.js:16930:11
[ES] [user] Local settings already up to date  cesium.js:16137:13
Error from node (http://data.gtest.duniter.fr:80/user/profile/AmDcZSEB5MCt8GyZ1VMRt1sUwRH5D7HpXx8YKhMKZ1qa?&_source_exclude=avatar._content&_source=title,avatar._content_type)  vendor.js:34606:18
formatAmount: currentUD not defined  cesium.js:21368:9
[wallet] TX history loaded in 12440ms  cesium.js:3444:15
[wot] Loading identity 92UQQCi4...  cesium.js:5062:9
Blocage d’une requête multi-origines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur http://data.gtest.duniter.fr/user/profile/92UQQCi4kdQvio4XPE5KuXRGNhUginRFz7USy9xXkpyM?&_source_exclude=avatar._content. Raison : l’en-tête CORS « Access-Control-Allow-Origin » ne correspond pas à « (null) ».  (source inconnue)
Error from node (http://data.gtest.duniter.fr:80/user/profile/92UQQCi4kdQvio4XPE5KuXRGNhUginRFz7USy9xXkpyM?&_source_exclude=avatar._content)  vendor.js:34606:18
Error while loading identity data, on extension point.  cesium.js:5148:17
Error from node (http://data.gtest.duniter.fr:80/user/profile/92UQQCi4kdQvio4XPE5KuXRGNhUginRFz7USy9xXkpyM?&_source_exclude=avatar._content)  cesium.js:5149:17
[wallet] Identity 92UQQCi4 loaded in 6537ms  cesium.js:5155:13

**Comment by Candidesk8** [comment]
bon, en fait ça marche sur ton adresse debug/html

**Comment by Candidesk8** [comment]
et aussi sur http://gtest.duniter.fr/#/app/wallet.

bref, la prochaine fois, j'essaie de recharger la page avant de faire une issue ^^
