### ISSUE TITLE
language selection

### ISSUE THREAD

**Issue by Candidesk8** [duniter/cesium#326]
Hello, me again ;)

every time I open my cesium webclient, I have to set the language to french;
isn't it possible to have this setting bind with my account?

But, I realise that when I'm using my Cesium webapp on my android, it is always in french. I setted the remember me button on, so maybe it's beacause of this setting?

but couldn't it be done without having to conserve data on the machine?

**Comment by blavenie** [comment]
duplicated https://github.com/duniter/cesium/issues/317
