### ISSUE TITLE
Message on Android

### ISSUE THREAD

**Issue by Candidesk8** [duniter/cesium#329]
Trying to answer to message with the webapp but it freeze when attempting to send.

#### General information
* ** FairPhone FP1U :**
* ** Android 4.2.2 :**
* ** F-Droid :**
* ** v0.9.18 :**

#### Steps to reproduce
This is a new bug report. I am still using the application :-)

1. writing an answer to a private message
2. want to submit it, touching the button
3. the keyboard disappear but then it freeze

#### Expected result
**What is the expected output?** 
message is sent
**What do you see instead?**
my written message, unsent, webapp frozen.

Screenshot :
first attempt
![](https://framapic.org/SposFVLt3BDu/BFAiJTDl2f2r)

second attempt
![](https://framapic.org/kHZzaJtiFQn1/XmOYDsuq6jCX)

**Comment by blavenie** [comment]
@Candidesk8  Could you try again with the last version ? v0.9.31 (or more)  deployed on google play store or in the GH release page

**Comment by Candidesk8** [comment]
tried to install 9.31 and 9.32 unsucessfully.
I only could install 9.30 and the problem related here still occurs.

tell me if logs are needed.

**Comment by blavenie** [comment]
as tu essayé avec la 0.9.35 (à installer depuis la page github, fichier APK)

**Comment by Candidesk8** [comment]
oui et avec la 9.34 aussi, l'appli crash au démarage, de même que pour la .31 et la .32
j'ai réinstallé la .30 sur mon smartphone.

**Comment by blavenie** [comment]
@Candidesk8 peux tu essayer sur la dernière version 0.11.0 ou + ?

**Comment by Candidesk8** [comment]
J'ai le même problème depuis la 9.31 jusqu'à la 11.0,

**Comment by Candidesk8** [comment]
tu as sorti une 11.1, mais je pense qu'elle ne concerne que le bug relevé par cgeek et thatoo

**Comment by blavenie** [comment]
Pouvez-vous tester sur la version 0.12.6 ?
Elle corrige un soucis sur les messages, sous Android
