### ISSUE TITLE
Je ne vois pas mon statut membre ou non

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#33]

**Comment by blavenie** [comment]
Que veux tu dire ?
Es tu connecté avec ton UID normal, qu iest membre ?
Si oui, tu aimerais avoir par exemple ta date d'adhésion comme membre ? Autre chose ?

**Comment by c-geek** [comment]
J'ai écrit cela en pleine présentation aux RML7, et je ne me souviens plus du problème ..
