### ISSUE TITLE
Since V0.9.30, can't acces mys wallet ...

### ISSUE THREAD

**Issue by Candidesk8** [duniter/cesium#334]
An image is worth 100 words:
![](https://framapic.org/RIaDxSVcDT7q/HLvPxwIiSAQ0)
I enter my password but it's unable to go further than this.

**Comment by blavenie** [comment]
Merci pour tes remontées de bug. Cela m'aide vraiment.

En revanche, quand tu un soucis de blocage, j'ai besoin des logs javascript. 
Tu peux obtenir les logs détaillé sur <adresse de cesium>/debug.html  par exemple gtest.duniter.fr/debug.html

merci à toi

**Comment by blavenie** [comment]
@Candidesk8 peux tu tester sur la dernière version, si c'est mieux ?

**Comment by Candidesk8** [comment]
Voila les logs depuis la 9.32 : 

Sending message that cannot be cloned. Are you trying to send an XPCOM object?  MessageChannel.jsm:657:6
Not a diaspora* pod, move along...  (source inconnue)
Une chaîne vide a été transmise à « getElementById() ».  github-bc58d168780db26c31e2f011006ab3fc9eafbafe944e7fd8f297f55088e88229.js:6:14304
Une chaîne vide a été transmise à « getElementById() ».  frameworks-b0d504a21e5761da5ec5eade7ed594f51a8583550c5666e515607039056c976d.js:6:7699
TypeError: NetworkError when attempting to fetch resource.  (source inconnue)
Sending message that cannot be cloned. Are you trying to send an XPCOM object?  MessageChannel.jsm:657:6
Ce site semble utiliser un effet de positionnement lié au défilement. Cet effet pourrait ne pas fonctionner correctement avec le défilement asynchrone. Consultez https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects pour obtenir davantage de détails ou discuter des outils et des fonctionnalités liés.  Candidesk8
Sending message that cannot be cloned. Are you trying to send an XPCOM object?  MessageChannel.jsm:657:6
Sending message that cannot be cloned. Are you trying to send an XPCOM object?  MessageChannel.jsm:657:6
Sending message that cannot be cloned. Are you trying to send an XPCOM object?  MessageChannel.jsm:657:6
Not a diaspora* pod, move along...  (source inconnue)
Sending message that cannot be cloned. Are you trying to send an XPCOM object?  MessageChannel.jsm:657:6
Une chaîne vide a été transmise à « getElementById() ».  github-bc58d168780db26c31e2f011006ab3fc9eafbafe944e7fd8f297f55088e88229.js:6:14304
Une chaîne vide a été transmise à « getElementById() ».  frameworks-b0d504a21e5761da5ec5eade7ed594f51a8583550c5666e515607039056c976d.js:6:7699
Sending message that cannot be cloned. Are you trying to send an XPCOM object?  MessageChannel.jsm:657:6
Firefox ne peut établir de connexion avec le serveur à l’adresse wss://live.github.com/_sockets/VjI6MTU0MzkwMDc3OmNlODY5N2FiNjk0N2Q0NzAzMWRlNTIzZjI0NjJjODZjNzAwMGRiMjY2MjFjMTE5ZDJlMTBkZmIzNjQ5YjhlOTQ=--796794b66d30552a6c0c557cb0bba45dcbdadfff.  github-bc58d168780db26c31e2f011006ab3fc9eafbafe944e7fd8f297f55088e88229.js:5:16941
Sending message that cannot be cloned. Are you trying to send an XPCOM object?  MessageChannel.jsm:657:6
TypeError: NetworkError when attempting to fetch resource.  (source inconnue)
Sending message that cannot be cloned. Are you trying to send an XPCOM object?  MessageChannel.jsm:657:6
Une chaîne vide a été transmise à « getElementById() ».  frameworks-b0d504a21e5761da5ec5eade7ed594f51a8583550c5666e515607039056c976d.js:6:7699
Sending message that cannot be cloned. Are you trying to send an XPCOM object?  MessageChannel.jsm:657:6
TypeError: NetworkError when attempting to fetch resource.  (source inconnue)
Une chaîne vide a été transmise à « getElementById() ».  frameworks-b0d504a21e5761da5ec5eade7ed594f51a8583550c5666e515607039056c976d.js:6:7699
Sending message that cannot be cloned. Are you trying to send an XPCOM object?  MessageChannel.jsm:657:6
TypeError: NetworkError when attempting to fetch resource.  (source inconnue)
Sending message that cannot be cloned. Are you trying to send an XPCOM object?  MessageChannel.jsm:657:6

**Comment by blavenie** [comment]
Je penses qu'il doit y avoir une erreur dans ta capture de log, car les scripts référencé (`MessageChannel.jsm`) ne sont pas liés à Cesium. 

Tu as peut-etre installé des plugins dans ton navigateur, qui empêche le bon fonctionnement de Cesium. Je te conseille de les déactiver et de retester.

On ré-ouvrir ce ticket si besoin

**Comment by Candidesk8** [comment]
nouvelle tentative de capture de logs en v0.9.33

Successfully compiled asm.js code (total compilation time 2263ms; caching disabled in FF51 due to bug; will be reenabled in FF52)  vendor.js
Successfully compiled asm.js code (total compilation time 296ms; caching disabled in FF51 due to bug; will be reenabled in FF52)  vendor.js
Adding String.prototype.format() -> was missing on this platform  cesium.js:23182:3
[settings] Trying to restore settings...  cesium.js:121:11
[settings] Restored  cesium.js:125:13
[ES] [user] Enable  cesium.js:17768:7
[ES] [notification] Enable  cesium.js:18096:7
[ES] [message] Enable  cesium.js:18616:7
[ES] [blockchain] Enable  cesium.js:18882:7
[app] Locale [fr]  cesium.js:23113:5
[ionic] Platform is ready  cesium.js:2741:13
[device] No device detected  cesium.js:2851:11
[crypto] Loading FullJS implementation...  cesium.js:1417:9
[crypto] Loaded  'FullJS' implementation in 146ms  cesium.js:1429:11
Champs mot de passe présents sur une page non sécurisée (http://). Cela représente un risque de sécurité permettant le vol d’identifiants de connexion.[En savoir plus]  debug.html
[ES] [user] Loading user data from ES node...  cesium.js:17440:7
[ES] [notification] Loading count from ES node...  cesium.js:18060:7
[ES] [notification] Successfully load count from ES node  cesium.js:18071:11
[ES] [message] Detecting 1 unread messages  cesium.js:18215:11
Blocage d’une requête multi-origines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur http://data.gtest.duniter.fr/user/profile/AmDcZSEB5MCt8GyZ1VMRt1sUwRH5D7HpXx8YKhMKZ1qa?&_source_exclude=avatar._content&_source=title,avatar._content_type. Raison : l’en-tête CORS « Access-Control-Allow-Origin » ne correspond pas à « (null) ».  (source inconnue)
[wallet] TX history loaded in 5732ms  cesium.js:3888:15
[ES] [blockchain] Enable  cesium.js:18882:7
Error from node (http://data.gtest.duniter.fr:80/user/profile/AmDcZSEB5MCt8GyZ1VMRt1sUwRH5D7HpXx8YKhMKZ1qa?&_source_exclude=avatar._content&_source=title,avatar._content_type)  vendor.js:34606:18
Blocage d’une requête multi-origines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur http://data.gtest.duniter.fr/user/profile/AmDcZSEB5MCt8GyZ1VMRt1sUwRH5D7HpXx8YKhMKZ1qa?&_source_exclude=avatar._content. Raison : l’en-tête CORS « Access-Control-Allow-Origin » ne correspond pas à « (null) ».  (source inconnue)
Error from node (http://data.gtest.duniter.fr:80/user/profile/AmDcZSEB5MCt8GyZ1VMRt1sUwRH5D7HpXx8YKhMKZ1qa?&_source_exclude=avatar._content)  vendor.js:34606:18
GET 
http://gtest.duniter.fr/dist_css/cesium.css [HTTP/1.1 200 OK 0 ms]
