### ISSUE TITLE
Pourquoi se connecte-ton avec sa phrase de protection ?

### ISSUE THREAD

**Issue by fbuland** [duniter/cesium#34]
Pourquoi se connecte-ton avec sa phrase de protection et pourquoi pas avec son username ? Comme sur Sakia.
Cela veut donc dire que la phrase de protection doit être unique ?
merci
Franck Buland

**Comment by blavenie** [comment]
sur Sakia on utilise aussi sa phrase de protection (salt) mais peut-être pas saisi à chaque fois ?

cette phrase sert à mélanger le mot de passe.

La phrase de protection n'a pas besoin d'être unique, mais seulement : tu ne dois pas l'oublier !
