### ISSUE TITLE
Deconnexion suite rafraichissement (F5)

### ISSUE THREAD

**Issue by vincentux** [duniter/cesium#341]
Mon compte se déconnecte après un F5 sur la page. 
Pourtant j'ai bien "Se souvenir de moi" de coché, @c-geek tu as la même chose que moi il me semble ?
Cesium 0.9.32 sur Firefox.

**Comment by c-geek** [comment]
Tu peux ignore la fenêtre, ton compte reste bien connecté.

**Comment by M5oul** [comment]
Avant j’utilisais Césium sans cocher _Se souvenir de moi_, et tout en conservant une session active, j’étais déconnecté lorsque je naviguais dans l’interface de Césium.
Puis, j’ai découvert cette coche, et depuis, je reste connecté.
C’est embêtant si l’on souhaite utiliser Césium sur une machine ne nous appartenant pas.
Le bug que je décris doit également être lié.
