### ISSUE TITLE
Ğ1 identifiants rémanents

### ISSUE THREAD

**Issue by JeanFe** [duniter/cesium#342]
Sur monnaie Ğ1 si j'active à la connexion l'option "se souvenir de moi" Cesium/G1/ malgré une saisie correcte affichant la bonne clef publique sur l'écran de log, une fois connecté, c'est la clef publique de Ğtest qui s'affiche.

**Comment by blavenie** [comment]
peux tu essayer de réinitialiser tes paramètres ?
