### ISSUE TITLE
membre / non-membre

### ISSUE THREAD

**Issue by Carolef** [duniter/cesium#343]
si on met un mauvais identifiant password, on arrive sur un compte non-membre, mais on ne s'en rend pas compte de suite, surtout qu'on a l'impression que la certification marche ...
Ne serait-il pas mieux de faire une inscription autre pour les non-membres ? 
lien vers le sujet du forum
https://forum.duniter.org/t/presentation-membre-carolefabre/1836/41

**Comment by blavenie** [comment]
La monnaie n'est pas encore lancée, quand elle le sera, ce type de connexion déclenche une ouverture d'une boite de dialogue d'avertissement.
