### ISSUE TITLE
Message corrompu

### ISSUE THREAD

**Issue by yann1108** [duniter/cesium#350]
Remontée d'un incident sur la Gtest :
je n'ai pas pu ouvrir le message,
mais il semble que le contenu soit "particulier"
c'est un gars de Montpellier qui voulait être certifie sur cette monnaie...
J'ai vérifié l'authenticité - tout est correct, sauf son message ...

![screenshot-cesium monnaielibreoccitanie org 2017-02-22 12-25-18](https://cloud.githubusercontent.com/assets/272091/23209711/a1d5c7b2-f8fa-11e6-859c-45340fb64cfb.png)
![screenshot-cesium monnaielibreoccitanie org 2017-02-22 12-25-51](https://cloud.githubusercontent.com/assets/272091/23209712/a1defb7a-f8fa-11e6-92cd-1ec6d620410e.png)

**Comment by yann1108** [comment]
Il s'agit du 1er dans la liste "Nicolas" alias Nico34

**Comment by blavenie** [comment]
Oui, ce bug a été corrigé. Simplement les messages qui ont été généré pendant que le bug étaient actifs sont a jetter. (tu peux le faire en glissant le message dans la liste, sur la gauche)
