### ISSUE TITLE
Problème Certification sur "mars3" dans Gtest

### ISSUE THREAD

**Issue by yann1108** [duniter/cesium#354]
"mars3" est un nouveau membre toulousain,
mais qui semble avoir un problème de paramétrage de son compte.
sa clé publique est :
GJAF5y9eLWJWSCp4ATVp4vELWyxT2G7aftqkGxHksBh5
il y a rejet de la demande de certification (le compte ne semble pas complètement fini et/ou inscrit)
Pourtant à midi jeudi 23/02 - il avait eu 4 certifications qui semblaient être en attente sans problème.

![screenshot-gtest duniter fr 2017-02-24 01-08-45](https://cloud.githubusercontent.com/assets/272091/23284930/5f11c658-fa2e-11e6-9b44-d77fc0160dc9.png)

**Comment by blavenie** [comment]
Le bug est en fait que le bouton est affiché, alors que ce compte n'a plus de demande d'adhésion en attente.

Corrigé pour la v0.9.36
