### ISSUE TITLE
bug repport

### ISSUE THREAD

**Issue by Candidesk8** [duniter/cesium#356]
Trying to refresh the payement hystory after a payement.

**General information**

Device    ** laptop netbook samsung NC10 :**
OS    ** Lubuntu 16.10 :**
Source    ** Github :**
Version    ** v0.9.35 :**

Steps to reproduce

 sent a payement to remuniter
    want to know if it is written in blockchain, so I tried to refresh my history
    got an error message

Expected result

What is the expected output?
my transactions refreshed
What do you see instead?
error message.

Screenshot :
![](https://framapic.org/ttUqIxnov1PS/GiThfGtVnqtd)

JS logs

Adding String.prototype.format() -> was missing on this platform  cesium.js:24520:3
[settings] Loading from local storage...  cesium.js:135:11
[settings] Loaded from local storage in 9ms  cesium.js:201:11
[BMA] Starting [gtest.elois.org:80]...  cesium.js:3206:7
[app] Locale [fr-FR]  cesium.js:24451:5
[device] Ionic platform ready - no device detected.  cesium.js:2833:15
[crypto] Loading FullJS implementation...  cesium.js:1426:9
[ES] [http] Starting on [data.gtest.duniter.fr:80]...  cesium.js:16859:7
[crypto] Loaded 'FullJS' implementation in 301ms  cesium.js:1438:11
[http] TODO: implement check version [0.90.8] compatible with [0.90.0]  cesium.js:2661:5
[BMA] Started in 7050ms  cesium.js:3222:11
[ES] [http] Could not start [data.gtest.duniter.fr:80]: node unreachable  cesium.js:16866:13
[ES] node could not be started !!  cesium.js:17488:15
[wallet] TX history loaded in 5188ms  cesium.js:4133:15
[wallet] TX history reloading...  cesium.js:9108:5
[wallet] TX history loaded in 2446ms  cesium.js:4133:15
Error from node (http://gtest.elois.org:80/wot/certified-by/AmDcZSEB5MCt8GyZ1VMRt1sUwRH5D7HpXx8YKhMKZ1qa)  cesium.js:1596:9
[ES] [http] Starting on [data.gtest.duniter.fr:80]...  cesium.js:16859:7
[ES] [settings] Loading user settings...  cesium.js:17341:7
[ES] [http] Could not start [data.gtest.duniter.fr:80]: node unreachable  cesium.js:16866:13
[ES] node could not be started !!  cesium.js:17488:15
Error from node (http://data.gtest.duniter.fr:80/user/settings/AmDcZSEB5MCt8GyZ1VMRt1sUwRH5D7HpXx8YKhMKZ1qa)  vendor.js:34606:18
[ES] [http] Starting on [data.gtest.duniter.fr:80]...  cesium.js:16859:7
[ES] [settings] Loading user settings...  cesium.js:17341:7
[ES] [http] Could not start [data.gtest.duniter.fr:80]: node unreachable  cesium.js:16866:13
[ES] node could not be started !!  cesium.js:17488:15
Error from node (http://data.gtest.duniter.fr:80/user/settings/AmDcZSEB5MCt8GyZ1VMRt1sUwRH5D7HpXx8YKhMKZ1qa)  vendor.js:34606:18
[app] Locale [en]  cesium.js:24451:5
[ES] [http] Starting on [data.gtest.duniter.fr:80]...  cesium.js:16859:7
[ES] [settings] Loading user settings...  cesium.js:17341:7
[ES] [http] Could not start [data.gtest.duniter.fr:80]: node unreachable  cesium.js:16866:13
[ES] node could not be started !!  cesium.js:17488:15
Error from node (http://data.gtest.duniter.fr:80/user/settings/AmDcZSEB5MCt8GyZ1VMRt1sUwRH5D7HpXx8YKhMKZ1qa)  vendor.js:34606:18
[ES] [http] Starting on [data.gtest.duniter.fr:80]...  cesium.js:16859:7
[ES] [settings] Loading user settings...  cesium.js:17341:7
[wot] Loading identity AmDcZSEB...  cesium.js:5891:11
Error from node (http://data.gtest.duniter.fr:80/user/settings/AmDcZSEB5MCt8GyZ1VMRt1sUwRH5D7HpXx8YKhMKZ1qa)  vendor.js:34606:18
[ES] [http] Could not start [data.gtest.duniter.fr:80]: node unreachable  cesium.js:16866:13
[ES] node could not be started !!  cesium.js:17488:15
Error from node (http://gtest.elois.org:80/blockchain/block/703)  vendor.js:34606:18
Error from node (http://gtest.elois.org:80/blockchain/block/703)  cesium.js:1596:9
ERROR: in help tour  [certs], in step [0] : [helptip] element now found: helptip-certs-certify  cesium.js:7598:11
[wallet] TX history reloading...  cesium.js:9108:5
[wallet] TX history loaded in 5859ms  cesium.js:4133:15
[ES] [http] Starting on [data.gtest.duniter.fr:80]...  cesium.js:16859:7
[ES] [settings] Loading user settings...  cesium.js:17341:7
[ES] [http] Started in 632ms  cesium.js:16869:11
[ES] [user] Enable  cesium.js:18461:7
[ES] [user] Loading user avatar+name...  cesium.js:18183:7
[ES] [notification] Enable  cesium.js:18796:9
[ES] [notification] Loading count...  cesium.js:18728:7
[ES] [message] Enable  cesium.js:19309:9
[ES] [message] Loading count...  cesium.js:18882:7
[ES] [group] Enable  cesium.js:19725:9
[ES] [settings] Enable  cesium.js:17491:15
[ES] [settings] Loading user settings...  cesium.js:17341:7
[ES] [notification] Loaded count (106) in 1475ms  cesium.js:18740:11
[ES] [notification] Starting listen user event...  cesium.js:18749:11
[http] Listening on websocket [/ws/event/user/:pubkey/:locale]...  cesium.js:2571:11
[ES] [message] Loaded count (1) in 1600ms  cesium.js:18890:11
[ES] [group] Detecting 0 unread notifications  cesium.js:19584:11
[ES] [settings] Loaded user settings in 4158ms  cesium.js:17306:15
[ES] [settings] Successfully load settings from ES  cesium.js:17352:11
[wot] Loading identity AmDcZSEB...  cesium.js:5891:11
[ES] [settings] Loaded user settings in 3712ms  cesium.js:17306:15
[ES] [settings] Successfully load settings from ES  cesium.js:17352:11
Error from node (http://data.gtest.duniter.fr:80/user/profile/AmDcZSEB5MCt8GyZ1VMRt1sUwRH5D7HpXx8YKhMKZ1qa?&_source_exclude=avatar._content&_source=title,avatar._content_type)  vendor.js:34606:18
[wot] Identity CandideSK8 will need 3 certification(s)  cesium.js:5844:11
Error from node (http://data.gtest.duniter.fr:80/user/profile/AmDcZSEB5MCt8GyZ1VMRt1sUwRH5D7HpXx8YKhMKZ1qa?&_source_exclude=avatar._content)  vendor.js:34606:18
Error while loading identity data, on extension point.  cesium.js:5978:17
Error from node (http://data.gtest.duniter.fr:80/user/profile/AmDcZSEB5MCt8GyZ1VMRt1sUwRH5D7HpXx8YKhMKZ1qa?&_source_exclude=avatar._content)  cesium.js:5979:17
[wot] Identity AmDcZSEB loaded in 3419ms  cesium.js:5986:13
[ES] [settings] Saving user settings... at time 1488054778  cesium.js:17416:7
[ES] [settings] Saved user settings in 1ms  cesium.js:17447:11
[ES] [message] All messages decrypted in 552ms  cesium.js:19184:11
[message] marked as read  cesium.js:22898:23
[wot] Identity AmDcZSEB found in cache  cesium.js:5888:13
[ES] [settings] Saving user settings... at time 1488054902  cesium.js:17416:7
[ES] [settings] Saved user settings in 1ms  cesium.js:17447:11
[wot] Will search on: 'julien'  cesium.js:6012:15
[wallet] Amount has been truncate to 10  cesium.js:4602:13
[wot] Loading identity AdnytaKr...  cesium.js:5891:11
Error from node (http://data.gtest.duniter.fr:80/user/profile/AdnytaKroFsrux4DhLR2QjzBtCn7QTaPQzJkC6uJjqqQ?&_source_exclude=avatar._content)  vendor.js:34606:18
Error while loading identity data, on extension point.  cesium.js:5978:17
Error from node (http://data.gtest.duniter.fr:80/user/profile/AdnytaKroFsrux4DhLR2QjzBtCn7QTaPQzJkC6uJjqqQ?&_source_exclude=avatar._content)  cesium.js:5979:17
[wot] Identity AdnytaKr loaded in 2750ms  cesium.js:5986:13
[ES] [settings] Saving user settings... at time 1488055090  cesium.js:17416:7
[ES] [settings] Saved user settings in 1ms  cesium.js:17447:11
[currency] Parameters loaded in 1403ms  cesium.js:11144:7
[ES] [settings] Saving user settings... at time 1488055102  cesium.js:17416:7
[ES] [settings] Saved user settings in 1ms  cesium.js:17447:11
[wallet] TX history reloading...  cesium.js:9108:5
Error from node (http://gtest.elois.org:80/blockchain/block/703)  cesium.js:1596:9
[wallet] TX history loaded in 15868ms  cesium.js:4133:15
Error from node (http://gtest.elois.org:80/blockchain/block/9081)  vendor.js:34606:18

**Comment by blavenie** [comment]
le noeud ElastixSearch (qui contient les profile Cesium+) était HS
