### ISSUE TITLE
création de compte sous G1

### ISSUE THREAD

**Issue by Candidesk8** [duniter/cesium#357]
un bug, cesium ne charge pas les monnaies:
![](https://framapic.org/e7LJGeF13w72/wQru5G8DxI6Y)
mes logs : 
Successfully compiled asm.js code (total compilation time 2042ms; caching disabled in FF51 due to bug; will be reenabled in FF52)  vendor.js
Successfully compiled asm.js code (total compilation time 287ms; caching disabled in FF51 due to bug; will be reenabled in FF52)  vendor.js
Adding String.prototype.format() -> was missing on this platform  cesium.js:23182:3
[settings] Trying to restore settings...  cesium.js:121:11
[settings] Restored  cesium.js:125:13
[ES] [user] Enable  cesium.js:17768:7
[ES] [notification] Enable  cesium.js:18096:7
[ES] [message] Enable  cesium.js:18616:7
[ES] [blockchain] Enable  cesium.js:18882:7
[app] Locale [fr]  cesium.js:23113:5
[ionic] Platform is ready  cesium.js:2741:13
[device] No device detected  cesium.js:2851:11
[crypto] Loading FullJS implementation...  cesium.js:1417:9
[crypto] Loaded  'FullJS' implementation in 130ms  cesium.js:1429:11
Error from node (https://g1.duniter.org:443/blockchain/parameters)  vendor.js:34606:18
Error from node (https://g1.duniter.org:443/blockchain/parameters)  cesium.js:1587:9

**Comment by blavenie** [comment]
Duniter node was just down. Not a bug.
I just fix the message, to display : `Unable to load currencies. Please retry later.`
