### ISSUE TITLE
Problème d'affichage sur les certification envoyées 

### ISSUE THREAD

**Issue by wwann** [duniter/cesium#359]
J'ai certifié 3 utilisateurs à la suite.
Les certifications sont bien envoyées aux 3 utilisateurs (on les voit sur leurs comptes respectifs). 
Mais sur ma page des certifs, les 3 dernières certifications envoyées affichent 3 fois mon identité au lieu des personnes certifiées. 

Voir screenshot.
https://duniter.fr/g1/#/app/home

![image](https://cloud.githubusercontent.com/assets/17970991/23341515/573659b8-fc49-11e6-931e-de70415bbdac.png)

Problème réglé après rechargement 
![image](https://cloud.githubusercontent.com/assets/17970991/23341554/09e0d4f8-fc4a-11e6-9425-148c6b6ef100.png)

**Comment by M5oul** [comment]
Duplicate https://github.com/duniter/cesium/issues/349.
