### ISSUE TITLE
2 comptes avec la même clé publique

### ISSUE THREAD

**Issue by fbuland** [duniter/cesium#36]
Il y a les comptes Sybille et SybilleSG qui ont la même clé publique, est-ce normal ?
Si j'affiche le compte Sybille ou SybilleSG, et que je vais voir ses certifications, une erreur s'affiche : "Weird, the signature is wrong and in the database."

Merci
Franck

**Comment by fbuland** [comment]
Les 2 comptes dans l'annuaire :
![compte_sybille_pb](https://cloud.githubusercontent.com/assets/19709395/15804659/e7d3146c-2b10-11e6-9509-811796389984.JPG)

**Comment by blavenie** [comment]
Ce n'est pas un bug : Duniter permet de publier plusieurs fois un uid sur une même clé publique. Mais une seul pourra rencontrer dans la BlockChain comme membre.

ex: http://cgeek.fr:9330/wot/lookup/sybille

**Comment by mcl1234** [comment]
Quel est le processus pour changer d'identifiant utilisateur de cette façon via l'explorateur ?
