### ISSUE TITLE
My account: events not refreshed when locale change

### ISSUE THREAD

**Issue by Candidesk8** [duniter/cesium#362]
#### General information
* Device ** FairPhone FP1U :**
* OS ** Android 4.2.2 :**
* Source ** Github :**
* Version ** v0.9.30 :**

#### Steps to reproduce

1. changing language in settings
2. get to my account
3. read the warning information's (you will soon lack of certifications, your membership will be over in xx days)

#### Expected result
**What is the expected output?** 
message is in the selected language
**What do you see instead?**
message is always in French.

Screenshot :
if needed.

**Comment by blavenie** [comment]
Angular directive `trustAsHtml` should be fixe, to be aware of changement in its content

**Comment by blavenie** [comment]
fix in v0.18.3
