### ISSUE TITLE
Profile: Hashtag regexp

### ISSUE THREAD

**Issue by blavenie** [duniter/cesium#366]
As @cgeek [says](https://forum.duniter.org/t/release-cesium-v0-10-0/1966/5?u=kimamila), Cesium+ profile does not recognize tags with accent, like `#développeur`

The regexp use for hashtag is: 
```
        HASH_TAG: match('#([\\wḡĞğ]+)')
```

**Comment by blavenie** [comment]
@c-geek as tu une idée de meilleur regexp ? (Je ne vois pas comment inclure les accents, en fait...)

**Comment by c-geek** [comment]
You could add `àáâãäåçèéêëìíîïðòóôõöùúûüýÿ` also.
