### ISSUE TITLE
In certification panel, at 1st level show UID instead of Pubkey

### ISSUE THREAD

**Issue by fbuland** [duniter/cesium#367]
On the right column, the UID is displayed at 1st level, which is useful.
I suggest to do the same on the left column.
![image](https://cloud.githubusercontent.com/assets/19709395/23480086/ec36048a-fec6-11e6-9bad-6aefc7447528.png)

Franck

**Comment by blavenie** [comment]
ce n'est pas un bug, c'est le comportement normale sur g1, car le noeud n'est pas encore pleinnement fonctionnel (la blockchain n'est pas encore lancée)
