### ISSUE TITLE
Cesium 0.10.2 > crash on Android/cm

### ISSUE THREAD

**Issue by gpsqueeek** [duniter/cesium#368]
When starting the app, the logo is displayed properly but then the app crashes using my Samsung galaxy note (n7000) running CyanogenMod (android 4.3). The logs are the following :

I/ActivityManager( 2241): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=fr.duniter.cesium/.MainActivity} from pid 21279
I/ActivityManager( 2241): Start proc fr.duniter.cesium for activity fr.duniter.cesium/.MainActivity: pid=21298 uid=10087 gids={50087, 3003, 1015, 1006, 1028}
D/XWalkLib(21298): Pre init xwalk core in fr.duniter.cesium.MainActivity
D/XWalkLib(21298): Reserve class class org.xwalk.core.XWalkPreferences to fr.duniter.cesium.MainActivity
D/XWalkLib(21298): Reserve method setValue to fr.duniter.cesium.MainActivity
D/XWalkLib(21298): Reserve class class org.xwalk.core.XWalkPreferences to fr.duniter.cesium.MainActivity
D/XWalkLib(21298): Reserve method setValue to fr.duniter.cesium.MainActivity
D/XWalkLib(21298): Reserve class class org.xwalk.core.XWalkPreferences to fr.duniter.cesium.MainActivity
D/XWalkLib(21298): Reserve method setValue to fr.duniter.cesium.MainActivity
D/XWalkLib(21298): Reserve object class org.crosswalk.engine.XWalkCordovaView to fr.duniter.cesium.MainActivity
D/XWalkLib(21298): Reserve object class org.crosswalk.engine.XWalkCordovaResourceClient to fr.duniter.cesium.MainActivity
D/XWalkLib(21298): Reserve method setResourceClient to fr.duniter.cesium.MainActivity
D/XWalkLib(21298): Reserve object class org.crosswalk.engine.XWalkCordovaUiClient to fr.duniter.cesium.MainActivity
D/XWalkLib(21298): Reserve method setUIClient to fr.duniter.cesium.MainActivity
D/XWalkLib(21298): Reserve method setXWalkViewInternalVisibility to fr.duniter.cesium.MainActivity
D/XWalkLib(21298): Reserve method setSurfaceViewVisibility to fr.duniter.cesium.MainActivity
D/dalvikvm(21298): Trying to load lib /data/app-lib/fr.duniter.cesium-2/libsodiumjni.so 0x418b4130
D/dalvikvm(21298): Added shared lib /data/app-lib/fr.duniter.cesium-2/libsodiumjni.so 0x418b4130
D/dalvikvm(21298): No JNI_OnLoad found in /data/app-lib/fr.duniter.cesium-2/libsodiumjni.so 0x418b4130, skipping init
I/WindowManager( 2241): Switching to real app window: Window{42123888 u0 fr.duniter.cesium/fr.duniter.cesium.MainActivity}
D/dalvikvm(21298): Trying to load lib /data/app-lib/fr.duniter.cesium-2/libxwalkcore.so 0x418b4130
I/ActivityManager( 2241): Displayed fr.duniter.cesium/.MainActivity: +649ms (total +1s30ms)
D/dalvikvm(21298): Added shared lib /data/app-lib/fr.duniter.cesium-2/libxwalkcore.so 0x418b4130
D/dalvikvm(21298): Trying to load lib /data/app-lib/fr.duniter.cesium-2/libxwalkdummy.so 0x418b4130
D/dalvikvm(21298): Added shared lib /data/app-lib/fr.duniter.cesium-2/libxwalkdummy.so 0x418b4130
D/dalvikvm(21298): No JNI_OnLoad found in /data/app-lib/fr.duniter.cesium-2/libxwalkdummy.so 0x418b4130, skipping init
D/XWalkLib(21298): Post init xwalk core in fr.duniter.cesium.MainActivity
W/chromium(21298): [WARNING:xwalk_external_extension.cc(58)] Error loading extension '/data/app-lib/fr.duniter.cesium-2/libsodiumjni.so': couldn't get XW_Initialize function.
W/chromium(21298): [WARNING:xwalk_extension_server.cc(412)] Failed to initialize extension: /data/app-lib/fr.duniter.cesium-2/libsodiumjni.so
W/chromium(21298): [WARNING:xwalk_external_extension.cc(58)] Error loading extension '/data/app-lib/fr.duniter.cesium-2/libxwalkdummy.so': couldn't get XW_Initialize function.
W/chromium(21298): [WARNING:xwalk_extension_server.cc(412)] Failed to initialize extension: /data/app-lib/fr.duniter.cesium-2/libxwalkdummy.so
W/chromium(21298): [WARNING:xwalk_external_extension.cc(58)] Error loading extension '/data/app-lib/fr.duniter.cesium-2/libxwalkcore.so': couldn't get XW_Initialize function.
W/chromium(21298): [WARNING:xwalk_extension_server.cc(412)] Failed to initialize extension: /data/app-lib/fr.duniter.cesium-2/libxwalkcore.so
I/chromium(21298): [INFO:CONSOLE(26)] "Adding String.prototype.format() -> was missing on this platform", source: file:///android_asset/www/dist_js/cesium-34de8a4d7e.js (26)
I/chromium(21298): [INFO:CONSOLE(5)] "[settings] Locale [en-GB]", source: file:///android_asset/www/dist_js/cesium-34de8a4d7e.js (5)
I/chromium(21298): [INFO:CONSOLE(5)] "[settings] Loading from local storage...", source: file:///android_asset/www/dist_js/cesium-34de8a4d7e.js (5)
I/chromium(21298): [INFO:CONSOLE(5)] "[settings] Loaded from local storage in 2ms", source: file:///android_asset/www/dist_js/cesium-34de8a4d7e.js (5)
I/chromium(21298): [INFO:CONSOLE(6)] "[BMA] Starting [gtest.duniter.org:10900]...", source: file:///android_asset/www/dist_js/cesium-34de8a4d7e.js (6)
I/chromium(21298): [INFO:CONSOLE(26)] "[app] Loading cached translations for locale [en-GB]", source: file:///android_asset/www/dist_js/cesium-34de8a4d7e.js (26)
I/chromium(21298): [INFO:CONSOLE(6)] "[http] TODO: implement check version [0.90.9] compatible with [0.90.0]", source: file:///android_asset/www/dist_js/cesium-34de8a4d7e.js (6)
I/chromium(21298): [INFO:CONSOLE(6)] "[BMA] Started in 1431ms", source: file:///android_asset/www/dist_js/cesium-34de8a4d7e.js (6)
I/chromium(21298): [INFO:CONSOLE(6)] "[device] Ionic platform ready, with [barcodescanner=true] [camera=true]", source: file:///android_asset/www/dist_js/cesium-34de8a4d7e.js (6)
I/chromium(21298): [INFO:CONSOLE(6)] "[device] Enabling InAppBrowser", source: file:///android_asset/www/dist_js/cesium-34de8a4d7e.js (6)
I/chromium(21298): [INFO:CONSOLE(5)] "[crypto] Loading Cordova MiniSodium implementation...", source: file:///android_asset/www/dist_js/cesium-34de8a4d7e.js (5)
I/chromium(21298): [INFO:CONSOLE(26)] "Disable UI effects - plateform's grade is not [a] but [b]", source: file:///android_asset/www/dist_js/cesium-34de8a4d7e.js (26)
I/chromium(21298): [INFO:CONSOLE(6)] "[UI] [effects] Disable", source: file:///android_asset/www/dist_js/cesium-34de8a4d7e.js (6)
I/chromium(21298): [INFO:CONSOLE(24)] "[ES] [http] Starting on [data.gtest.duniter.fr:80]...", source: file:///android_asset/www/dist_js/cesium-34de8a4d7e.js (24)
I/chromium(21298): [INFO:CONSOLE(5)] "[crypto] Loaded 'MiniSodium' implementation in 116ms", source: file:///android_asset/www/dist_js/cesium-34de8a4d7e.js (5)
W/ActivityManager( 2241):   Force finishing activity fr.duniter.cesium/.MainActivity
I/chromium(21298): [INFO:CONSOLE(24)] "[ES] [http] Started in 355ms", source: file:///android_asset/www/dist_js/cesium-34de8a4d7e.js (24)
I/chromium(21298): [INFO:CONSOLE(25)] "[ES] [user] Enable", source: file:///android_asset/www/dist_js/cesium-34de8a4d7e.js (25)
I/chromium(21298): [INFO:CONSOLE(25)] "[ES] [notification] Enable", source: file:///android_asset/www/dist_js/cesium-34de8a4d7e.js (25)
I/chromium(21298): [INFO:CONSOLE(25)] "[ES] [message] Enable", source: file:///android_asset/www/dist_js/cesium-34de8a4d7e.js (25)
I/chromium(21298): [INFO:CONSOLE(25)] "[ES] [group] Enable", source: file:///android_asset/www/dist_js/cesium-34de8a4d7e.js (25)
I/chromium(21298): [INFO:CONSOLE(24)] "[ES] [settings] Enable", source: file:///android_asset/www/dist_js/cesium-34de8a4d7e.js (24)
I/WindowState( 2241): WIN DEATH: Window{42123888 u0 fr.duniter.cesium/fr.duniter.cesium.MainActivity}
W/WindowManager( 2241): Force-removing child win Window{42a29008 u0 SurfaceView} from container Window{42123888 u0 fr.duniter.cesium/fr.duniter.cesium.MainActivity}
I/ActivityManager( 2241): Process fr.duniter.cesium (pid 21298) has died.

**Comment by Candidesk8** [comment]
I've got the same probleme on my FP1U, Androïd 4.2.2 : 
since version 9.31, It's possible to install the app, but not to run it!

last try today with versions from 10.0 to 11.0

**Comment by Candidesk8** [comment]
@gpsqueeek how do you copy your logs? I've tried aLogcat and CatLog from F-droid repo, but what they give is very different from what you got....

**Comment by gpsqueeek** [comment]
@Candidesk8 I use aLogCat ROOT (needs root access), maybe it has more details ? Or maybe you have a different issue too.

**Comment by Candidesk8** [comment]
here are [my logs](https://hastebin.com/jenefebexo.md)
