### ISSUE TITLE
Mes opérations > faire un virement : champ "A" bloqué

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#369]
Cliquer sur le champ pour sélectionner un bénéficiaire crée une erreur dans la console JS, et je n'accède pas à la recherche du bénéficiaire : 

![image](https://cloud.githubusercontent.com/assets/969136/23545912/94625fbe-fffd-11e6-9c0c-a93519eaac0e.png)

**Comment by blavenie** [comment]
fixed in v0.11.0
