### ISSUE TITLE
Pas assez de change

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#370]
J'ai voulu envoyer 10 DU aujourd'hui (1500G, en gros). Mais ma transaction n'est pas passée, Cesium m'a indiqué que je n'avais pas assez de change.

J'ai tenté la même opération dans Sakia : ça a d'abord pris beaucoup de temps, j'ai cru à un bug, mais finalement la transaction est passée sous cette forme : 

![image](https://cloud.githubusercontent.com/assets/969136/23577681/d8017624-00c5-11e7-8a66-e94e0e7a8d30.png)

Ma transaction de 1500 (150.10¹) est passée en 3 transactions chaînées.

Ce serait top que Cesium puisse faire de même, le problème de change serait totalement réglé !

**Comment by c-geek** [comment]
![image](https://cloud.githubusercontent.com/assets/969136/23577908/60751150-00cb-11e7-99dd-c720222d4dfb.png)

Bien vu :smile:

**Comment by c-geek** [comment]
A noter qu'en fait Cesium a réalisé un change sans que je m'en aperçoive. J'ai donc pu réaliser l'opération uniquement via Cesium, qui a d'ailleurs volé la vedette à Sakia puisque le change Cesium s'est produit *avant* les transactions de change de Sakia.

Bref, j'ai pu réitérer la transaction de 1500G via Cesium, et cette fois ça passe.

Le but de ce ticket est que l'opération se fasse en une fois, et sans refus de Cesium pour des raisons de change.

**Comment by Insoleet** [comment]
Normalement j'ai lamentablement copié l'algo de change de Cesium - c'est bizarre qu'il affiche un message d'erreur dans Cesium.

Personnellement, je n'ai pas trop compris ton explication sur le comportement de Cesium vis à vis de Sakia.

**Comment by c-geek** [comment]
@Insoleet j'ai réalisé l'opération d'abord via Cesium, qui m'a affiché un bug. J'ai cru que rien ne s'était passé. J'ai ensuite essayé la même chose sur Sakia, qui a fonctionné tout de suite (cf les 5 lignes en copie d'écran ci-dessus) : j'ai alors cru que l'opération serait réalisée par Sakia.

Sauf que non, Cesium avait bien commencé une opération de change et l'avait envoyée au réseau "volant la vedette à" (passant avant) Sakia. Bref, aucune des opérations réalisées via Sakia n'a été inscrite en blockchain, du coup.

**Comment by blavenie** [comment]
je penses que ce problèmé était lié au bug #524, que je viens de résoudre : ouf !
