### ISSUE TITLE
Cesium exposing private key when not needed

### ISSUE THREAD

**Issue by galuel** [duniter/cesium#372]
In Cesium and Sakia there are requirements to "connexion" not needed to consult any account. Anyone can consult the blockchain and obtain information on any pubkey without needing the corresponding private key.

So consultation should be 100% disconnected from updates (transactions / certifications / renewing membership) in the user environment. The updates are the only operations that need private key to generate duniter documents (and then should be also available to do offline), and Sakia / Cesium should not save the private key anywhere, it should be asked only when needed, and then deleted from memory after generation.

The possibility to store locally the pivate key should be only an option, protected for instance with a 8 digits pin code, and an orange alert or something like that.

**Comment by blavenie** [comment]
duplicate https://github.com/duniter/cesium/issues/399
