### ISSUE TITLE
Transaction with amount < 0.01 G1

### ISSUE THREAD

**Issue by Candidesk8** [duniter/cesium#373]
tried to send monney, had this : 
![](https://framapic.org/2lbSOSFHvKI8/vSvOob0lkDpP)

logs : https://hastebin.com/apiwadubut.pas

with debug.html, it worked once, but not the second time

logs when it doesn't worked : https://hastebin.com/ulecazimad.pas

**Comment by Candidesk8** [comment]
peut être un problème d'unité ...

**Comment by blavenie** [comment]
oui, tu ne peux pas virer 0.001, puisque l'unité de base s'arrete à 0.01
