### ISSUE TITLE
suggestions ergonomiques

### ISSUE THREAD

**Issue by fiatou** [duniter/cesium#374]
Sur la page principale de Cesium, Je propose de modifier l'ordre des rubriques apparaissant dans l'encadré sur la gauche. En effet, je crois qu'il est primordial pour tous les utilisateurs d'utiliser cette monnaie afin d'effectuer des transactions monétaire. Le reste, vue sur les caractéristiques de la Monnaie et du Réseau Blockchain, sera certainement moins usité et pourrait rebuter certains utilisateurs néophytes (je dis ça en vue de réactions de beaucoup de personnes non-initiées qui ont trouvés ce porte-feuille très, pour ne pas dire trop, chargé en informations nouvelles).
L'ordre serait le suivant : sont mis en exergue l'Accueil de manière très visible (peut-être marqué par un code couleur ou un effet visuel quelconque) Mes opérations, Virement, Mon compte puis toujours affiché mais avec moins d'importance (taille de police plus petite ou bien jeu de couleurs ou d'effet visuel quelconque) Monnaie, Réseau, Annuaire.
Je crois qu'il est très important pour un utilisateur néophyte de pouvoir se raccrocher très vite à du connu et donc de lui permettre de prêter plus d'importance aux opérations monétaires et à son compte perso (les seuls options "permises" sur un compte bancaire classique) sans pour autant l'empêcher d'aller voir plus loin s'il le souhaite.

J'espère être assez clair...

![capture d ecran 2017-03-09 a 09 19 18](https://cloud.githubusercontent.com/assets/23424058/23741881/e114b512-04aa-11e7-8d00-55e42d007d3c.png)

**Comment by fiatou** [comment]
Ne faudrait-il pas préciser aux nouveau arrivants qu'il sont bien sur un gestionnaire de porte-monnaie libre ? Je constate que cette précision manque sur la page d'accueil Cesium 
![capture d ecran 2017-03-19 a 23 49 15](https://cloud.githubusercontent.com/assets/23424058/24085567/e42468f4-0cfe-11e7-8cd1-1a6de4f58706.png)
Je propose de changer cette phrase : " Suivez vos comptes Duniter en temps réel. " par : " Suivez vos comptes Monnaie Libre en temps réel. ". Il serait alors envisageable de mettre en bas de page ou bien sur un des côtés un lien vers Duniter sous la forme : " Cesium fonctionne grâce au projet Duniter (lien), participez à son développement ".

**Comment by blavenie** [comment]
>  Suivez vos comptes Monnaie Libre en temps réel.

est-ce que tout les comptes en monnaies libres utilisent Duniter ?
Si non, alors peut on dire cela ?

Je penses qu'il faut garder la mention Duniter, ou bien alors cité la monnaie : Gtest, G1, etc.

**Comment by fiatou** [comment]
> est-ce que tout les comptes en monnaies libres utilisent Duniter ?
Si non, alors peut on dire cela ?

Cette phrase me laisse dubitatif... Je croyais que Duniter était le système logiciel générateur de monnaie libre. Serait-il possible de m'éclairer ?
Je soutiens qu'il manque une info essentielle sur cette page d'accueil, le fait que le visiteur soit bien sur un gestionnaire de comptes en Monnaie Libre.

**Comment by fiatou** [comment]
J'ai vu que le profil des comptes non membres sont affichés avec une bannière grise, mais je viens de me créer un compte simple portefeuille (donc non membre) dont l'affichage du profil est toujours de couleur bleue. Est-ce normal ? Ne serais-ce pas plus cohérent si la bannière était elle aussi grise pour bien différencier un compte membre d'un non membre ?
![capture d ecran 2017-04-05 a 08 03 32](https://cloud.githubusercontent.com/assets/23424058/24692052/5a7205c2-19d7-11e7-8e50-a2cdaaa00425.png)

**Comment by fiatou** [comment]
Ou alors pourraient-ils avoir encore une autre couleur (vert ?) qui différencie bien les comptes simple portefeuille des comptes membres (non-encore-membre car en attente des 5 certif' => gris, et membres => bleu)

**Comment by fiatou** [comment]
J'ai aidé un ami à se créer un compte et nous nous sommes rendu compte qu'il manque une information importante lors du _processus de création d'un nouveau compte_ : " Compte Membre : Si vous n'êtes pas encore inscrit en tant qu'individu (un seul compte possible par individu). **Ce compte vous permet de créer votre Dividende Universel journalier.** 
![capture d ecran 2017-04-08 a 23 14 46](https://cloud.githubusercontent.com/assets/23424058/24840403/ca42feb8-1d6c-11e7-882d-1cdfe3dde646.png)

**Comment by blavenie** [comment]
Corrigé, pour 
 - le libellé de la page d'accueil (qui précisera "G1" et non "monnaie libre Duniter")
 - le libellé "compte membre" :
![image](https://user-images.githubusercontent.com/5269556/31830653-2e74fc3c-b5c1-11e7-8793-f00e2d5d2828.png)

Pour l'ordre du menu, je ne change pas pour le moment. C'est important i lme semble de mettre la monnaie en premier lieu.
