### ISSUE TITLE
Problème d'arithmétique dans Cesium 0.11.1

### ISSUE THREAD

**Issue by gerard94** [duniter/cesium#378]
Je lis sur https://g1.duniter.fr/#/app/currency/lg :
![capture du 2017-03-09 19-22-56](https://cloud.githubusercontent.com/assets/23338182/23773678/a305ef18-0520-11e7-8044-061c0195a5b3.png)
N = 59
M / N = 1 DU
M = 118 DU
118 / 59 ==  2 != 1

**Comment by blavenie** [comment]
le calcul doit etre fait avec M(t-1).
Soit 59 / 59 = 1

**Comment by gerard94** [comment]
Peut-être pourrais-tu remplacer alors t par t-1 dans le texte là où il faut :-)
