### ISSUE TITLE
certification

### ISSUE THREAD

**Issue by Artichit** [duniter/cesium#38]
Il serait utile d'avoir la possibilité de renseigner des champs plus complets dans nos profils de membres, comme sur les réseaux sociaux et aussi d'avoir un chat ou possibilité d'envoyer des messages aux autres membres. Cela pourrait aussi servir à la certification, pour être sûr que l'on certifie des gens que l'on connaît.

**Comment by blavenie** [comment]
Duniter (qui est un protocole, en fait) ne gère que les informations minimales que l'on saisie sous Cesium

Mais oui, tu as raison Ariane, c'est prévu dans une version améliorée, qui stockera des informations dans un serveur complémentaire, autre que Duniter.

Une  maquette est déjà quasiment fonctionnelle. Elle sera prête d'ici quelques mois.

**Comment by blavenie** [comment]
Je ferme cette demande, elle devra etre fait en dehors de cesium, ou dans une version dérivée
