### ISSUE TITLE
Ğ1 affichage paramètres monnaie

### ISSUE THREAD

**Issue by galuel** [duniter/cesium#380]
Cesium 0.11.1 Ğ1 affiche c = 4,88% / jour au lieu de c = 4,88% / équinoxe

La formule par ailleurs devrait changer pour DU<sub>jour</sub>(équinoxe+1) = DU<sub>jour</sub>(équinoxe) + c² (M/N)(équinoxe) / 182,625 jours

"L'équinoxe de printemps initial étant situé apour Duniter au 21 Mars 2017 12h00 et les équinoxes suivants étant séparés de 15778800 secondes : https://forum.duniter.org/t/preparation-de-g1/1798/33"

Ou formulation similaire.

**Comment by blavenie** [comment]
Pour rester générique vis à vis de Duniter, et ne pas mettre la chaine 'équinox' en dur, je proposes : 

<span class="item-note dark" ng-if="!loading &amp;&amp; formData.dt != formData.dtReeval">DU<sub>jour</sub>(t + 6 mois) = DU<sub>jour</sub>(t)+ c<sup>2</sup> * M<sup>t</sup>/N<sup>t</sup>)/182.625 jours</span>

**Comment by blavenie** [comment]
De même, pour `c` : 

<span>4,88 %&nbsp;/&nbsp;6 mois</span>

**Comment by blavenie** [comment]
ah non ma formule marche pas...

**Comment by blavenie** [comment]
Si, ca peut marcher, en ajoutant `t=équinox` en dessous de la formule, non ?

**Comment by blavenie** [comment]
ou alors : 
<span class="item-note dark" ng-if="!loading &amp;&amp; formData.dt != formData.dtReeval">DU<sub>jour</sub>(t<sub>reval</sub> + 6 mois) = DU<sub>jour</sub>(t<sub>reval</sub>)+ c<sup>2</sup> * (M/N)(t<sub>reval</sub>) / 182.625 jours</span>

**Comment by galuel** [comment]
Oui tu as trouvé une bonne formulation, t<sub>reval</sub> est une bonne option en effet ! Il faut en effet éviter "t", parce que la formule ne fonctionne pas pour tout "t" !

Par contre mets 182,625 jours à la place de "6 mois" de manière à utiliser toujours la même unité.

**Comment by blavenie** [comment]
tu veux dire pour c ? Soit  `4,88 % / 182,625 jours` ?

**Comment by galuel** [comment]
Je veux dire pour tout :) mais bon fais comme tu le sens, c'est pareil in-fine, du moment que c'est précis.

**Comment by blavenie** [comment]
ah je vois, pour le début de la formule :
<span class="item-note dark" ng-if="!loading &amp;&amp; formData.dt != formData.dtReeval">DU<sub>jour</sub>(t<sub>reval</sub> + 182.625 jours) = DU<sub>jour</sub>(t<sub>reval</sub>)+ c<sup>2</sup> * (M/N)(t<sub>reval</sub>) / 182.625 jours</span>

**Comment by galuel** [comment]
Voilà oui, c'est parfait comme ça, rien à dire.

**Comment by blavenie** [comment]
Bon, j'ai essayer de gagner un peu de place. Voici le résultat :
![image](https://cloud.githubusercontent.com/assets/5269556/23856291/75e17ddc-07f9-11e7-9760-5aa0947da079.png)

**Comment by galuel** [comment]
C'est parfait, t'es un As !

**Comment by c-geek** [comment]
Détail de détail .. si l'icône du cercle pouvait être en arrière plan plutôt qu'en avant plan, l'effet serait plus esthétique.

Mais sur le fond, ça me paraît très clair :-)

**Comment by blavenie** [comment]
héhé, je vois que @cgeek est aussi très visuel ;)  
Oui, j'avais ca en tête, mais j'ai fait vite. L'icone étant transparente faudra que je ruse.
