### ISSUE TITLE
Compte portefeuille : plantages & inactivité

### ISSUE THREAD

**Issue by Darunya** [duniter/cesium#386]
Bonjour à tous, voici le fonctionnement étrange puis le bug relevés : 

- Sous Césium pour G1, quand on se log pour la première fois sur un compte, un pop-up nous informe que "ce compte est inactif". Pas de souci avec ça. Lorsque l'on se déconnecte et que l'on revient dessus, même message. Étrange, car finalement même s'il n'est pas membre ce compte n'est pas inactif (peut-être n'afficher ce message que si ce compte n'a pas été "connecté" depuis 1 mois par exemple ?). Mais pourquoi pas !
- Du coup j'ai essayé de suivre le "créer un compte" en choisissant "portefeuille". Et là, plantage : Pop-up pour nous dire que le compte est inactif + pop-up pour nous demander si on est bien sûr de créer ce compte (pourtant non membre)... Et là, chargement infini. Impossible d'accéder au-dit compte. Peut-être est-ce en suivant ces pas qu'un compte portefeuille n'émet plus de pop-up "compte inactif", mais du coup je n'ai jamais pu vérifier (3 essais).
Voilà ! :)

**Comment by blavenie** [comment]
> Lorsque l'on se déconnecte et que l'on revient dessus, même message. Étrange, car finalement même s'il n'est pas membre ce compte n'est pas inactif (peut-être n'afficher ce message que si ce compte n'a pas été "connecté" depuis 1 mois par exemple ?)

on a aucun moyen de savoir si c'est la première connexion, puisqu'à ce stade il n'y a eu aucune écriture dans la blockchain. C'est pourquoi le message s'ouvre à chaque fois.

>  Et là, chargement infini. Impossible d'accéder au-dit compte. 

C'est bien un bug. Je vais le corriger de suite. Merci !
