### ISSUE TITLE
Affichage des noms des comptes-portefeuille lors des transactions

### ISSUE THREAD

**Issue by Darunya** [duniter/cesium#387]
Salutations, voici une remarque purement ergonomique :

Lors d'un virement vers un compte-portefeuille (donc non-membre, donc qui ne possède pas de pseudo), on peut rechercher ce compte-portefeuille par la clé réduite, ou par le nom que la personne a mis sur le compte.
Exemple : J'ai modifié mon compte portefeuille pour lui coller mon nom dessus. Puis, depuis mon compte membre, j'ai tapé mon propre nom dans la recherche des destinataires pour pouvoir trouver mon compte-portefeuille sans pour autant avoir retenu sa clé réduite.

Voici ce qu'il se passe : une fois que l'on clique sur le compte-portefeuille depuis la fenêtre de virement, il indique dans la case du destinataire la clé complète, et rien d'autre !
Problèmes ergonomiques : Aucun moyen de vérifier la personne à qui on destine le virement + la clé complète du destinataire est visible.
Proposition de résolution : Ne pas afficher la clé complète une fois que l'on a cliqué sur le destinataire. Afficher le nom que la personne a attribué à son compte-portefeuille, ou s'il n'a pas attribué de nom la clé réduite.

Voilà ! Et... Je ne sais pas si c'est le bon endroit pour faire remonter les remarques d'ergonomie, parce que finalement ce n'est pas vraiment une (eng) issue (/eng) ...

**Comment by galuel** [comment]
Seuls les comptes membres qui font partie de la WoT ont un ID. Tous les autres comptes sont anonymes. Le fait de leur attribuer un nom est une opération purement personnelle, stockable en local ou ailleurs, mais n'a pas de lien avec Duniter.

Si tu vérifies comment fonctionne ta banque en monnaie dette, tu verras que lorsque tu fais un virement c'est vers un RIB et tu ne saisis aucun nom uniquement des chiffres. Par ailleurs tu peux attribuer un libellé une fois un compte de virement entré dans tes comptes destinataires, mais c'est personnel, pour t'en rappeler, les autres utilsateurs de la monaie dette mettront leurs propres libellés, ça n'est pas une donnée bancaire pour tous, seul le RIB fait foi.

**Comment by Darunya** [comment]
Je suis totalement d'accord sur le fonctionnement actuel, bien que si tu regarde à côté de l'IBAN, que ce soit sur internet, un RIB, ton relevé de compte... en monnaie dette, il y a toujours le nom de la personne.

....mais là n'est pas mon sujet, il me semblait que vous disiez que Césium+ n'était pas sûr à 100% car lorsque l'on envoie des messages il utilisait les clés complètes. Du coup quid pour un virement où la clé complète est utilisée également (évidemment), mais où elle est même affichée à l'écran ! C'est son affichqge qui me titille !

...d'où la proposition a minima de remplacer dans la fenêtre du virement, la clé complète par la clé réduite (provient de Duniter, ce n'est pas du local, ça ?). Bien qu'ergonomiquement, peu importe le fonctionnement des monnaies dette, lors du virement afficher le "nom" du destinataire s'il en a rentré un aurait été plus pratique, plus rassurant, et plus humain... Mais si ce nom n'est qu'en local yes, ce n'est juste pas possible (mais alors bizzard que j'ai retrouvé mon compte-portefeuille en mettant le nom que je lui ai attribué...)

Enfin au final, peu importe l'affichage de la clé complète ou pas, le fait de ne pas au moins afficher le nom du compte auquel on fait le virement je trouve ça dommage :)

Attention hein, ce thread n'est pas vital du tout au fonctionnement, j'en ai totalement conscience, donc je ne vais pas "batailler" ou quoi hein ^_^  Je relève juste un truc qui, à mon sens (donc ça le sera pour d'autres aussi) aurait pu être amelioré ;)

**Comment by galuel** [comment]
Si tu parles de ton IBAN personnel oui ton nom est dessus, mais quand un contact t'envoie son IBAN, c'est juste le chiffre dont il s'agit et qui est demandé par ta banque pour ton virement, le nom étant sans aucune sorte d'intérêt, et on y mettre n'importe quoi que ça ne changerait rien.

Cesium+ est un client qui fait des opérations non-duniter sur des bases de données centralisées. Il n'est pas sûr pas parce qu'il utilise la clé privée Duniter à des fins qui n'ont rien à voir avec Duniter pour des opérations centralisées, et qui ne nécessitent absolument pas ni Duniter ni la clé Duniter pour ce faire via d'autres moyens, comme [ce mail que j'ai envoyé à Canercanda](https://forum.duniter.org/t/demande-de-certification-g1-canercandan/2060/5) pour commencer à vérifier la clé proposée.

**Comment by blavenie** [comment]
see https://github.com/duniter/cesium/issues/381
