### ISSUE TITLE
Licence de la monnaie et engagement de responsabilité

### ISSUE THREAD

**Issue by galuel** [duniter/cesium#388]
**Licence :**  (pour tout nouveau membre, avant de lancer sa demande d'adhésion, déjà inscrit dans les clients et dans Duniter sous forme technique) : 
Ğ1 se produit via un Dividende Universel (DU) pour tout membre humain, qui est de la forme : 
Les [paramètres de Ğ1](https://forum.duniter.org/t/preparation-de-g1/1798/33) sont : ...
Avec : 
* c = 4,88% / équinoxe
* La formule de calcul du DU est : DU<sub>jour</sub> (équinoxe suivant) = DU<sub>jour</sub> (équinoxe) + c² (M/N)(équinoxe) / (182,625 jours)

Lorsque un membre de Ğ1 certifie un nouveau compte (non inscrit à ce jour dans les logiciels) : 

**Vous êtes vous assuré :** 

1°) De bien connaître (pas seulement de la connaître "de visu") la personne qui déclare gérer cette pubkey (nouveau compte) et d'avoir personnellement vérifié avec elle qu'il s'agit bien de cette pubkey que vous vous apprêtez à certifier
2°) De la rencontrer physiquement pour vous assurer que c'est bien cette personne que vous connaissez qui gère cette pubkey
3°) Ou bien avez-vous vérifé à distance ce lien personne / clé en contactant la personne par **plusieurs moyens de communication différents**, comme forum + mail + vidéo conférence + téléphone (reconnaître la voix). Car si on peut pirater 1 compte mail ou 1 compte forum, il sera bien plus difficile d'imaginer pirater 4 moyens de communication distincts, et imiter l'apparence (vidéo) ainsi que la voix de la personne en plus.

Le 2°) restant toutefois préférable au 3°)... tandis que le 1°) est toujours indispensable dans tous les cas.

**Rappel :** Certifier n'est pas uniquement s'assurer que vous avez rencontré la personne, c'est assurer la communauté Ğ1 que vous la connaissez suffisamment bien et que vous saurez repérer un double compte effectué par une personne certifiée par vous-mêmes en faisant des recoupements qui permettront de révéler le problème le cas échéant.

--
Pour valider votre certification : 
--
Vous confirmez engager votre responsabilité envers la communauté Duniter Ğ1 et acceptez de certifier le compte Duniter Ğ1 suivant : 

- ID : xxx
- pubkey : yyyy

Pour confirmer votre certification veuillez confirmer votre signature : 

* phrase secrète : 
* password : 
* Bouton "publier"

**Comment by Arcurus** [comment]
how does this look practically: ¨ it is to assure the community Ğ1 that you know it well enough and that you will be able to locate a double account carried out by a person certified by yourself by doing Overlaps that will reveal the problem if necessary.¨

**Comment by galuel** [comment]
practically I know pretty well the persons I certify. So in case of a problem I can analyse informations outside the numerical world and make some conclusions.

**Comment by Arcurus** [comment]
thx for the clarification, so in case of a problem you have to figure it out, but you yourself must not look all the time if there is a double account.

**Comment by galuel** [comment]
Check also https://forum.duniter.fr/t/virginie-caura-alias-petiteberger/532/5 (translate with a robot should be enough to understand).

**Comment by blavenie** [comment]
fix in v0.12.4
