### ISSUE TITLE
Message erreur lors de l'affichage du fichier brut d'un bloc validé dans la blockchain

### ISSUE THREAD

**Issue by fiatou** [duniter/cesium#389]
Lorsque je clique sur le lien permettant d'accéder à la visualisation du fichier brut d'un bloc validé dans la blockchain, 
![capture du 2017-03-12 13-43-17](https://cloud.githubusercontent.com/assets/23424058/23831892/3012eac2-072a-11e7-9d75-80d521610616.png)
je suis redirigé vers une page blanche avec un message d'erreur 404 Not found. 
![capture du 2017-03-12 13-43-01](https://cloud.githubusercontent.com/assets/23424058/23831897/4d78b844-072a-11e7-8665-506a7be4e82b.png)

**Comment by blavenie** [comment]
Still error on v0.11.4 : example : url = `https://g1.duniter.org:443true/blockchain/block/1437`
