### ISSUE TITLE
Changement UD <-> TN : mon compte s'affiche à 0

### ISSUE THREAD

**Issue by fbuland** [duniter/cesium#39]
Quand j'effectue un changement d'affichage de la monnaie relatif vers absolu ou vice-versa, parfois le résultat sur mon compte s'affiche à 0.
![fbuland_compte_pb_ud_0](https://cloud.githubusercontent.com/assets/19709395/15804644/7d2390c4-2b10-11e6-90d8-13e19368b968.JPG)

Dans certains cas, je peux toujours payer car le bon montant s'affiche dans la fenêtre pour payer. Mais parfois je ne peux pas payer, car il s'affiche aussi 0 monnaie dans la fenêtre pour payer.
![fbuland_compte_paiement_des_ud](https://cloud.githubusercontent.com/assets/19709395/15804647/919262e2-2b10-11e6-9156-b53acdd1d885.JPG)

Merci
Franck

**Comment by blavenie** [comment]
@fbuland Merci pour cette remontée !

Peux-tu essayer de reproduire sur la dernière version, et décrire exactement tes étapes (quelles boutons, etc.) ?
merci !

**Comment by blavenie** [comment]
non reproduit depuis la v0.1.20
