### ISSUE TITLE
Problèmes avec les lien de partage

### ISSUE THREAD

**Issue by Thatoo** [duniter/cesium#390]
Ce matin, j'ai voulu partager le lien de ma page de compte. Le lien s'est avéré incomplet.
Cesium me donne
https://duniter.fr/#/app/wot/BbdyLPyABYzx8Lef3oXzkoiAQ5kn3uU96ZED7Nt17gZx/Nathana%C3%ABl%20Leprette

or cela devrait être 
https://duniter.fr/g1/#/app/wot/BbdyLPyABYzx8Lef3oXzkoiAQ5kn3uU96ZED7Nt17gZx/Nathana%C3%ABl%20Leprette

Il manque un petit /g1 après https://duniter.fr et avant /#/app/wot/BbdyLPyABYzx8Lef3oXzkoiAQ5kn3uU96ZED7Nt17gZx/Nathana%C3%ABl%20Leprette

Autre remarque, tous les liens de partage des profils sont du type https://duniter.fr/g1/#/app/wot (sans le g1 donc) /clef-publique/pseudo
sauf le lien de partage de son propre compte qu'on obtient dans https://duniter.fr/g1/#/app/wallet .
Là, il est du type 
https://duniter.fr/g1/#/app/wot (sans le g1 donc) /clef-publique/prénom-nom
Au lieu de pseudo, il est donné avec prénom-nom (quid de ceux qui n'utilisent pas Cesium+ ?).

**Comment by blavenie** [comment]
oui, les liens de partage ont été pensé pour une installation du type https://g1.duniter.fr  (sans chemin supplémentaire).

Effectivement, je vais devoir revoir tout ca... merci de ta remarque.
