### ISSUE TITLE
Différence entre "créer un compte" et "connecter un compte"

### ISSUE THREAD

**Issue by galuel** [duniter/cesium#397]
Voir la même issue dans Sakia : https://github.com/duniter/sakia/issues/623#issuecomment-286577133

Consulter un compte ne nécessite qu'une pubkey pour voir tout ce qui concerne ce compte, rien d'autre, surtout pas la clé privée !

Créer un compte est une opération spéciale où l'utilisateur doit être guidé, il doit sauvegarder précieusement ses phrase secrète / password, qui lui permettent de générer clé privée et nouvelle pubkey utilisable pour lui en mise à jour (et toujours consultable par n'importe qui).

**Comment by blavenie** [comment]
La Cas d'Utilisation "Le Cas d'utilisation "Utiliser Cesium pour la consultation uniquement" (et pas forcément sur mes comptes) n'est pas dans mes objectifs poru Cesium.  
Mais rien n'empêche d'autres personnes de le faire.
