### ISSUE TITLE
question sur boite de dialogue connexion 

### ISSUE THREAD

**Issue by yann1108** [duniter/cesium#398]
Certaines personnes sont confuses.
J'ai une personne émotionnelle, qui semble avoir créé 3 comptes en pensant "se connecter";
Est-ce possible de "créer" des comptes en faisant une erreur en se connectant ?
je dois voir en Install Party avec les "Michu" cette issue d'ergonomie...

**Comment by yann1108** [comment]
je vais poster cela sur le forum ;-)

**Comment by galuel** [comment]
Voir https://github.com/duniter/cesium/issues/397#issue-214222468 Cesium et Sakia restent très confus sur la notion "créer n'est pas se connecter".

**Comment by blavenie** [comment]
> Est-ce possible de "créer" des comptes en faisant une erreur en se connectant ?

En utilisant le bouton "Se connecter", il n'est pas possible de créer un compte, à moins de : 

 - une fois connecté, accepter le message de confirmation indiquant que ce compte ne correspond à rien, 
 - Dans "Mon compte", cliquer sur le menu "Options" puis "Devenir membre"
 - Puis saisir un pseudo et confirmer

A ce stade, il faut vraiment pas être douté ;)
Et rien n'y personne n'y peut rien (à mon avis, et sans mauvaise fois), sauf une formation à l'informatique (et à la lecture !).

je ferme le ticket, sauf si Yann tu as une proposition explicite ?

**Comment by yann1108** [comment]
Alors le plus simple pour les "michu" et crois-moi,
je fais du "support" depuis des années,
"n'ouvres pas une porte que tu veux garder fermée !"
ou "ne prêtes pas la batte de base-ball, pour te faire taper dessus"

Pourquoi ne pas refuser la connexion, à quelqu'un qui ne rentre pas un login "legit" ?
et si c'est une erreur de manipulation car il y en a beaucoup qui ne sont pas "doué";
alors il comprendra devant la porte fermée qu'il faut qu'il clique sur "créer un compte" ...
Et je te promet ce n'est qu'un début ...
