### ISSUE TITLE
Création d'un portefeuille anonyme

### ISSUE THREAD

**Issue by wwann** [duniter/cesium#40]
La création d'un portefeuille anonyme fonctionne mal : 
- être déconnecté
- Sur l'accueil cliquer sur "Nouveau Compte" puis choisir "Portefeuille anonyme"
- Saisir tous les champs pour créer le compte (ici, "les_rapetous", mdp "176-167!")

![image](https://cloud.githubusercontent.com/assets/17970991/15804677/898ac2aa-2b11-11e6-8f2d-b378026e2f5a.png)

- Valider
- **Un temps de chargement infini est affiché. On est bloqué.**

![image](https://cloud.githubusercontent.com/assets/17970991/15804684/a0c43d2a-2b11-11e6-880e-c48e7aae4173.png)

- Rafraichir pour débloquer.
- Sur l'accueil, cliquer sur "Se connecter"
- Saisir les infos avec lesquel on s'est inscrit et afficher la clef.
- **Le compte existe mais la clef est différente de celle affichée à l'inscription**

![image](https://cloud.githubusercontent.com/assets/17970991/15804688/dad042ca-2b11-11e6-9081-3c838bce135f.png)

- La connexion fonctionne.

![image](https://cloud.githubusercontent.com/assets/17970991/15804694/09366306-2b12-11e6-8e8b-0a63d8f714fc.png)

- Demander à devenir membre (en tant que "les_freres_rapetous").
- **Dès la demande envoyée, le compte s'affiche comme un compte membre**.

![image](https://cloud.githubusercontent.com/assets/17970991/15804716/a65c6fc2-2b12-11e6-9e34-b263db44224d.png)

Le compte n'apparait plus que comme un compte membre, par exemple après une recherche dans l'annuaire : 

![image](https://cloud.githubusercontent.com/assets/17970991/15804785/f17d696e-2b14-11e6-80c0-cf6e27e334e6.png)

**Comment by blavenie** [comment]
* Connexion anonyme qui fonctionne mal : corrigé.
* Clef public différente : il s'agit d'une erreur dans la saisie des formulaires (par exemple une majuscule au lieu d'une minuscule, un espace en trop, etc.)
* Visualisation différente si on passe par l'annuaire : corrigé
