### ISSUE TITLE
Build Cesium for Ubuntu (phone and more ?)

### ISSUE THREAD

**Issue by blavenie** [duniter/cesium#400]
# Install Ubuntu SDK : 

doc: https://developer.ubuntu.com/en/phone/platform/sdk/installing-the-sdk/

(or also : https://cordova.apache.org/docs/en/latest/guide/platforms/ubuntu/index.html)

```bash
sudo add-apt-repository ppa:ubuntu-sdk-team/ppa
sudo apt update
sudo apt install ubuntu-sdk
```

Add "click" packaging tool:
```bash
sudo apt-add-repository ppa:ubuntu-sdk-team/ppa
sudo apt update
sudo apt-get install click cmake libicu-dev pkg-config devscripts qtbase5-dev qtchooser qtdeclarative5-dev qtfeedback5-dev qtlocation5-dev qtmultimedia5-dev qtpim5-dev libqt5sensors5-dev qtsystems5-dev 

```
> ou alternativement (à tester) : 
> `sudo click chroot -a armhf -f ubuntu-sdk-15.04 install cmake libicu-dev:armhf pkg-config qtbase5-dev:armhf qtchooser qtdeclarative5-dev:armhf qtfeedback5-dev:armhf qtlocation5-dev:armhf qtmultimedia5-dev:armhf qtpim5-dev:armhf libqt5sensors5-dev:armhf qtsystems5-dev:armhf`

# Add Ubuntu platform to Ionic project

```bash
cd cesium
ionic platform add ubuntu
```

# Build Cesium

```bash
cd cesium
ionic build ubuntu
```

**Comment by jytou** [comment]
Installed the .deb successfully from the software center with no error.

But when I click on the installed icon, nothing happens.
When launching manually /opt/cesium/cordova-ubuntu I get the following error which explains why nothing happens in graphical mode: ./cordova-ubuntu: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./cordova-ubuntu)

I have an Ubuntu x64 14.04 LTS. Maybe the fact that I already have cordova-ubuntu-2.8 installed on the system could cause some problems? I don't even know what it is (although I have a little idea of what it could be).

Opening the index file from a navigator works fine, though.
