### ISSUE TITLE
SSL mode: Copy difficulties from SSL nodes to non SSL nodes (for same pubbeys)

### ISSUE THREAD

**Issue by jytou** [duniter/cesium#401]
In the "network" display, nodes for the same member don't show the same difficulties in SSL mode and non-SSL mode.
![screenshot from 2017-03-15 14 56 31](https://cloud.githubusercontent.com/assets/6391882/23952715/8e1c853c-0992-11e7-92ee-f8c5254c5f93.png)

**Comment by blavenie** [comment]
A priori ce n'est pas un bug. L'affichage est dégradé (cf message en haut de l'écran), pour les noeuds qui n'ont pas de numéro de block (le noeuds en bas de ta capture) : du coup, pour ces noeuds, on ne peut pas récupérer la difficulté depuis le noeud lui même. Est donc affiché celuis donné par le noeud par défaut (celui configuré dans tes paramètres). il peut donc y avoir une incohérence...

Une idée de contournement serait de récupérer la difficulté des noeuds accessibles, et de les appliqués aux noeuds non accessibles...

**Comment by jytou** [comment]
Ce qui m'a surtout étonné, c'était que le même nœud de cgeek soit vu avec 2 difficultés différentes, mais après avoir un peu navigué dans le code de cesium, je comprends que le même nœud vu à la fois en http et https est en réalité vu comme 2 nœuds différents. Et du coup on retombe sur le même genre de problème d'affichage dû au décalage entre différents nœuds qui n'ont pas encore reçu le dernier bloc au moment où on les interroge.
