### ISSUE TITLE
SSL node not recognized as SSL on a different port than 443

### ISSUE THREAD

**Issue by jytou** [duniter/cesium#403]
When configuring a node with SSL, Cesium doesn't recognize it as SSL if another port than 443 is used. There must be some hard-coded 443 somewhere to recognize SSL nodes and this needs to be changed as multiple nodes on the same IP would have to use different ports.

I have tested with 80/443 and the node is recognized correctly as SSL.

But when switching to 9004/9006 the node never appears as SSL, thus missing functionalities in the display.

**Comment by Tortue95** [comment]
Yes, please also add 1 parameter to enable SSL in the file` app/config.json` | `config.js` for the default node configured.

**Comment by blavenie** [comment]
@Tortue95 @jytou next release will fix this (v0.11.9).

To allow SSL on non 443 port : 
 - use a https:// ... installation of Cesium
 - and/or add `httpsMode: true` in the `config.js` file

**Comment by jytou** [comment]
Is there a way to see the current version of a given cesium instance (the one at g1.duniter.fr for instance :) )?

**Comment by blavenie** [comment]
> Is there a way to see the current version of a given cesium instance (the one at g1.duniter.fr for instance :) )?
tu plaisantes, pas vrai ? ;)

en bas à gauche :
![image](https://cloud.githubusercontent.com/assets/5269556/24122930/0040a0ba-0dbe-11e7-892f-991249ddc28a.png)
