### ISSUE TITLE
lien vers releases dans Readme incorrect

### ISSUE THREAD

**Issue by Thatoo** [duniter/cesium#404]
Dans Installation

Dans la ligne
Download the latest release. Choose the web packaging (cesium-vX.Y.Z-we.zip); 

Le lien pointe vers https://github.com/duniter/cesium/releases/latest qui redirige systématiquement vers https://github.com/duniter/cesium/releases/tag/v0.6.2

Il faudrait faire pointer le lien vers https://github.com/duniter/cesium/releases

**Comment by blavenie** [comment]
non, ce n'est pas incorrecte, c'est juste que les autres versions ne sont des "releases" mais des "pre-releases" ;)

mais comme Cesium est déjà plus stable, je vais passer la v0.11.7 en "release"
