### ISSUE TITLE
Couleur de fond > Compte membre/non membre

### ISSUE THREAD

**Issue by fiatou** [duniter/cesium#407]
Par rapport au code couleur, l'affichage d'un compte membre et non-membre est assez similaire au premier abord bien qu'un compte non-membre soit précisé par l'appellation (non-membre) de couleur rouge juste sous le pseudo. Est-ce possible d'appuyer la différence de ces comptes en modifiant la couleur de fond des profils : ex, bleu pour les comptes membres et gris pour les comptes non-membres ?

**Comment by blavenie** [comment]
Je propose ca pour un non-membre : 

![image](https://cloud.githubusercontent.com/assets/5269556/24000770/7f40bce8-0a5c-11e7-808e-ac7716a09027.png)


Je uis pas très inspiré pour les couleurs, donc si vous avez mieux...

**Comment by blavenie** [comment]
oups, en fait c'est une sélection par la souris qui a changé les couleurs. Voici les bonnes : 

![image](https://cloud.githubusercontent.com/assets/5269556/24008981/bf8e864c-0a73-11e7-9003-a9c759435e7a.png)

**Comment by fiatou** [comment]
Ouais c'est excellent !! merci beaucoup :-)
