### ISSUE TITLE
Empêcher de certifier les identités révoquées

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#408]
Même en piscine, une identité peut être révoquée : c'est-à-dire que si cette identité vient à être inscrite en blockchain, *n'importe qui pourra la révoquer instantanément* puisque la révocation est visible de tous, en piscine.

Il serait donc bien que Cesium empêche ou de certifier ce genre d'identité, car l'intérêt est nul.

L'identité finira par périmer au bout de 2 mois.

**Comment by blavenie** [comment]
as tu une identité exemple, sur gtest par exemple ?

**Comment by c-geek** [comment]
Oui : `compte_a_revoquer`. Je viens de le créer.

Par ailleurs je note une typo lors de la révocation "révoqurer".

**Comment by blavenie** [comment]
A ton avis, tu masquerait carrément la possibilité de certifier ? (genre masquer la zone "Certifications reçues" et bouton avec l'icone certifier)

**Comment by c-geek** [comment]
Je griserais le bouton, puis ajouterais un bandeau général « cette identité a été révoquée, sa certification est donc désactivée ».

**Comment by blavenie** [comment]
Alors voila le résultat, dans la recherche annuaire :  

![image](https://cloud.githubusercontent.com/assets/5269556/24007117/f42af2b0-0a6d-11e7-81b0-9bc4eca15ee7.png)

et dans l'identité elle-même : 
![image](https://cloud.githubusercontent.com/assets/5269556/24007939/6932b4b0-0a70-11e7-88bf-ebb0531bc7ac.png)

**Comment by c-geek** [comment]
Nickel !

**Comment by blavenie** [comment]
Le résultat (en grisant le bouton certifier) : 
![image](https://cloud.githubusercontent.com/assets/5269556/24008736/c1ef5dd6-0a72-11e7-8fd3-bb838f4e067d.png)
