### ISSUE TITLE
"Sent certifications with error" (or "Certifications émises en erreur")

### ISSUE THREAD

**Issue by cuckooland** [duniter/cesium#409]
Maybe a misuse from me. I have tried many time to send certifications to "Boudali Nadia" and "Lecointe Alexis". In the moment, everything seems ok, but when I come back later (and sign in again), visiting the page: 
https://g1.duniter.fr/#/app/wallet/cert/lg

I have a "Sent certifications with error" warning on the "Sent certification" section (top-right of the page): 

![certifenerreur](https://cloud.githubusercontent.com/assets/15369049/24070625/74624326-0bc1-11e7-9ff8-3a84b3bac629.png)

Looking in Firefox console, I notice some messages about Nadia and Alexis certifications ("Invalid cert GvYqNcp3: block hash changed"):

![log](https://cloud.githubusercontent.com/assets/15369049/24070629/818dfbda-0bc1-11e7-91fe-36f5a2a21b72.png)

Eloïs has noted thanks to his specialized node that Nadia has received several certifications from me:

![willmembers](https://cloud.githubusercontent.com/assets/15369049/24070631/93384e08-0bc1-11e7-9244-7fc516c82bf4.png)

**Comment by blavenie** [comment]
Il y a sans doute eu un fork, après tes certifications. Tes documents de certifications ne sont donc plus valides.

Par exemple, ta certification à Nadia [visible ici](https://g1.duniter.org/wot/lookup/GvYqNcp3rB7vYrZ7MmY1BFFC911woju8To9Nshriryyb) :+1: 
```json
{
pubkey: "56aXsYLSQmGz75ZohRQMLcKiYaUmJK5cbyz4ZGiKsbAe",
meta: {
block_number: 1927,
block_hash: "00001A626FA12CB0FB5F7E74FAF3FEA41DDC2155688819CC87022F3A71726E89"
},
uids: [
"cuckooland"
],
isMember: true,
wasMember: true,
signature: "5r0p2bQlv/hFb7JXuZ2DskFC4HXBZUkuZ77d3GYW7w9T9FP9pSuDuAB3q71V0PQVKAyOwEl5dcYbi5wSsLN2BQ=="
},
```
montre un block 1927 avec le hash `00001A626FA12...`

Or le block 1927 a maintenant [le hash `0000156A20AE2`](https://g1.duniter.fr/#/app/block/1927/0000156A20AE2705D3DC4B0F62973258801D3BD5A0E1DDD51BC4E936713608C6)

Voila donc le soucis...

Sans doute faudra t il que Cesium publie des documents en utilisant des blocs antérieurs, afin de se prémunir des forks... ou bien publier à tous les fork du réseau, comme indiqué dans ce ticket https://github.com/duniter/cesium/issues/102

**Comment by blavenie** [comment]
@cuckooland je t'invite à vérifier si l'outil de Elois détecte bien cas cas de figure.
