### ISSUE TITLE
Vidage de compte en plusieurs transactions

### ISSUE THREAD

**Issue by jytou** [duniter/cesium#410]
Depuis Cesium, après avoir vérifié le solde de mon compte à 12,3Ğ, j'ai envoyé 5 transactions de 2Ğ, puis une de 2,3Ğ. Les 5 premières sont passées sans souci.
Pour la dernière, celle qui vidait totalement le compte, c'est un peu plus compliqué. Pour un observateur inattentif, on aurait dit que tout s'était bien passé, cesium disant que la transaction avait été envoyée avec succès. Mon œil de lynx (!) a aperçu pendant une fraction de seconde un truc rouge dans le coin de la fenêtre d'envoi avant qu'elle se referme. En allant ensuite sur « Mes Transactions », j'étais bien à 0, mais un petit F5 m'a montré que la transaction n'était en fait pas passée, cesium ne me l'affichait pas et m'indiquait que mon compte n'était pas à 0 mais avait 2,3Ğ. Je suis retourné pour la soumettre à nouveau, et ai fait une petite capture d'écran pour voir ce que c'était:
![screenshot from 2017-03-12 17 55 01](https://cloud.githubusercontent.com/assets/6391882/24076362/8df4b2f2-0c2e-11e7-8070-d171961a53cd.png)

Donc cesium a bien repéré que la transaction mettrait mon compte à 0. Le plus curieux, c'est que cette transaction est passée cette fois dans cesium, mais avec un montant légèrement différent: 2,29Ğ (alors que j'avais bien indiqué 2,3, c'est une certitude). Cesium me l'a affichée pendant un moment, et me mettait bien que mon compte était à 0,01Ğ (cohérent, même si ce n'était pas ce que j'avais demandé). J'ai essayé d'envoyer les 0,01 restants, cesium m'a dit que la transaction avait été envoyée, mais un petit F5 sur mon compte m'a indiqué que la transaction en question n'existait pas et que j'étais toujours avec un solde de 0,01Ğ.

Depuis, le temps a passé, et ce qui a été inscrit dans la blockchain est différent de l'histoire que cesium m'avait racontée. La transaction à 2,3Ğ a bien été diffusée et est bien passée (au bloc 1166), et celle à 2,29 est maintenant dans les transactions non exécutées de cesium, qui m'affiche bien un solde final de 0, et affiche aussi la transaction à 2,3Ğ comme exécutée. L'histoire n'est pas la même, mais le résultat final est cohérent, ce qui est très bien.

Je suis conscient que c'est vraiment un cas à la marge, mais je tenais à le signaler pendant que c'est frais.

**Comment by blavenie** [comment]
résolu dans Cesium v0.15.0 - link to #406
