### ISSUE TITLE
My account > Share button: Error: $rootScope is not defined

### ISSUE THREAD

**Issue by vincentux** [duniter/cesium#411]
Le bouton "partager" sur le Césium installé sur mon nœud : https://duniter-g1.vincentux.fr/cesium/
ne fonctionne pas du tout, c'est normal ?

![image](https://cloud.githubusercontent.com/assets/11737560/24092877/61eb5b4c-0d51-11e7-816f-bc0da270955f.png)

**Comment by blavenie** [comment]
@vincentux dans quel écran ? Quel navigateur ?
Peux tu ajouter test logs console JS ?

Je viens de tester sous Firefox, sur cette identité, et je n'ai pas eu de problème : https://duniter-g1.vincentux.fr/cesium/#/app/wot/6Fdtk5DLmfJXxPhPTf27oH5KA8jw84H2vXMAnm5eCey/_Wapetoooooooo_

**Comment by vincentux** [comment]
Excuse moi, j'ai fais la moitié du boulot :( 
je suis avec Firefox 52 (32bits) sous Windows 7
Dans l'écran "Mon compte" et voici les logs de la console : 

```
Error: $rootScope is not defined
WalletController/e.showSharePopover@https://duniter-g1.vincentux.fr/cesium/dist_js/cesium-648d232f62.js:1:29271
anonymous/fn@https://duniter-g1.vincentux.fr/cesium/dist_js/vendor-a84e9eaef1.js line 14 > Function:2:314
@https://duniter-g1.vincentux.fr/cesium/dist_js/vendor-a84e9eaef1.js:21:3901
$n/this.$get</h.prototype.$eval@https://duniter-g1.vincentux.fr/cesium/dist_js/vendor-a84e9eaef1.js:13:2746
$n/this.$get</h.prototype.$apply@https://duniter-g1.vincentux.fr/cesium/dist_js/vendor-a84e9eaef1.js:13:2978
@https://duniter-g1.vincentux.fr/cesium/dist_js/vendor-a84e9eaef1.js:21:3881
Ke@https://duniter-g1.vincentux.fr/cesium/dist_js/vendor-a84e9eaef1.js:11:9367
Xe/n@https://duniter-g1.vincentux.fr/cesium/dist_js/vendor-a84e9eaef1.js:11:9316
n@https://duniter-g1.vincentux.fr/cesium/dist_js/vendor-a84e9eaef1.js:5:17760
t@https://duniter-g1.vincentux.fr/cesium/dist_js/vendor-a84e9eaef1.js:5:17594
o@https://duniter-g1.vincentux.fr/cesium/dist_js/vendor-a84e9eaef1.js:5:18456
  vendor-a84e9eaef1.js:12:20010
```

**Comment by blavenie** [comment]
ok, donc c'est bien un bug ;(

alors peux tu recommencer, mais depuis l'adresse /debug.html

**Comment by vincentux** [comment]
j'ai essayé avec `/debug.html` mais je n'ai pas eu plus de message.
