### ISSUE TITLE
Impossible de créer un compte Ḡ1 (Cesium 0.11.4)

### ISSUE THREAD

**Issue by yann1108** [duniter/cesium#418]
Il semble que le nœud gérant Cesium+ bloque la procédure pour l'enregistrement du compte membre Ḡ1 (en Install Party, nous aidons les prétendants à Ḡ1)

- on suit la procédure "création de compte" mais au moment de finaliser - voilà le message : 
![screenshot-g1 duniter fr 2017-03-23 04-48-37](https://cloud.githubusercontent.com/assets/272091/24231990/1137bef0-0f88-11e7-8102-49289578b356.png)

J'ai changé de connexion, de nœud Duniter mais c'est bien le nœud de Cesium+ qui pose problème, t là, je ne peux pas changer de nœud - (y en a-t-il un autre ?)
![screenshot-g1 duniter fr 2017-03-23 05-15-35](https://cloud.githubusercontent.com/assets/272091/24232046/86444272-0f88-11e7-856b-9ed4d0699f5a.png)

bon, résultat des courses, impossible de finaliser l'inscription...

**Comment by vincentux** [comment]
As-tu essayé de déactiver Césium+ ?

**Comment by yann1108** [comment]
oui, je viens de re-essayer avec Cesium+ désactivé - et impossible de finaliser l'inscription d'un compte membre - je venais de me connecter sur mon compte membre juste avant, donc le nœud Duniter "g1.monnaielibreoccitanie.org:443" semble fonctionner correctement.
Je vais essayer sur un autre nœud (ce que j'avais déjà tenté) sinon je vais aller sur Sakia pour faire le test. Je donnerai le résultat sur Sakia...

**Comment by yann1108** [comment]
Ok sous Sakia, ça marche très bien.
Il a juste fallu que je modifie le pseudo qui était déjà utilisé, dans les 3 comptes que cette personne avait fait malencontreusement.
Ok plus de données pour les prochains tutos :-)
