### ISSUE TITLE
Noeuds mirroirs non SSL - boucle infinie (depuis une site Cesium SSL)

### ISSUE THREAD

**Issue by blaurent49** [duniter/cesium#423]
Bonjour,
Quand je clique sur certains nœuds miroir, Cesium affiche "Nœuds connus" et se contente de tourner en boucle.
J'ai le cas notamment pour : 
g1monnaielibreoccitanie.org (89.234.156.194:443)
g1.duniter.org:10901
duniter.laurent-st-math.fr:80 (le mien !)
Est-ce que ça signifie que ces nœuds ne répondent pas correctement ?

**Comment by blavenie** [comment]
Depuis quelle installation de Cesium (que adresse web du site) ?

**Comment by blaurent49** [comment]
J'utilise Cesium 11.8 dans mon navigateur Firefox : https://g1.duniter.fr/#/app/network?type=mirror.

En choisissant le nœud ci-dessous par exemple, j'obtiens le comportement indiqué plus haut : 
https://g1.duniter.fr/#/app/network/peer/89.234.156.194:443

Je n'ai pas de nœud installé sur ma machine.

**Comment by blavenie** [comment]
Ah, c'est parceque ces noeud ne sont pas en SSL (httpS:...)
Ton navigateur refuse car ils ne sont pas sécurisé.

Il faut que j'ajoute un message d'avertissement ;)

merci de la remarque
