### ISSUE TITLE
Cannot switch from HTTPS to HTTP node

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#425]
In Cesium, we can configure the node we are connected to:

![image](https://cloud.githubusercontent.com/assets/969136/24503296/c4f1d222-1551-11e7-88a6-04d4e16f241f.png)

The problem is: we cannot switch from an HTTPS node an HTTP one, for example

* from `g1.duniter.fr:443`
* to `192.168.1.18:10900`

Indeed, Cesium generates an error:

![image](https://cloud.githubusercontent.com/assets/969136/24503377/23552dfa-1552-11e7-9633-65669ed8205e.png)

And he is right! My node is not accessible through HTTPS here, but HTTP.

We should be able to switch from HTTPS to HTTP, shouldn't we?

**Comment by blavenie** [comment]
Yes, we should be able to switch, but only on an not `httpS://` URL.
Is that your case ?

**Comment by c-geek** [comment]
I try to switch from https to http. And I can't.

**Comment by blavenie** [comment]
fixed in v0.12.1
