### ISSUE TITLE
transactions impossibles à partir d'un compte non-membre

### ISSUE THREAD

**Issue by mamygeek** [duniter/cesium#428]
cesium version 0.11.8
J'ai créé un compte secondaire, donc non membre. Je n'ai pas eu de problème pour l'alimenter. 
Par contre, impossible d'effectuer des virements.

message d'erreur : wrong unlocker in transaction.

**Comment by blavenie** [comment]
@mamygeek peux tu s'il te plait : 
 - ouvrir la console Javascript de ton navigateur
 - lancer Cesium avec l'adresse /debug.html
 - puis me donner ici les logs affichés

Merci

**Comment by blavenie** [comment]
Discuté au RML9 : 
 - peut etre faut il un indicateur pour indiquer si le compte destinaire est vide ou non, lorsqu'il ne correspond pas à un membre
