### ISSUE TITLE
Exclu de GTest, je ne peux plus revenir

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#429]
Sur http://gtest.duniter.fr : 

J'ai été exclu de GTest. J'essaye d'y revenir, mais : 

1. si j'essaye de me renouveler alors j'ai le message « il faut être membre pour cela »
2. si j'essaye de devenir membre alors j'ai le message « pseudo déjà utilisé »

Remarque : si j'actualise la page et que je retente 2), ça fonctionne.

**Comment by blavenie** [comment]
Ah oui, c'est le soucis que j'ai eu, et qui m'a fait te demander d'ajouter "wasMember" quelque par dans BMA.
Depuis, je n'ai pas retravaillé la dessus...

merci du rappel
