### ISSUE TITLE
Le DU n'apparait pas dans la liste des transactions

### ISSUE THREAD

**Issue by fbuland** [duniter/cesium#43]
Ne devrait-on pas faire apparaître la création de DU (quotidien sur cette monnaie de test, mensuel pour une monnaie réelle) dans la liste des transactions ? Cela permet de mieux suivre d'où vient la monnaie sur notre compte.
Ou alors donner le choix d'afficher ou non les transactions de création de DU.
Dans Sakia, on voit la création des DU dans la liste des transactions.

**Comment by blavenie** [comment]
J'ai ajouté les DU dans l'historique des transactions, avec une option pour le désactiver, dans les paramètres
