### ISSUE TITLE
Cesium+ sélection de texte impossible dans les messages

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#430]
Dans un message privé où il y aurait une URL, on ne peux pas copier celle-ci car le texte ne peut pas être sélectionné.

**Comment by blavenie** [comment]
as tu réussi à la faire dans gannonce ?
Tu as modifié quoi ?

**Comment by blavenie** [comment]
linked to issue #316

**Comment by c-geek** [comment]
Ça : https://github.com/c-geek/gannonce-ui/blob/master/src/app/app.scss#L1-L3

**Comment by blavenie** [comment]
closed in v0.10.5
