### ISSUE TITLE
Identifier clairement la monnaie

### ISSUE THREAD

**Issue by JeanFe** [duniter/cesium#431]
Il serait bon d'afficher clairement le nom de la monnaie dans l'entête de cesium web, en effet quand deux instances sont ouvertes (Ğ1 et Ğtest) il est facile par confusion de faire un virement ou certifier une identité sur la mauvaise monnaie.

**Comment by blavenie** [comment]
Fait en v0.12.8 : le symbole d ela monnaie apparait en haut du menu
