### ISSUE TITLE
On identity creation: urge to save the revocation document on the disk

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#432]
> Ah oui, tu veux dire que Gildas avait accès à son 1er compte que vous avez donc certifié, puis a perdu ses accès et alors il a créé un nouveau compte que vous avez de nouveau certifié, sans qu'il ai pu révoquer le 1er ?

> Si c'est le cas, on voit bien à quel point il devient crucial qu'au moment de la création d'un compte, le logiciel harcèle l'utilisateur pour stocker sa révocation sur son PC (on pourrait même imaginer que tant que cette action n'est pas faite, le logiciel refuse de fonctionner).

In other words: the revocation document is an absolute security: it should have been saved on account creation. Cesium could even refuse to work as long as the revocation document has not been saved.

**Comment by Gildas31** [comment]
Si on télécharge ce document de révocation lors de la création du compte, mais qu'on perd son accès à ce compte, le document de révocation ne peut pas être utilisé, non?
Il me semble que dans la procédure de certification il faut bien vérifier que la personne est la personne, mais également, qu'elle se déconnecte et se reconnecte, pour être certain qu'elle puisse le renouveller tout le temps. Une fois cela fait, on peut envoyer la certif.

**Comment by c-geek** [comment]
@Gildas31 justement si, la révocation peut être envoyée sans besoin de s'identifier. D'ailleurs même un ami peut envoyer ce document si on lui transmet.

C'est ce mécanisme qui permet aux membres de la toile d'avoir confiance justement : le compte, même en piscine, peut montrer qu'il est révocable à tout instant et par n'importe qui.

**Comment by Gildas31** [comment]
Ah ouai d'accord !
Effectivement, cette étape de sauvegarde du document de révocation devrait être incontournable.

**Comment by fiatou** [comment]
> In other words: the revocation document is an absolute security: it should have been saved on account creation. Cesium could even refuse to work as long as the revocation document has not been saved.

Je plussoie à cet issue !

**Comment by yann1108** [comment]
Exactement la validation de la création de compte devrait être lié au téléchargement du fichier de révocation.
on pourrait le faire automatiquement à la création du compte dans les différentes étapes - après avoir validé Identifiant + mot de passe + pseudo on rajoute le téléchargement du fichier ; (pas facultatif) - on doit télécharger si on veut finir le processus ...
Cela simplifierait grandement les erreurs que nous voyons maintenant - puisque tous auraient (au moins, s'ils ne perdent pas le fichier) ce fameux fichier de révocation
