### ISSUE TITLE
Default Duniter node has invalid SSL certificate ?

### ISSUE THREAD

**Issue by antoniovictor** [duniter/cesium#433]
Mententon
Sur mon PC, à partir de Github, j’ai téléchargé la version cesium-v0.11.8-android.apk.
Je l’ai ensuite importée sur mon téléphone(Android 5.1) puis installée. Une fois mes identifiants pour G1 rentrés, j’ai un écran figé (bleu foncé 1/3 en haut et blanc 2/3 en bas). Par trois fois je suis allé dans :Parametres /adresse du nœud Duniter et j’ai remplacé « g1.duniter.org:443 » par « g1.duniter.fr:443 » et là tout fonctionne impeccable. Je viens de retenter à l’instant,(4 ou 5 heures plus tard), je n’arrive plus à me connecter même en rentrant l’adresse d’autres nœuds actifs que je vois sur mon cesium web.

**Comment by antoniovictor** [comment]
Bahh j'en ai encore fait une, mes dernières tentatives de connexion à Cesium ont échoué car mon téléphone n'était plus connecté au wifi :(
Par contre je dois toujours remplacer, en manuel, l'adresse par defaut « g1.duniter.org:443 » par « g1.duniter.fr:443 » ce qui ne doit pas faciliter la vie au premier venu sur Cesium.

**Comment by blavenie** [comment]
Je me dmeande si le certificat SSL de duniter.org n'a pas un soucis, car j'ai eu plusieurs fois cette remarque, et depuis Java je peux reproduire.

cc @c-geek : une idée ?

**Comment by c-geek** [comment]
Le certificat a en effet été renouvelé il y a une semaine, le 26 ou 27 avril.

Est-ce toujours d'actualité ? Si je vais sur https://g1.duniter.org, je n'ai pas de soucis particulier. Le certificat est valide.
