### ISSUE TITLE
Certifications oubliées par Cesium

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#436]
Voici le cas de `bdcht`. Cette personne a reçu 11 certifications de 5 personnes différentes : 

* mimi (1 certif - clé 5UGxjjevfX4vJwH3Q4e76nFEppfXFx6wyKzVBjRK8om5)
* CatherineLeroy (6 certifs - clé 8U7ShA8saua3gzU254zozLhA4MsPidBh8SoTQbV7HEtc)
* fluidlog (2 certifs - clé 6wuMCx2xbPn4iMJM2mGanGr7myUhYg319jJ4gkMNHkD)
* BenoitLavenir (1 certif - clé 38MEAZN68Pz1DTvT3tqgxx4yQP6snJCQhPqEFxbDk4aE)
* simonelion (1 certif - clé 78jhpprYkMNF6i5kQPXfkAVBpd2aqcpieNsXTSW4c21f)

Le Cesium est celui de https://g1.duniter.fr et le nœud https://g1.duniter.org.

Or voici ce qu'affiche [sa fiche](https://g1.duniter.fr/debug.html#/app/wot/cert/lg/BJZLQx4SQ7HMCCTNzohXWbzV5QzNTpYufWSHnM1VuESN/bdcht) : 

![image](https://cloud.githubusercontent.com/assets/969136/24862019/3205d6e0-1dfb-11e7-9e00-0b00d214d6e1.png)

Les remarques que je peux faire : 

* On voit bien apparaître le chiffre « 5 » comme la somme des 3 certifs valides et les 2 en erreur. Mais on ne voit pas explicitement qu'il y a 5 certifications valides, mais seulement 3.
* Toutefois il y a 11 certifications ... et je ne retrouve pas cette info dans Cesium. Je remarque que cela laisse perplexe les utilisateurs qui ne comprennent pas ce qui se passe, voir [ce post du forum](https://forum.duniter.org/t/help-2-certifications-in-error/2351) pour s'en rendre compte.
* J'ai vérifié, et *il existe bien 5 certifications valides parmi les 11* (avec toutefois 1 seule qui n'est pas inscriptible immédiatement parmi ces 5, celle de simonelion, qui le sera toutefois jeudi 13 avril 21h).

Bref, visiblement Cesium occulte les certifications valides parce qu'il en rencontre d'autres en erreur (ce qui est possible). Mais il pourrait tout de même afficher celles qui sont correctes dans la liste des « correctes » justement.

Je pense que ce n'est pas grand-chose, mais l'investigation fût longue et le désarroi des utilisateurs, grand ! :grin:

**Comment by blavenie** [comment]
Les certifications ([voir ici](https://g1.duniter.org/wot/requirements/BJZLQx4SQ7HMCCTNzohXWbzV5QzNTpYufWSHnM1VuESN)) suivantes sont invalides : 
 - 7179-000009CBF8C31E24C1407F10028B69868036E29977FD9BF73619F4EFE19412FF (mauvais hash)
- 7209-0000085F1384A8D27563E5E683BA4961580BFE5A5B85931F7F2524697FA862CC (mauvais hash)

Catherine Leroy (pub key 8U7ShA8saua3gzU254zozLhA4MsPidBh8SoTQbV7HEtc) l'a certifié 9 fois (dont 1 invalide)

Cesium ne prenait en compte qu'une seule certification par pubkey (la première dans l'ordre du /wot/lookup). Or la 1ere était ensuite invalidée à cause du mauvais hash...

**Comment by blavenie** [comment]
A non, j'ai fait un truc mieux que ca en fait : je garde les certification les plus récentes, mais il ya avait un bug dans mon test sur le numéro de bloc... arf, vive le JS ! ;)

**Comment by c-geek** [comment]
Une release de prévue bientôt ?
