### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by galuel** [duniter/cesium#44]
Le c% ne précise pas l'unité de temps. L'arrêt de l'adhésion devrait être dans une page spéciale "gestion du compte", et ne pouvoir être lancée qu'avec la double entrée de son mot de passe et un message d'alerte (et d'information : ce ne sera effectif qu'à ... telle date = cessation des certifications dans 1 an, 10 mois, 5 mois...).

Didende Universel et pas "Dividend"

Le bouton pour l'unité de paiment est curieux, je trouvais mieux que ce soit le bouton gauche<->droite qui serve, et pas pour "commentaire"... Ce n'est pas naturel il me semble d'avoir un commentaire optionnel par bouton, soit on saisit un commentaire, soit on en saisit pas...

**Comment by blavenie** [comment]
> c%

Corrigé. J'ai ajouté aussi la période pour le DU

> L'arrêt de l'adhésion devrait être dans une page spéciale "gestion du compte", et ne pouvoir être lancée qu'avec la double entrée de son mot de passe et un message d'alerte (et d'information : ce ne sera effectif qu'à ... telle date = cessation des certifications dans 1 an, 10 mois, 5 mois...).

Doublon avec l'issue #28 

> Le bouton pour l'unité de paiment est curieux, je trouvais mieux que ce soit le bouton gauche<->droite qui serve

Le bouton droite/gauche ne fonctionne que pour deux unités, mais mon idée est d'en ajouter d'autre. Il faut donc un bouton plus ouvert.

> Ce n'est pas naturel il me semble d'avoir un commentaire optionnel par bouton, soit on saisit un commentaire

En fait mon idée était qu'àprès avoir indiqué le montant, on puisse faire directement "OK" dans le clavier virtuel (sur téléphone en tous cas) et que ca envoi directement la transaction, plutot que ca passe au champs commentaire.
Mais effectivement, dans un navigateur c'est autre chose...
Peut etre que ce mode dévrait etre réservé au téléphone seulement ?
Pour faire cela, il faut que le montant
