### ISSUE TITLE
Have an URL to make a preset payment

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#440]
For example, if I want to make a "Pay Remuniter" button somewhere, I would make a link with something like:

https://g1.duniter.fr/#/app/transfer/TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS

But this URL does not work.

Also, it would be cool to have `amount` and `comment` options as well.

**Comment by blavenie** [comment]
fixed. Add option `udAmount` also, to force a relative amount

**Comment by c-geek** [comment]
Should it be fixed in production also, or should I wait v0.11.9?

**Comment by blavenie** [comment]
fixed in 0.12.1
deployed on gtest : http://gtest.duniter.fr/#/app/transfer/5ocqzyDMMWf1V8bsoNhWb1iNwax1e9M7VTUN6navs8of?amount=100&comment=test

deployment on G1 will coming soon ;)

**Comment by c-geek** [comment]
Works like a charm!
