### ISSUE TITLE
Impossible d'accéder à mon profil

### ISSUE THREAD

**Issue by viico** [duniter/cesium#441]
Salut,

J'ai un problème de cross origin request lorsque j'essaye d'éditer mon profil ("Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://g1.data.duniter.fr/user/profile/CJ58FqDypoprz77CrBkKHcc8k6C94sz74p3ZPQhDPAyb. Raison : l’en-tête CORS « Access-Control-Allow-Origin » est manquant.").

J'ai le problème avec Firefox et Chrome. Lorsque je me connecte mon profil est vide il est indiqué que je n'ai aucun profil Cesium+.

Sachant que j'ai déjà réussi à y accéder et à le modifier mais depuis 2 jours plus moyen. Un truc à paramétrer chez moi?

**Comment by blavenie** [comment]
La situation est rétablie, semble t il. Le noeud qui stockait les profiles était HS.
Tu confirmes @viico ?

**Comment by viico** [comment]
Je confirme c'est tout bon pour moi.
Merci
