### ISSUE TITLE
Bug Cesium > Connexion à un mauvais compte ?

### ISSUE THREAD

**Issue by Barnaky** [duniter/cesium#442]
Bonjour,
Ol m'est très difficile de me connecter sur Cesium, il me connect sur un compte qui n'est pas le mien par exemple.

**Comment by blavenie** [comment]
Bonjour @Barnaky,
cela arrive lorsque vos identifiants sont incorrectement saisis (c'est eux qui génére la clef de votre compte).
Pensez à bien afficher et vérifier la clef publique de votre compte, avant de lancer la connection.

Si le problème persiste, veuillez tester depuis un autre navigateur.

Redites moi si cela fonctionne à nouveau.

**Comment by blavenie** [comment]
Dans Cesium v0.12.8 (et +) une fenetre d'avertissement indique maintenant à l'utilisateur que le compte est inactif, et qu'il s'agit sans doute d'une erreur de saisie.
