### ISSUE TITLE
incohérence d'affichage entre cesium et la piscine sur le "willMembers" d'Elois.

### ISSUE THREAD

**Issue by fiatou** [duniter/cesium#446]
Depuis mon compte, Cesium affiche qu'Ekiben n'a que 2 certifications de Ajnael et Fiatoux alors que la piscine sur le willMembers affiche qu'Ekiben est certifiée par 3 membres, Ajnael, Fiatoux et Roco.
Ekiben me dit que depuis son propre compte Cesium elle voit bien les 3 certifications apparaîtres venant de Ajnael, Fiatoux et Roco...

Depuis mon compte sur Cesium
![pbekibenlast](https://cloud.githubusercontent.com/assets/23424058/25684441/c6cad74e-3061-11e7-9cf1-a5969878722d.png)

Depuis la piscine sur willMembers 
![pb affichage ekiben3](https://cloud.githubusercontent.com/assets/23424058/25684364/5243ec8a-3061-11e7-9c7b-b47fceb54f23.png)

**Comment by blavenie** [comment]
Il se peut que les noeuds utilisés (celui d'Elois pour WillMembers et celui de duniter.org pour Cesium) n'était pas synchronisé.
Cela arrive parfois dans les blockchain. Mais cela ne dure généralement pas, le temps que les document numériques se propage entre les noeuds.

la situation semble maintenant cohérente, voici ce qu'affiche mon Cesium : 
![image](https://cloud.githubusercontent.com/assets/5269556/25711564/8984a124-30ef-11e7-90a3-55e582f024ca.png)
