### ISSUE TITLE
[bug] Une transaction supprimée par un fork reste affichée comme effectuée

### ISSUE THREAD

**Issue by librelois** [duniter/cesium#448]
J'ai envoyer 20 Ğ1 à Moul le 4 mai,  cesium m'a dit que la tx est passée, mais je ne la voit pas en blockchain ni dans sakia. Donc je pense qu'elle à été supprimée à cause d'un fork réseau.

Si tel est le cas, cela signifie que césium garde en mémoire des transactions qui n'existent plus, c'est un bug.

![bug-cesium](https://cloud.githubusercontent.com/assets/22670546/25766270/b929c9ba-31f1-11e7-8f68-3a4e8f8ebee2.png)

**Comment by blavenie** [comment]
duplicate https://github.com/duniter/cesium/issues/113
