### ISSUE TITLE
L'appli Cesium bientôt téléchargeable sur F-Droid ?

### ISSUE THREAD

**Issue by fiatou** [duniter/cesium#449]
Hello,
L'autre jour un ami m'a présenté [F-droid](https://fr.wikipedia.org/wiki/F-Droid) qui est un magasin d'appli libre pour Android. Nous n'y avons pas trouvé Cesium. Nous avons trouvé cela dommage. 
Pensez-vous bientôt proposer cesium sur F-droid ?

Librement,

**Comment by M5oul** [comment]
Duplicate of https://github.com/duniter/cesium/issues/358.

**Comment by M5oul** [comment]
Pour répondre : oui, c’est en cours. Mais, il doit manquer du travail.
