### ISSUE TITLE
refus de caractères accentués Cesium

### ISSUE THREAD

**Issue by JeanFe** [duniter/cesium#45]
j'ai du supprimer les accents et une apostrophe pour supprimer le message "caractères non accentués non autorisés" mais peut être est-ce un mauvais paramètrage de langue de mon navigateur?
OS ubuntu 17.04
navigateur: firefox
![cesium 2016-06-09](https://cloud.githubusercontent.com/assets/19825127/15914126/a6e6fe02-2dde-11e6-98c9-0e0bbf8e8051.jpg)

**Comment by M5oul** [comment]
Il me semble que c’est pensé ainsi pour qu’on ne puisse pas mettre de caractères spéciaux. Mais uniquement des caractères ASCII afin de réduire la taille du message.
Je ferme le ticket.
N’hésitez pas à le réouvrir si je dis des conneries.
