### ISSUE TITLE
restauration des identifiants

### ISSUE THREAD

**Issue by Carolef** [duniter/cesium#455]
bug repéré par Sybille  : impossible de restaurer les identifiants après avoir fait la sauvegarde
https://www.dropbox.com/s/ed466d5vc4jikb1/Capture%20d'%C3%A9cran%202017-05-17%2020.40.04.png?dl=0

**Comment by blavenie** [comment]
@Carolef es tu sur que le fichier de sauvegarde des identifiants était bon ?
Peux tu me coller son contenu quelque part ?
