### ISSUE TITLE
A chaque nouvelle connexion sur mon compte, toutes mes notifications marquées comme lues s'affichent.

### ISSUE THREAD

**Issue by fiatou** [duniter/cesium#456]
Tout est dit dans le titre,
![notifications](https://cloud.githubusercontent.com/assets/23424058/26206630/a6dc9514-3be5-11e7-8d80-d30434e74df3.png)

**Comment by blavenie** [comment]
Oui, j'ai un soucis sur le Noeud ES qui gère les noitifications
