### ISSUE TITLE
Inscriptions "Compte membre" impossible sous Firefox

### ISSUE THREAD

**Issue by blavenie** [duniter/cesium#464]
L'affichage empeche toute saisie du pseudonyme (qui apparait masqué à droite) : 
![image](https://cloud.githubusercontent.com/assets/5269556/26666334/aa5a1d5a-469f-11e7-81b5-4243ae6eaaf6.png)

@ArnaudCerisier peux tu regarder, stp ?

**Comment by blavenie** [comment]
Sous Chrome, cela fonctionne : 

![image](https://cloud.githubusercontent.com/assets/5269556/26666397/fa8928f2-469f-11e7-8de2-cfc00cc20045.png)

**Comment by slaivyn** [comment]
J'ai le même problème, avec Firefox ET Chromium

**Comment by blavenie** [comment]
closed in v0.12.8
