### ISSUE TITLE
Issue with ssl node on not port 443

### ISSUE THREAD

**Issue by Tortue95** [duniter/cesium#466]
Hi, i can't send transaction when i use my ssl node on [https://g1.duniter.tednet.fr:9000](https://g1.duniter.tednet.fr:9000)

on console i have this issue:
`Blocked loading mixed active content "http://g1.duniter.tednet.fr:9000/tx/process"`

because cesium try to connect with http.

in the same time, my node was not detected with SSL mode on Network view

ps: in the config.js i have enabled: "httpsMode": true

**Comment by blavenie** [comment]
@Tortue95 tu n'aurais pas un problème de certificat sur ton noeud ?

![image](https://user-images.githubusercontent.com/5269556/26968709-45d73fec-4d03-11e7-8bfc-c4bf5a23f9aa.png)

**Comment by Tortue95** [comment]
Hello, non tout est correct.
sur ton screen tu cherche a valider avec le protocole x509 l'IP et non le domaine `g1.duniter.tednet.fr`
seul le domaine est trusté par l'autorité de certification ici `Let's Encrypt Authority`
