### ISSUE TITLE
Dependency problems on Ubuntu GNOME

### ISSUE THREAD

**Issue by RavanH** [duniter/cesium#467]
Hi,

Trying to install the latest deb package (with double-click invoking the Software Center) the installation process takes a crazy long time and finallly end in a crash of Software Center.

Cesium seems to be installed but does not start.

Via command line I see:
`
$ sudo dpkg --configure -a
dpkg: vereistenproblemen verhinderen de configuratie van cesium:
 cesium is afhankelijk van ubuntu-sdk-libs; maar:
  Pakket ubuntu-sdk-libs is niet geïnstalleerd.

dpkg: fout bij verwerken van pakket cesium (--configure):
 vereistenproblemen - blijft ongeconfigureerd
Fouten gevonden tijdens verwerken van:
 cesium
`
(Sorry, in Dutch, meaning "cesium depends on  ubuntu-sdk-libs but it's not installed, cesium remains unconfigured")

Then when doing `$ sudo apt --fix-broken install` it turns out that this very long chain of dependencies (among which ubuntu-sdk-libs) needs installing: 

  hud indicator-network libaccounts-qt5-1 libboost-log1.62.0
  libboost-program-options1.62.0 libclick-0.4-0 libcolumbus1-common
  libcolumbus1v5 libconnectivity-qt1 libcontent-hub0 libdbus-cpp5
  libdbusmenu-qt5 libertine-xmir-tools libertined libgflags2v5
  libgoogle-glog0v5 libgsettings-qt1 libhud2 libjsoncpp1 liblibertine1
  liblttng-ust-ctl2 liblttng-ust0 libmediascanner-2.0-4 libnet-cpp2
  libnih-dbus1 libonline-accounts-client1 libpkcs11-helper1 libpoppler-qt5-1
  libprocess-cpp3 libqdjango-db0 libqgsttools-p1 libqofono-qt5-0
  libqt5bluetooth5 libqt5bluetooth5-bin libqt5contacts5 libqt5feedback5
  libqt5keychain1 libqt5location5 libqt5location5-plugins libqt5multimedia5
  libqt5multimedia5-plugins libqt5multimediaquick-p5 libqt5multimediawidgets5
  libqt5opengl5 libqt5organizer5 libqt5positioning5 libqt5positioning5-plugins
  libqt5quickparticles5 libqt5quicktest5 libqt5sensors5 libqt5systeminfo5
  libqt5versit5 libqt5versitorganizer5 libqt5websockets5 libqt5xmlpatterns5
  libsignon-qt5-1 libu1db-qt5-3 libubuntu-app-launch4
  libubuntu-download-manager-client1 libubuntu-download-manager-common1
  libubuntugestures5 libubuntumetrics5 libubuntutoolkit5 libudm-common1
  libudm-priv-common1 libunity-action-qt1 libunwind8 liburcu4
  liburl-dispatcher1 libusermetricsinput1 mediascanner2.0
  network-manager-openvpn openvpn python3-libertine python3-psutil
  qml-module-qt-labs-folderlistmodel qml-module-qt-labs-settings
  qml-module-qt-websockets qml-module-qtbluetooth qml-module-qtfeedback
  qml-module-qtlocation qml-module-qtmultimedia qml-module-qtorganizer
  qml-module-qtpositioning qml-module-qtqml-models2
  qml-module-qtqml-statemachine qml-module-qtquick-localstorage
  qml-module-qtquick-particles2 qml-module-qtquick-xmllistmodel
  qml-module-qtsensors qml-module-qtsysteminfo qml-module-qttest
  qml-module-qtwebsockets qml-module-ubuntu-components
  qml-module-ubuntu-components-labs qml-module-ubuntu-layouts
  qml-module-ubuntu-mediascanner0.1 qml-module-ubuntu-onlineaccounts
  qml-module-ubuntu-onlineaccounts-client qml-module-ubuntu-performancemetrics
  qml-module-ubuntu-test qmlscene qtchooser qtdeclarative5-poppler1.0
  qtdeclarative5-u1db1.0 qtdeclarative5-ubuntu-content1
  qtdeclarative5-ubuntu-download-manager0.1
  qtdeclarative5-ubuntu-mediascanner0.1 qtdeclarative5-ubuntu-push-plugin
  qtdeclarative5-ubuntu-syncmonitor0.1
  qtdeclarative5-ubuntu-telephony-phonenumber0.1
  qtdeclarative5-ubuntu-ui-toolkit-plugin qtdeclarative5-unity-action-plugin
  qtdeclarative5-usermetrics0.1 sqlite3 suru-icon-theme ubuntu-app-launch
  ubuntu-download-manager ubuntu-html5-theme ubuntu-html5-ui-toolkit
  ubuntu-mobile-icons ubuntu-sdk-libs ubuntu-ui-toolkit-theme
  usermetricsservice xmir

Note that Cesium 0.12.3 included with Duniter Desktop 1.2.6 does not invoke this dependency chain, not even ubuntu-sdk-libs

**Comment by blavenie** [comment]
See new release for desktop : https://github.com/duniter/cesium/releases

**Comment by RavanH** [comment]
version 0.12.9 installé, ça marche!
