### ISSUE TITLE
Settings node changed: keep old node data

### ISSUE THREAD

**Issue by blavenie** [duniter/cesium#468]
@Florck a du s'inscrire sur g1-test depuis un Cesium existant, mais le currenct block est resté celui de G1.

Soit doit etre du au service csCurrency qui n'a pas été redémarré

**Comment by florck** [comment]
Hum, le seul césium que j'ai utilisé est le cesium test... MAIS... J'ai essayé de le faire avant avec Sakia ce qui n'a pas été un grand succès....
