### ISSUE TITLE
Cesium desktop (Ubuntu build v0.12.7) : Could not download revocation file

### ISSUE THREAD

**Issue by JordanGuiz** [duniter/cesium#469]
Lors de la création du compte, le téléchargement du doc de révocation ne donne rien.

**Comment by blavenie** [comment]
Ceci doit être du au navigateur embarqué utilisé par la version desktop de Cesium...

**Comment by blavenie** [comment]
closed
Il faut maintenant utiliser la version cesium-desktop (disponible [ici](https://github.com/duniter/cesium/releases/tag/v0.12.7) pour la v0.12.7)
