### ISSUE TITLE
Always display clearly which node we are connected to

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#472]
For example, we could add this information near the avatar:

![image](https://cloud.githubusercontent.com/assets/969136/26826621/fab251b4-4ab9-11e7-8507-fc33505e0f41.png)

or near the version number:

![image](https://cloud.githubusercontent.com/assets/969136/26826631/04f3a0b0-4aba-11e7-9f89-5355b17e106c.png)

**Comment by blavenie** [comment]
@cgeek voici un 1er jet : 

![image](https://user-images.githubusercontent.com/5269556/26983848-6fadcd1a-4d3d-11e7-9d54-a64f53be0d9f.png)
