### ISSUE TITLE
Add a message on Cesium homepage when we can't reach the connected node

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#473]
For example if I try to reach `localhost:10901` for a node I've shut down previously, Cesium displays errors in the console but does not says explicitely that there is a connection problem with my node.

I note that in such situation, even if I logged in before in Cesium with my personal member key, Cesium behave like I'm not connected at all (which is wrong: I can see CESIUM_DATA and CESIUM_SETTINGS filled in in the localStorage):

![image](https://cloud.githubusercontent.com/assets/969136/26827588/4b6174d8-4abe-11e7-9ce2-824cf33fe048.png)

**Comment by blavenie** [comment]
> I note that in such situation, even if I logged in before in Cesium with my personal member key, Cesium behave like I'm not connected at all (which is wrong: I can see CESIUM_DATA and CESIUM_SETTINGS filled in in the localStorage):

duplicate  #477
