### ISSUE TITLE
Licence : Fichier introuvable

### ISSUE THREAD

**Issue by jeangraine** [duniter/cesium#475]
Bonjour.
En faisant, sous cesium-v0.12.7-web "créer un compte"->"créer un compte membre", 
il manque la licence ( ~/cesium/cesium-v0.12.7-web/license/license_g1-fr-FR.txt ).

merci
jeangraine

PS : Soyez indulgent si ma remontée de bug est incorrecte, c'est ma première soumission.
PS2 : Je rencontre le même problème sous v0.12.4

**Comment by jeangraine** [comment]
<img width="512" alt="capture d ecran 2017-06-07 a 06 36 33" src="https://user-images.githubusercontent.com/25570144/26871905-07e5fd84-4b75-11e7-8193-a107b0b3e055.png">

**Comment by blavenie** [comment]
closed in Cesium v0.12.9
