### ISSUE TITLE
Connection: fallback on g1.duniter.org:443

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#476]
I wanted to add a local connection to `localhost:10901` Duniter node. But few time later, I closed my node and Cesium. And then I want to open Cesium again, without success as my `localhost:10901` is down.

It would be very nice if Cesium could automatically detect that the connexion is lost with `localhost` and tests the connection with a fallback node like `g1.duniter.org:443`, and temporarily uses it.

So for example, in my case I would be asked: 

    Votre nœud `localhost:10901` est inaccessible, voulez-vous temporairement utiliser le nœud `g1.duniter.org:443` à la place ?

And then if I relaunch Cesium and my Duniter node is UP, Cesium would automatically be back again on `localhost:10901`, because `g1.duniter.org:443` was just a session connection.

Maybe you could use sessionStorage instead of localStorage for that purpose.

**Comment by c-geek** [comment]
Excellent work!

However I encounter a strange behavior on http://g1.duniter.org/cesium: I change the connection (which is g1.duniter.org:443 by default) to my local node (g1.cgeek.fr:80) and I'm getting the message:

![image](https://user-images.githubusercontent.com/969136/26922540-b52c1f94-4c3f-11e7-941b-86111cabea2f.png)

So click "OK" and I use temporarily g1.duniter.org:443, as expected if I click on this button.

But what is weird is that:

* if I go to another screen (for example "Currency") and then go back to Parameters, the node is displayed in red with a message telling me this is a temporary address:

![image](https://user-images.githubusercontent.com/969136/26922683-15774004-4c40-11e7-9462-67ef7e2cca5f.png)

This is fine, but this red color + message were not visible when I clicked "OK" the first time. I had to go to another screen to see it.

* if I press F5, the value goes back to g1.cgeek.fr:80 (which is the expected behavior: good!), my node does not seem to have any problem and is reachable. So I don't see why Cesium told me it wasn't, and why I had to use the fallback node

**Comment by c-geek** [comment]
Note: you may experience issues with my node g1.cgeek.fr:80. But you still have the above problem with any other node.

Replace g1.cgeek.fr:80 by g1.duniter.org:10901 for example.

**Comment by blavenie** [comment]
@c-geek j'ai laisse ce ticket ouvert pour avoir du recul.
Penses tu finalement qu'il faille faire autre chose que l'existant ?

**Comment by c-geek** [comment]
A priori non, tu peux fermer.
