### ISSUE TITLE
Nœud affiché comme indisponible

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#478]
Quand on clique sur le nœud d'eloïs, on tombe sur cette erreur : 

https://forum.duniter.org/t/pre-inscriptions-g1-test/2592/15

**Comment by blavenie** [comment]
Je ne comprends pas bien... le lien que tu donnes dans ce post est en https://  donc impossible d'accéder à la fiche de pair d'un noeud dont le port est 10900.

En revanche, [ce lien](http://g1-test.duniter.org/cesium/#/app/network/peer/5.135.188.170:10900) fonctionne parfaitement...
tu confirmes @cgeek ?
