### ISSUE TITLE
Mauvais logo pour l'application Google Play

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#48]
Sur mon mobile, Cesium a le logo du Sou une fois installé (je crois : logo vert et violet façon Yin/Yang), tandis que sur Google Play il y a le logo Duniter .. et puis Cesium n'est pas fait que pour le Sou ?!

**Comment by blavenie** [comment]
oui, c'est bien un bug ! ;)
J'avais vu mais j'espérais trouver un logo avant de déployer

**Comment by blavenie** [comment]
bon, remarques, en attendant ca distingue de l'application Duniter App

**Comment by blavenie** [comment]
fix on v0.1.19
