### ISSUE TITLE
On Loging, Error. Android 7.0, v0.12.6 : crypto function not compatible

### ISSUE THREAD

**Issue by jeangraine** [duniter/cesium#480]
![screenshot_20170608-203947](https://user-images.githubusercontent.com/25570144/26969174-177bc4b8-4d05-11e7-97a5-762045559e26.png)

**Comment by blavenie** [comment]
Thank's @jeangraine 
 this is a known issue.

To be able to test Cesium, you will need to disable your lock screen + code pin, in Android settings.

Will be fix in next releases
