### ISSUE TITLE
Historique évolution d'un compte jusqu'en 2012

### ISSUE THREAD

**Issue by vincentux** [duniter/cesium#483]
Rien de méchant, mais quand on demande [l'historique d'un compte](https://duniter.fr/g1/#/app/wot/5dzkzedBWdeqTFCaD7AkKPMPusfRUL1XyFNJWWGYQ9f1/stats?t=100&stepUnit=month) et que dans les options on choisi d'afficher par mois, Césium 0.12.9 remonte jusqu'en 2012.
2017 suffirait largement ;)
![cesium_graph](https://user-images.githubusercontent.com/11737560/27029774-0961111e-4f6a-11e7-9ae7-cea2ad9ffeb9.PNG)

**Comment by blavenie** [comment]
oui, j'ai éviter de mettre des valeurs en dures ;)
