### ISSUE TITLE
Suggestion Ergonomie (opening URL link in another window)

### ISSUE THREAD

**Issue by yann1108** [duniter/cesium#493]
Juste une amélioration pratique, 
que les liens URL dans l'a propos et dans l'aide (differents liens) 
s'ouvrent dans une differente fenetre 
car pour l'instant, ils s'ouvrent dans la même fenêtre et vous obligent à vous re-connecter, ce qui n'est pas pratique quand on a juste voulu avoir une information sur une commande ou un terme ;-)

**Comment by blavenie** [comment]
Oui, bien vu. Je l'avais fait pour d'autres liens (profil par exemple) pas pour ces liens ci.

Merci du test ! :)
