### ISSUE TITLE
Cesium .deb log sur un noeud local & un compte 

### ISSUE THREAD

**Issue by yann1108** [duniter/cesium#494]
Je viens de tester pour la 1ère fois Cesium build en .deb (64 bits - version 0.13.0)
et je me trouve avec ces alertes sur un noeud local & une connection à un compte:
voir copies d'écran en attachements
![screenshot at 2017-06-26 06 51 57](https://user-images.githubusercontent.com/272091/27525263-9d7186d6-5a3c-11e7-97b9-5319dcc089c6.png)
![screenshot at 2017-06-26 06 52 33](https://user-images.githubusercontent.com/272091/27525264-9d788346-5a3c-11e7-8e98-8ca72a69ef60.png)

**Comment by blavenie** [comment]
@c-geek ca te dit quelque chose ?
(toi qui as déjà testé le desktop + noeud local)

@yann1108 Est-ce que ton noeud local est bien démarré ?

**Comment by c-geek** [comment]
Oui c'est le cas où Duniter est détecté présent sur la machine, mais que le nœud ne tourne pas.

C'est [le petit script de détection](https://github.com/duniter/cesium-desktop/blob/master/src/nw/cesium/node.js) qui n'est pas très malin et ne vérifie pas que le nœud fonctionne effectivement. Du coup Cesium affiche le message : 

> Un nœud pour la monnaie g1 a été détecté sur cet ordinateur, voulez-vous que Cesium s'y connecte ? (plus sécurisé)

Puis évidemment comme le nœud est éteint, on arrive sur le message ci-dessus : « nœud injoignable » et Cesium passe sur une adresse de secours.

**Comment by c-geek** [comment]
Ceci dit, ça montre comme Cesium devient robuste : on a toujours une solution de secours qui fonctionne ;-)

**Comment by yann1108** [comment]
[@yann1108 Est-ce que ton noeud local est bien démarré ?]
Non effectivement, cela sera résolu d'ici le courant juillet ; 
j'aurais d'ailleurs 2 noeuds alors qui tourneront (une brique internet en permanence et un PC en occasionnel)

Effectivement je comprend les alertes maintenant,
cela me sera utile pour mes propres résolus "support" (Install Party et autres Apéro ;-)

[Ceci dit, ça montre comme Cesium devient robuste : on a toujours une solution de secours qui fonctionne ;-)]
Tout à fait, bon boulot !

Sujet clos et résolu ;-)
