### ISSUE TITLE
UID not unique

### ISSUE THREAD

**Issue by RavanH** [duniter/cesium#50]
Creating a new account on http://cesium.duniter.fr/ allows me to use the same UID as an existing account. Can this not cause issues? At least on the human side when searching for someone you wish to send money to?

**Comment by blavenie** [comment]
Thks for this remarks ! ;)

This is not a bug.
This is possible only if the UID has not been written in the blockchain.
@c-geek : it that correct ?

**Comment by c-geek** [comment]
Yes as long as the UID is not « taken » by someone (that is, use an already written in the blockchain UID), you can use the UID to create many identities.

Only one will be written, however.

**Comment by RavanH** [comment]
Example: user RavanH was created today at around 3 o'clock via Sakia, then connected to cgeek.fr and the identity was submitted to the network successfully. Then the user was certified an hour later. It another hour (or more) to get certified status in Sakia. After that, I tried creating another user with the same UID via Cesium. This now has the status "Membership sent. Waiting validation."

I suppose that this validation will fail at some point because of the existing UID but until it is rejected, I can search for user "RavanH" and I find both accounts ! In fact, I logged in again using the same credentials and I now see three instances in the search results on http://cesium.duniter.fr/#/app/wot and in Sakia > Search identities

Maybe best to prevent an account from appearing in the search results until the UID has been accepted? Or would that prevent others from finding and certifying a new member?

**Comment by c-geek** [comment]
Yes you are right, we could simply prune impossible UIDs (UIDs already taken) after the UID has been officially integrated in Duniter first, but Ceisum should also make such a filter: a network machine should never be trusted, it could send fake results as well (by a bug or malicious intentions).

**Comment by RavanH** [comment]
Question that may be related -- or not, or just slightly I'm still learning ;) : Is there a way for a user to be removed from Duniter a at all? In Sakia I see "Supprimer ce compte" but does that remove the user locally or from all communities too?

**Comment by Insoleet** [comment]
In Sakia, "Supprimer c ecompte" only removes the user locally. It should be possible one day to revoke an identity using Sakia. But not at the moment. It is possible to do a pull request to do so following the [tutorial](https://forum.duniter.org/t/contribuer-au-code-de-sakia/964?u=inso) on the forum thought !

**Comment by c-geek** [comment]
The revocation is possible at protocol level: it completely and definitely unvalidate the identity as a member or potential member. Clients like Cesium or Sakia just need to implement it, but the Duniter nodes are ready.

**Comment by RavanH** [comment]
OK thanks guys, I'm learning a lot :) ... I'm not a Python / Qt developer  (I do PHP mostly) so I don't think I'll be forking Sakia (let alone contributing code) any time soon. Maybe one day though.
