### ISSUE TITLE
Display QR code on high resolutions

### ISSUE THREAD

**Issue by M5oul** [duniter/cesium#504]

**Comment by blavenie** [comment]
Quel est le besoin précis @M5oul, stp ?

**Comment by M5oul** [comment]
Pour pouvoir afficher QR code sur une tablette ou un ordinateur portable afin qu’il puisse être scanné.
It only works with small screen size resolution.

**Comment by blavenie** [comment]
ah je vois, j'avais mal compris...
que penses tu de rajouter une entrée "Voir le QR code" dans le menu "Options" de la page "Mon compte" ?
Ce choix pourrait etre persisté d'une session à l'autre (via les paramètres locaux)
