### ISSUE TITLE
Révocations d'identités non-membre restes éternellement affichés "en attente"

### ISSUE THREAD

**Issue by librelois** [duniter/cesium#507]
Lorsque l'on révoque une identité non-membre, Cesium affiche éternellement la révocation comme en attente de traitement, or la révocation ne pourra être inscrite en blockchain que si l'identité deviens membre, or l'identité ne deviendra jamais membre puisqu'elle a été révoquée.

Cette ambiguïté fait croire a certains (comme [**stephane**](https://forum.duniter.org/t/adhesion-non-valide/2820/9?u=elois) sur le forum pourtant informaticien) qu'il n'est pas possible de révoquer une identité non-membre ou que cela ne fonctionne pas, alors que cela fonctionne.

Cesium devrait donc indiquer que la révocation de l'identité est effective, dés lors qu'il a confirmation du nœud duniter de référence que le document se trouve bien dans sa sandbox, ce qui n'est 
assurément pas le cas, la preuve ici : 
j'ai changé de nœud de référence pour `g1-test.elois.org`, et j'ai constater que le document de révocation est bien dans la sandbox de mon nœud, mais cesium affiche pourtant toujours la révocation comme en attente :
http://g1-test.duniter.fr/#/app/wot/5Cyanij3qmWtAP8K2d7NwAbUgL97Zrh1QECvC548nhQt/elois-test-pending-revocation

**Comment by blavenie** [comment]
> Cesium devrait donc indiquer que la révocation de l'identité est effective, dés lors qu'il a confirmation du nœud duniter de référence que le document se trouve bien dans sa sandbox

Que veux tu dire par "effective" ?
Pour moi, justement, elle n'est pas effective (elle ne le sera jamais) car les sandbox peuvent être remise à zéro...

Il faudrait plutôt trouver un autre terme (autre que "en attente" ou "effective")...

Une idée @c-geek, @inso, @galuel ?

**Comment by c-geek** [comment]
> or l'identité ne deviendra jamais membre puisqu'elle a été révoquée

Non, cela on n'en sait rien ! On sait simplement que n'importe qui pourra révoquer l'identité *si jamais* celle-ci devient membre. Mais donc elle peut le devenir.

> alors que cela fonctionne

Oui, disons que l'identité peut être pré-révoquée, ou annulée, je ne sais pas quel est le bon terme. C'est-à-dire que la révocation peut co-exister avec l'identité en piscine.

**Comment by galuel** [comment]
Que veux tu dire par "effective" ?

=> "Le document de révocation de cette identité est validé et publié sur le réseau Duniter, cette clé publique ne doit donc plus être utilisée".

**Comment by Insoleet** [comment]
Techniquement il pourrait réutiliser cette clé publique en republiant son identité... Mais pour faire simple, ce discours me parait très bien.
