### ISSUE TITLE
Renouvellement en mode "connecté par clé publique"

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#508]
Cesium n'arrive pas à effectuer l'action, car évidemment je ne possède pas la clé privée du compte auquel je suis connecté. Mais Cesium ne m'a pas demandé de me connecter. Le message d'erreur est technique, mais il aurait fallu soit : 

* me demander de m'authentifier, avec un message d'erreur si je n'arrivais pas à reproduire le trousseau possédant la même clé publique que celle utilisée en connexion
* afficher un message d'erreur "veuillez préalablement vous authentifier"

Je me doute que tu n'as pas eu le temps de tout développer, mais je fais un ticket pour tracer :smile: 

![image](https://user-images.githubusercontent.com/969136/27987019-bbe44962-6407-11e7-9013-89b7c8e09093.png)

**Comment by blavenie** [comment]
Oui merci. je n'avais pas tester cette fonction là.
