### ISSUE TITLE
Connexion par uid

### ISSUE THREAD

**Issue by Insoleet** [duniter/cesium#511]
Salut kima,

Ce soir, stanjourdan est venu nous voir parce qu'il avait créé 2 identités involontairement.

Ce qu'il s'est passé : 

1. Il a créé un nouveau compte (Clé publique 3QtWDfByBb4fe...)
2. Il a rafraichi son navigateur et a du se reconnecter (normal)
3. Il s'est reconnecté mais a eu une typo. Sa clé publique a différé : 9C7PGn4zyX
4. Cesium lui a en toute logique signalé "l'inactivité de son compte" et il a republié cette seconde identité (et sans le document de révocation !)

En en parlant sur le chat (le 10 Juin) : https://logs.duniter.org/duniter/2017-07-10/ j'ai préféré la méthode que je fais dans Sakia pour le coup : 

1. Connexion avec uid : On vérifie que le compte existe (uid + pubkey)
2. Connexion sans uid : On se connecte sans vérifier

Que penses-tu d'intégrer un comportement similaire à Cesium ? De permettre de préciser l'UID dans le menu de connexion, et donc de vérifier que l'utilisateur s'est connecté sur un ensemble d'identifiants cohérent (UID + clé secrète + password).

Je vois un inconvénient potentiel : si l'identité n'est pas uniformément répartie sur les piscines, l'utilisateur pourrait avoir l'impression qu'il y aurait eu un bug à la diffusion de son identité. Mais a priori c'est un problème qui n'arrive plus depuis les récentes versions de Duniter.

**Comment by blavenie** [comment]
Dans la 0.14.0 (déployée uniquement sur g1-test pour le moment) tu peux presque le faire, avec la méthode de connexion "par clé publique".
=> tu as le possibilité de faire une recherche dans la Wot, par uid...

**Comment by blavenie** [comment]
> inso: En fait la connexion par pubkey pourrait avoir un champs optionnel "uid"

**Comment by blavenie** [comment]
@Inso Cesium permet maintenant de se connecté par pubkey AVEC une recherche dans la WoT (bouton "loupe"). Ca te semble suffisant ou pas ?

**Comment by inso** [comment]
Hi, can you stop mentioning me? (I think you should use @Insoleet instead)

**Comment by Insoleet** [comment]
Testé et validé !
