### ISSUE TITLE
Certification impossible sur mobile

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#52]
Voici une identité tout juste créée : 

![image](https://cloud.githubusercontent.com/assets/969136/15956981/4c5b9c2c-2eec-11e6-8366-244fd65ea5bd.png)

Sur un téléphone, il est impossible de cliquer sur "Nombre de certifications" pour accéder à la liste des certifs et signer l'identité. En fait, on voit même qu'il manque le signe ">" à droite.

Attention ce bug est vraiment **très bloquant**. Sauf à être sûr de l'avoir déjà corriger, il faut chercher pourquoi le lien n'est parfois pas cliquable.

Nous avons déjà eu le bug le samedi midi à table, avec 3 utilisateurs différents.

**Comment by blavenie** [comment]
Et si tu vas dans certifications, as tu le bouton ?

**Comment by blavenie** [comment]
C'est corrigé depuis hier (v0.1.14) : Il faut cliquer dans "Nombre de certifications 0 >"
Puis le bouton apparait.

**Comment by c-geek** [comment]
Justement je ne peux pas aller dans les certifications. Sur l'impression d'écran on voit que je peux cliquer, mais sur mon mobile justement je ne peux pas, c'est l'objet de cette issue.

**Comment by c-geek** [comment]
Dans mon cas, je ne vois même pas le signe ">" et j'ai beau appuyer indéfiniment sur "Nombre de certifications 0 >", je n'accède pas à l'écran suivant.

**Comment by blavenie** [comment]
Si tu ne vois pas le ">", c'est que tu n'as pas la dernière version ;(

Tu utilise l'application intégré ou via un navigateur ?
Il faut mettre à jour l'appli, ou rafraichir la page selon le cas...  

@c-geek redis moi si c'est bon ensuite

**Comment by c-geek** [comment]
OK c'est corrigé avec la dernière MAJ. Merci !
