### ISSUE TITLE
Error while sending transaction : "inputs must equal outputs"

### ISSUE THREAD

**Issue by blavenie** [duniter/cesium#524]
From [Alain](https://g1.duniter.fr/#/app/wot/4tsFXtKofD6jK8zwLymgXWAoMBzhFx7KNANhtK86mKzA/AlainLebrun) : 
> Alain a voulu te virer 70 DU. Son compte est crédité de 1070 Ğ1. Le virement est impossible… tantôt un message en anglais (inputs must equal outputs), tantôt en français (montant maximal 68000 Ğ1 !
> On a essayé avec 680 Ğ1, même résultat.

**Comment by blavenie** [comment]
Explication du bug : si le montant de la transaction nécessite plus de 40 inputs, je splittait la TX en plusieurs : des TX de change, puis la dernière la bonne TX.
...mais la split n'était pas bon, je sautais un `input` pour n'en prendre que 39 (et non 40), mais sans recalculer le montant pour la 2ème TX (la bonne)...  d'ou des inputs dont le montant étaient < aux outputs !

**Comment by c-geek** [comment]
Waow! Une bonne chose de faite :+1:
