### ISSUE TITLE
Supprimer une demande de certif

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#526]
J'ai tenté tout à l'heure de supprimer une demande de certification dans Cesium, et voici le message d'erreur : 

![image](https://user-images.githubusercontent.com/969136/29171431-e3609f6a-7ddc-11e7-8a2f-a09fcfc8e6e0.png)

**Comment by blavenie** [comment]
@c-geek tu étais sur quelle version ?

**Comment by blavenie** [comment]
duplicate #519
