### ISSUE TITLE
Add an URL for transfer with a return callback

### ISSUE THREAD

**Issue by blavenie** [duniter/cesium#527]
cf [this post](https://forum.duniter.org/t/website-g1-payment-integration/2991/6?u=kimamila)

- add parameter to set a reference (=TX comments)
- add a `callback` parameters, called after TX sent

**Comment by c-geek** [comment]
Ideally, the callback would return the complete transaction that was signed by Cesium so the website of the merchant can send himself the transaction to the network and check its correctness.
