### ISSUE TITLE
Meilleur affichage de la clé

### ISSUE THREAD

**Issue by vincentux** [duniter/cesium#528]
je trouve que la clé public n'est pas assez mise en avant quand on se trouve sur le profil d'une personne.
Est-il possible de la mettre juste sous la photo avec le nom, ou dans les "informations générales" par exemple ?

![cesium_cle](https://user-images.githubusercontent.com/11737560/29205730-e43c10a2-7e7e-11e7-9b86-af845300e293.png)

**Comment by blavenie** [comment]
done in v0.18.2 : pubkey is not on top of the page
