### ISSUE TITLE
QR codes cumulés

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#531]
Suite à plusieurs connexions sur mon Cesium et à des comptes différents, je remarque qu'il y a autant de QR codes que de connexions réalisées dans ma session : 

![image](https://user-images.githubusercontent.com/969136/29507872-5d7fde46-8652-11e7-9c63-fe6578105783.png)

**Comment by blavenie** [comment]
Quelle version utilises tu ?
Je croyais avoir corrigé ce bug en v0.16.0

**Comment by c-geek** [comment]
v0.15.7, OK, je vais passer en 0.16.0.

Par contre, ce serait bien d'officialiser une release stable ici : https://github.com/duniter/cesium/releases

**Comment by blavenie** [comment]
> Par contre, ce serait bien d'officialiser une release stable

Tu veux dire en mettant "release" ou lieu de "pre-release" ?

**Comment by c-geek** [comment]
Oui. Merci !
