### ISSUE TITLE
L'icône d'authentification n'est pas mise à jour

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#536]
Je suis *a priori* authentifié, d'ailleurs je viens d'effectuer une transaction, et je souhaite marquer comme lus tous mes messages en attente.

Lorsque je clique sur « Tout marquer comme lu », Cesium me redemande une authentification : 

![image](https://user-images.githubusercontent.com/969136/29520278-bd9f2e0c-8680-11e7-9399-2602a5f7431d.png)

Je décide d'essayer à nouveau de réaliser une transaction, et Cesium me redemande aussi de me ré-authentifier.

Donc j'en comprends que *vraiment*, j'ai perdu ma session d'authentification, soit, mais l'icône avatar n'a plus son cadenas rouge.

**Comment by blavenie** [comment]
je ne reproduit plus. Je ferme pour le moment.
