### ISSUE TITLE
Network: update the peer duniter version

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#540]
When I upgrade a node to a new version, I do not see the change in the Network view until I restart Cesium.

**Comment by blavenie** [comment]
En fait, je penses que la version est mise à jour, mais il y a un cache sur la requete (de 5 min) : 
https://github.com/duniter/cesium/blob/abfcd34ca84ab8ed6072d48fb95db36adb88d6a6/www/js/services/bma-services.js#L813

Ca me semble préférable de le laisser, qu'en penses tu ?

**Comment by c-geek** [comment]
OK, alors je vais faire mon test tout à l'heure avec une 1.5.3 (bug réseau vis-à-vis de Sakia).

**Comment by c-geek** [comment]
Tested: all good!

**Comment by blavenie** [comment]
super
