### ISSUE TITLE
[Césium 0.17.1] Erreur BMA 

### ISSUE THREAD

**Issue by vincentux** [duniter/cesium#543]
J'ai téléchargé le fichier .zip de Cesium et je l'ai glissé le fichier "debug.html" dans Firefox 55

![selection_012](https://user-images.githubusercontent.com/11737560/29574987-6cb0212a-8763-11e7-8e2e-06257a8d71a8.png)

**Comment by blavenie** [comment]
Merci à toi.
Je ne vois pas de bug : cela dis simplement que le noeud n'est pas joignable, ou bien qu'il a refusé de te répondre car tu as fait trop de requete
