### ISSUE TITLE
API : cancel_url don't replace {comment} by the comment of cancelled tx

### ISSUE THREAD

**Issue by librelois** [duniter/cesium#548]
J'ai tester l'API cesium avec les url de retour.
Et sur l'url d'annulation cesium ne remplace pas  {comment} par sa valeur, ce qui est très génant...
un site web qui intègre l'api a besoin de connaitre la référence de la transaction annulée !

**Comment by blavenie** [comment]
ah oui, je ne l'avais fiat que pour le cas ou tout est OK.
