### ISSUE TITLE
Ajouter une bouton "S'authentifier" quand l'utilisateur est déjà connecté

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#550]
Petit retour des rencontres Rennaises : des utilisateurs déjà identifiés sur leur téléphone cherchaient à s'authentifier pour une raison X ou Y (en l'occurrence pour me montrer qu'ils connaissaient bien leurs identifiants secrets), et ne trouvaient pas le bouton "Se connecter". En effet celui-ci est remplacé par « Mon compte » sur la page d'accueil.

Serait-il possible d'ajouter un bouton « Se connecter » (avec une icône de déverrouillage) dans la partie profil, par exemple sous « Editer mon profil » ?

![image](https://user-images.githubusercontent.com/969136/29913197-bff7fb96-8e34-11e7-8240-a1da82ff387a.png)

**Comment by blavenie** [comment]
Je ne suis pas sûr de comprendre...
tu parles sur téléphone uniquement ?

Si oui, voici le focntionnement actuel (sur téléphone) : 

 - si non connecté, bouton "Se connecter" visible sur la page d'accueil
![image](https://user-images.githubusercontent.com/5269556/29918645-7275b040-8e46-11e7-98b6-13aaebfb5e46.png)

 - si déjà connecté, plusieurs façon de se déconnecter : 
  * bouton-icone en haut à gauche du menu
![image](https://user-images.githubusercontent.com/5269556/29918690-9d614b5c-8e46-11e7-8a9b-d507e3bbbe8c.png)

  * dans "Mon compte", bouton "déconnecion
![image](https://user-images.githubusercontent.com/5269556/29918673-8a6e9356-8e46-11e7-9b91-4d1b5a7be274.png)

Cela ne suffit pas pour toi ?

**Comment by c-geek** [comment]
Autant pour moi, je confonds 2 personnes. Le cas qui m'intéresse est celui avec un PC.

On a une icône de verrou rouge en haut à droite : 

![image](https://user-images.githubusercontent.com/969136/29913197-bff7fb96-8e34-11e7-8240-a1da82ff387a.png)

Or pour la retirer, il faut s'authentifier. Mais il n'y a pas de bouton spécifique pour cette action, il faut absolument soit :

* se déconnecter pour avoir le bouton « se connecter »
* faire une action qui requiert l'authentification

L'utilisateur en question (FanchDZ je crois) voulait me montrer qu'il connaissait bien ses identifiants secrets en se connectant, puis s'est surpris à chercher le bouton « se connecter » qu'il n'a trouvé nulle part, puisque déjà identifié comme FanchDZ mais pas authentifié car il s'agissait d'une nouvelle session de navigation.

**Comment by blavenie** [comment]
ok, c'est donc plutôt un bouton "s'authentifier" qu'il faut ajouter.

Notons que : 
 - un clic sur "Editer mon profil"
 - un clic sur les messages ou les invitations 
force l'authentification ;)

**Comment by c-geek** [comment]
Oui c'est comme ça qu'il a contourné. Mais bon .. c'est quand même bizarre.

Après tu fais comme tu veux, je te faisais le retour d'un utilisateur.

**Comment by blavenie** [comment]
done : 
![image](https://user-images.githubusercontent.com/5269556/30648601-b71d45e0-9e1e-11e7-95f4-d7bc05d4bc44.png)
