### ISSUE TITLE
Sémantique : "monnaie libre duniter"

### ISSUE THREAD

**Issue by yann1108** [duniter/cesium#553]
![screenshot-cesium monnaielibreoccitanie org-2017-09-03-06-16-52](https://user-images.githubusercontent.com/272091/30000960-bfa466ce-907e-11e7-81e4-1cb3715f1169.png)
Juste un truc que je remarque à chaque fois que je lance Césium.
La page de garde de Cesium mentionne ::
>  "Bienvenue dans l'application Cesium ! Suivez  vos comptes en monnaie libre Duniter
c'est quoi la monnaie libre Duniter ? :-)

**Comment by blavenie** [comment]
@yann1108 la question est plutôt : que verrais tu sur cette 1ere page ? (sachant que le texte doit etre statique, indépendant de la dite monnaie G1, GT, etc.)

**Comment by yann1108** [comment]
à 1ère vue, la phrase peut simplement dire : 
"Bienvenue dans l'application Cesium ! Suivez vos comptes en monnaie libre"
si l'ajout de "Duniter" est pour préciser qu'il en est le centre, que c'est son écosystème.
On peut le dire ailleurs...

**Comment by blavenie** [comment]
Pourquoi pas "Suivez vos comptes Duniter" ?
@Insoleet @c-geek un avis ?

**Comment by c-geek** [comment]
Il y a cette personne qui a fait la confusion récemment : https://twitter.com/grebert/status/903576425139195904

L'idéal serait quand même « Suivez vos comptes en Ğ1 ». Pourquoi pas utiliser le fichier de conf pour ça ?

**Comment by yann1108** [comment]
Pour l'instant, effectivement, le nom approprié est "Ḡ1"
Mais nos logiciels ne sont pas supposés être capable de suivre, n'importe quelle monnaie libre et au moins 2 alternativement, dans le futur ?
donc soit on reste générique par simplification, soit on met une donnée relative basée sur le fichier de conf.
