### ISSUE TITLE
Scrollbar on the main container not working on Firefox / Desktop

### ISSUE THREAD

**Issue by G4dter** [duniter/cesium#56]

**Comment by G4dter** [comment]
Le problème vient à priori du fait qu'on ait pas cette ligne de code (ligne 143 du fichier app.js)

`$ionicConfigProvider.scrolling.jsScrolling(false);`

Si on commente le test sur le fait qu'on soit sur Android, ca fonctionne.

Par contre, on se retrouve à avoir un gros blanc quand on va dans "Monnaie". Il faut scroller pour avoir les infos (constaté sur Firefox et Chrome)

**Comment by blavenie** [comment]
See also : #41
