### ISSUE TITLE
Fichier exécutable pour le client Césium sur windows

### ISSUE THREAD

**Issue by MickaelLarose** [duniter/cesium#560]
Bonjour, 
je voulais simplement faire part de mon envie de pouvoir installer le client Césium sur mon ordinateur qui fonctionne sous windows.

**Comment by blavenie** [comment]
bonjour,

il y a bien des versions Windows : [ici](https://github.com/duniter/cesium/releases/tag/v0.15.5).

Pour la v0.17.2, @c-geek as tu un moment pour la générer ? ;)

**Comment by c-geek** [comment]
Je veux bien, mais désormais c'est 15 Ğ1 le déploiement :-)

**Comment by blavenie** [comment]
tu as bien raison. Depuis le temps j'aurais pu me débrouillé pour m'en sortir... et puis tu as bien assez de choses à faire sur Duniter.
Mieux vaut que je trouve une solution pérenne à mon soucis. Genre acheter un disque ;)

**Comment by blavenie** [comment]
une release est en cours... sur une autre machine du coup
