### ISSUE TITLE
DU absent

### ISSUE THREAD

**Issue by galuel** [duniter/cesium#576]
Quand on consulte un compte membre, par exemple via annuaire -> recherche -> opérations sur le compte, le DU n'apparaît pas, ce qui fait que le solde est faux, il ne représente pas la somme des opérations sur le compte.

C'est un bug d'affichage, il est impossible que le solde d'un compte ne puisse pas être retrouvé à l'aide de la somme des opérations sur celui-ci.

**Comment by librelois** [comment]
Pour voir les DU sur ton cesium il te suffit de modifier le paramètre `showUDHistory` dans ton fichier de conf, c'est `config.js` a la racine du dossier césium ;)
  @blavenie il serait souhaitable que ça devienne une option de la page des paramètres,  parce que tout le monde ne sais pas aller modifier manuellement un fichier de conf !

**Comment by galuel** [comment]
C'est un bug, on ne peut pas demander à un utilisateur d'aller corriger dans un fichier ce qui doit absolument être visible.

**Comment by blavenie** [comment]
Non @librelois le changement de paramètres ne suffit pas, car les noeud Duniter ne retourne plus l'historique des DU. Il faut le reconstitué à partir de plus sieurs appels à BMA.
C'est pour cela que j'avais désactiver l'option (qui ne sert plus à rien).

Il faut recoder une récupération de l'historique, en tenant compte des période d'entrée/sortie dans la WOT.
voir #232
