### ISSUE TITLE
Fenêtres en double incohérentes

### ISSUE THREAD

**Issue by galuel** [duniter/cesium#578]
Lorsqu'on se connecte à un compte pour le consulter, on peut passer par l'annuaire, et alors on rejoint une fenêtre comme celle ci : https://g1.duniter.fr/#/app/wot/AdZen5c2mi2tNUMqVwxgU7wJwyRVHb6rZcAMCPqomw1b/LaurentGilet

Où l'on voit assez clairement un sous-menu "certifications - opérations sur le compte - clé publique", qui sont des données Ğ1 polluées par des informations Cesium+ intercalées par défaut, alors qu'elles devraient être placées sans doute "en +" à la fin des informations purement Ğ1, et bien indiquées comme n'étant pas des données Ğ1, sinon la source de confusion est grande.

Mais quand on clique sur le menu général à gauche sur "mon compte" ("compte" suffirait, puisqu'on peut consulter tout compte), on voit bien le menu dans l'ordre différent du premier cas : "clé publique - certifications" mais il manque "opérations sur le compte".

Ces deux fenêtres ne devraient en faire qu'une puisqu'elles ont absolument les mêmes fonctionnalités. Elles devraient dans l'ordre respecter en menu : 

- Clé publique
- Certifications
- Opérations sur le compte
- Données centralisées non-Ğ1 Cesium+ (ou titre équivalent) : ... pour ceux qui voudraient activer Cesium+

**Comment by blavenie** [comment]
Pour les données cesium+, j'ai ajouté un texte explicatif : 
![image](https://user-images.githubusercontent.com/5269556/31500400-99b730c4-af67-11e7-9624-aae3a6246748.png)

**Comment by galuel** [comment]
Voilà, ce serait une bien meilleure approche, lister 1°) les données purement Ğ1 et 2°) annoncer les données Cesium+

Conseil à mon avis : mettre un "?" après "profil cesium+ (?)" clickable qui renvoie vers un help simple qui rappelle que Cesium+ est un enrichissement de données centralisé (non-P2P), qui n'est pas stocké en blockchain et est indépendant de la monnaie Ğ1, et qui ne devrait donc être utilisé qu'en connaissance de cause. (ou truc similaire)

**Comment by blavenie** [comment]
> un enrichissement de données centralisé (non-P2P)

non, Cesium+ (noeud ES) est en bonne voie pour etre du P2P.
cf ce post : https://forum.duniter.org/t/beta-test-duniter4j-elasticsearch-api-0-16-1-avec-synchronization-p2p/3265

**Comment by blavenie** [comment]
Je mettrais un helptip cliquable plus tard
