### ISSUE TITLE
Publicité pour un service privateur

### ISSUE THREAD

**Issue by galuel** [duniter/cesium#580]
Dans l'activation  paramètres Cesium+, on trouve une publicité pour un service privateur centralisé "Activer les services XXX" et "API XXX"

Pour un projet de logiciel libre concernant une monnaie libre c'est très douteux. Ca ne donne pas confiance dans le projet Cesium.

Je vais enlever Cesium des clients recommandables pour le moment.

**Comment by blavenie** [comment]
Attention à ne pas confondre "accès à des services privateur" avec "intégration de code privateur".
Il n'y a en effet aucune librairie non libre dans Cesium.

Dans la prochaine version, ces options seront néanmoins retiré. Comme indiqué dans les post du forum, c'était expérimental, juste pour voir ce que donne une carte plus complète.
