### ISSUE TITLE
Personnes qui perdent leur mot de passe

### ISSUE THREAD

**Issue by petiteberger** [duniter/cesium#581]
Bonjour,
Deux membres de la toile de confiance ont perdu leur mot de passe et ne sont plus en mesure d'accéder à leur compte. Il s'agit d'Alexis Lecointe et de Raphaël Modiano.
Quelle est la procédure conseillée dans ce cas là?
A ma connaissance, ils n'avaient pas sauvegardé leur document de révocation.

**Comment by librelois** [comment]
> Quelle est la procédure conseillée dans ce cas là?

Le membre en question doit révoquer son compte avec son document de révocation qu'il est censé avoir créé et téléchargé lors de son inscription conformément aux **[recommandations de sécurité](https://forum.duniter.org/t/recommandations-de-securite-v3-a-lire-avant-de-creer-votre-compte-g1/1829)**.

il devra ensuite recréer un compte membre puis redemander ses certifications auprès de tes anciens certificateurs :)

Si l'utilisateur n’a pas son document de révocation alors il doit attendre l’expiration de son compte membre (1nas après l'obtention du statut de membre), car tant que son ancien compte existe personne ne peut te certifier sur un nouveau compte cela serait contraire a la **[licence Ğ1](https://duniter.org/fr/wiki/devenir-membre)**.

Cette procédure ne dépend pas de Cesium ni d'aucun client en particulier, elle ne dépend que du protocole Duniter et de la licence Ğ1, je ferme donc ce ticket.
