### ISSUE TITLE
Intégration d'un système façon Tipee dans le virement permanent

### ISSUE THREAD

**Issue by Spirita** [duniter/cesium#582]
Bonjour,
Pour ceux qui connaissent pas, Tipee est un site qui permet de soutenir des artistes, asso, ... via des micro-virement (1-2 euros) tout les mois, dans le style du crowfunding.
Ce système de rémunération se développe de plus en plus (certains en vivent) et il pourrait être intéressant de l'intégrer de base dans Césium (dans le virement permanent ou dans un service distinct).

Quelques remarques :
* Tipee étant une entreprise existante il vaut mieux trouver d'autres termes (ma proposition : "Tipser", facile à conjuguer et décliner).
* Il peut être appréciable de pouvoir choisir entre verser un montant défini pour chaque tipsé, ou un montant maximum à répartir entre tout les tipsés (avec éventuellement une forme de pondération permettant "2 fois plus pour lui")
* Pour limiter le nombre d'opérations, il est préférable qu'il y ait un virement par tipseur (du montant total de tout ses tips qu'il émet) vers un seul compte qui fait un seul virement par tipsé (du montant total de tout les tips qu'il reçoit)

**Comment by librelois** [comment]
Tout ceci est très intéressant mais ça n'a rien a voir avec la monnaie et ses clients. Merci de poster votre idée sur le forum en .fr : https///forum.duniter.fr

Les tickets github d'un dépôt sont réservés à ce qui touche au logiciel de ce dépôt. Ce n'est pas le lieu pour proposer la création d'un nouveau programme.

**Comment by Spirita** [comment]
Ce n'est pas un nouveau programme, je parle de prévoir un cas d'utilisation pour "Mon compte" -> "Service en lignes" -> "Ajouter un service" -> "+ Ajouter un service" ->  "Virement automatique" dont l'infobulle dit "Cette fonctionnalité est encore en cours de développement. Pourquoi ne pas contribuer à Cesium, pour l'obtenir plus rapidement ? ;)"

**Comment by librelois** [comment]
@Spirita svp cessez de parler de votre idée ici.
Cesium est un client, un gestionnaire de compte, point. Il n'est techniquement pas possible de concevoir un service de virements automatiques au niveau de cesium car cela nécessite la possession permanente de votre clé privée, ce qui est évidemment impossible pour des raisons de sécurité.
Si vous souhaitez effectuer des virements automatique vous devez soit avoir votre propre serveur chez vous qui le fait (faisable que par des geek) soit faire gérer une part de votre monnaie par un gestionnaire extérieur que vous payerez pour cela, une sort"e de banque Ğ1 si vous voulez.

Merci de ne plus poster ici et de poursuivre cet échange sur le forum .fr : https://forum.duniter.fr

**Comment by blavenie** [comment]
@librelois si les virements automatiques sont possibles, mais via un tiers de confiance comme dans les "services en ligne" dont parle @Spirita.

@Spirita j'avais mise ce libellé possible dans les catégories de services en ligne, mais c'est vrai que je devrais le retirer pour le pas engendrer de confusion.

**Comment by blavenie** [comment]
On pourrait aussi simplement avoir une "rappel de virement". Ainsi les ordre de virements serait plus rapide à lancer, sans que la sécurité du compte soit mise en péril
