### ISSUE TITLE
Inconsistent displayed certifications numbers when membership expired

### ISSUE THREAD

**Issue by jellium** [duniter/cesium#583]
Seen on Cesium v0.12.9.

The certifications number [displayed on the account page](https://forum.duniter.org/uploads/default/optimized/2X/a/a8bccc2c4ab5a28995336b416be3b765f0657cb1_1_690x78.png) differs from that [displayed on the certifications page](https://forum.duniter.org/uploads/default/original/2X/d/d909c040c6a0cf0036836dcb3ec0bf2c2834a5df.png) when membership has expired, even though there are still some valid certifications.

See [this post](https://forum.duniter.org/t/demande-de-certifications-g1-test-jellium/2892/16?u=jellium) (fr) on the Duniter dev forum.

**Comment by blavenie** [comment]
Hello !
version 0.12.9 is pretty old ! ;)

I could not reproduce in Cesium v0.18.2
![image](https://user-images.githubusercontent.com/5269556/31831774-e9abcee2-b5c4-11e7-8bb3-32b4964b1e1b.png)
