### ISSUE TITLE
Certaines nœuds visibles en WS2P ne sont pas affichés par Cesium

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#584]
On a typiquement un cas reproductible avec le membre SimonLefort (Hb2TLnB6d3dKiC1VibaUJbZtLhyuHYaDxXNvVd7NqXJe).

Son nœud transmet bien ses trames HEAD au nœud https://g1.duniter.fr/network/ws2p/heads, pourtant Cesium 0.18.2 ne l'affiche pas dans la vue réseau.

**Comment by blavenie** [comment]
Oui a priori c'est un noeud WS2P privé, non ?
Car il n'est pas dans ta liste de peer ici : https://g1.duniter.fr/network/peers

Il y a déjà un ticket pour l'affichage des noeuds privés : #571

**Comment by c-geek** [comment]
Autant pour moi, je pensais que Cesium 0.17.4 affichait aussi les nœuds en WS2P Privé.
