### ISSUE TITLE
Impossible de créer un nouveau compte membre

### ISSUE THREAD

**Issue by Akasashasha** [duniter/cesium#592]
Bonjour

le bouton "J'accepte la licence" reste grisé et n'est donc pas cliquable ... impossible de créer un nouveau compte membre.

https://g1.duniter.fr/#/app/settings

merci

**Comment by blavenie** [comment]
Bonjour @Akasashasha, et merci pour votre remontée d'anomalie.
Pouvez vous me dire quel navigateur vous utilisez ? (Chrome, Safari, Firefox...)
Est-ce sous Mac ? quelle modèle de machine ? (iPad, etc.)
Merci de votre aide

**Comment by Akasashasha** [comment]
Bonjour

lors de cet essai ma config était:
- Ordinateur portable Acer Aspire V15
- Windows 10 Famille version 1703
- Google Chrome  Version 61.0.3163.100 (64 bit)

merci

2017-11-01 14:48 GMT+01:00 Benoit Lavenier <notifications@github.com>:

**Comment by Akasashasha** [comment]
Bonjour

je vois que cette conversation est marquée comme fermée, mais le problème n'est pas résolu, j'ai refait un essai aujourd'hui et le problème persiste (bouton grisé, impossible de passer l'étape)

**Comment by blavenie** [comment]
résolu en v0.19.2
