### ISSUE TITLE
Impossible d’accepter la license (installation locale / win8)

### ISSUE THREAD

**Issue by nanocryk** [duniter/cesium#595]
Comme dit dans le titre, je ne peux pas accepter la license alors que j’ai installer Cesium en local.
J’ai téléchargé cette version : https://github.com/duniter/cesium/releases/download/v0.17.5/cesium-v0.17.5-web.zip
Screenshot : https://i.imgur.com/LLNe8gQ.png2

Mon navigateur est Vivaldi qui utilise le moteur de rendu de Chrome.

**Comment by blavenie** [comment]
@nanocryk peux tu essayer avec une version plus récente de Cesium ?

Bon, de toute façon j'ai corrigé un truc pour la prochaine version : je fais en sorte de toujours activer le bouton, au bout de 5 secondes...

**Comment by blavenie** [comment]
resolved in Cesium v0.19.2
