### ISSUE TITLE
creation d'un nouveau compte membre, sur mac

### ISSUE THREAD

**Issue by PierreYvesC** [duniter/cesium#61]
Salut Benoit!
J'essaie de faire comme tu me l'a demandé. Si je m'exprime pas au bon endroit fait le moi savoir. merci.
donc:
à la création d'un compte membre, le compte qui s'ouvre ressemble à un compte simple portefeuille. Pas de speudo, pas de clef, une certification à été reçue mais elle n'apparait pas. Un paiement à été reçu est apparait, mais le solde est quand même nul.
ça donne ça:

![capture1](https://cloud.githubusercontent.com/assets/19892806/15993424/477e6a4e-30e6-11e6-9f83-0de63687c60c.jpg)

pourtant si je regarde le même compte via un mon compte PierreYves et l'annuaire je le vois comme ça:

![capture2](https://cloud.githubusercontent.com/assets/19892806/15993435/7b284612-30e6-11e6-8961-6c59b0cca679.jpg)

Le cas s'est présenté plusieurs fois.
Le compte à été certifié (par moi) mais n'est pas devenu membre actif.

**Comment by blavenie** [comment]
Merci @PierreYvesC je regarde ca !

**Comment by c-geek** [comment]
@blavenie Comme dit sur le salon XMPP : le UserID est à null, voilà pourquoi l'adhésion ne passe pas sauf à faire la procédure manuellement, qui redemande l'UserID http://paste.twiced.fr/azayijolar.tex
