### ISSUE TITLE
Césium 0.19.6 corrompu 

### ISSUE THREAD

**Issue by vincentux** [duniter/cesium#611]
Installation impossible de Césium 0.19.6 sous Android :/

![screenshot_20171111-213339](https://user-images.githubusercontent.com/11737560/32693294-f3863310-c728-11e7-9eb5-b39898f2b3f7.png)

**Comment by blavenie** [comment]
aie ;/

**Comment by blavenie** [comment]
je penses avoir trouvé, il y avait un soucis dans le numéro de code de version (1960 au lieu de 19600) du coup ton android penses que tu veux rétrograder l'application et te jette.

J'ai fait la même erreur avec la v1.0.0, donc je vais la regénérer

**Comment by blavenie** [comment]
> vincentux : version1.0.0 installé avec succès sur android \o/
