### ISSUE TITLE
Suppression : bouton demande de certification

### ISSUE THREAD

**Issue by yann1108** [duniter/cesium#614]
Cette fonctionnalité est une source de problème, et contredit la licence Ǧ1.
Je ne compte plus les instances et le temps passé à corriger les implications de ce petit bouton diabolique...
Merci de prendre en considération l'expérience terrain.

**Comment by blavenie** [comment]
en fait il y a plusieurs boutons. J'avais supprimé l'accès à l'un, mais oublié l'autre (celui de la page certification).
