### ISSUE TITLE
Problème de recherche ID bloc

### ISSUE THREAD

**Issue by galuel** [duniter/cesium#619]
![capture du 2017-11-24 18-12-54](https://user-images.githubusercontent.com/5245398/33219615-97f34234-d143-11e7-8c71-b4a2d662bcc0.png)

Quand on cherche des blocs par pseudo on ne trouve pas le bon résultat.

**Comment by blavenie** [comment]
il s'agit d'une recherche "textuelle" dans le contenu du bloc.

la fonction de recherche de bloc par pseudo n'existe pas.

Comme indiqué dans le champ, il est possible de chercher par `numéro de bloc, hash, clé publique`.
![image](https://user-images.githubusercontent.com/5269556/33229188-fdff7c2e-d1c9-11e7-838a-6c94c7095439.png)
