### ISSUE TITLE
visualisation de la toile de confiance sur Cesium.

### ISSUE THREAD

**Issue by PierreYvesC** [duniter/cesium#67]
je n'arrive pas à savoir quoi faire pour pouvoir certifier des nouveaux membres;
...les règles elles même de la toile me sont un peu obscures;
...en participant à test-net je prends conscience de combien la toile de confiance est au cœur du système monétaire...
Un moyen de visualiser la toile de confiance et ces mécanismes serait super aidant!

**Comment by blavenie** [comment]
Remarque pour les techniciens : j'ai commencé à intégrer la librairie d3 pour faire des graphs, etc...
Mais j'ai peur que ca plombe les perfs. Je cherche un moyens sous Ionic/Angular de ne charger un librairie Javascript qu'au dernier moment. Une idée ?

**Comment by mcl1234** [comment]
Des libraries WebSockets ( https://github.com/socketio/socket.io ), ou WebRTC ( https://github.com/KodeKraftwerk/reepio )?

**Comment by mcl1234** [comment]
https://github.com/carlipa/aurora-graphql ?

**Comment by mcl1234** [comment]
Avec les évènements je pense
http://ionicframework.com/docs/api/directive/onHold/

**Comment by blavenie** [comment]
Je ferme cette issue. La visualisation des certifications donénes/recues est maintenant possible ([exemple](http://cesium.duniter.fr/#/app/wot/cert/lg/EcDqqxvJAHSTEP16Y1AseAG9AmebedgBiME1iEr2Eaoy/PierreYves)).
Par ailleurs, les règles de la toile de confiance sont maintenant affichées [ici](http://cesium.duniter.fr/#/app/currency/view/lg/).
