### ISSUE TITLE
certifier les membres connus

### ISSUE THREAD

**Issue by PierreYvesC** [duniter/cesium#68]
Je voudrais certifier les membres que je connais.
(Je crois comprendre que plus les membres se certifient mutuellement, plus la distances entre deux membres qui ne se connaissent pas se raccourcie, et donc plus la communauté peux grandir.)
J'ai plusieurs difficulté sur Cesium: quand je crois connaitre un membre en fait je n'ai pas les moyens de vérifier que le compte est bien celui de la personne connue, et aussi que ce compte est unique.
idéalement j'imagine des moyens de faciliter l'inter-certifications (et le contrôle) des membres. voici quelque idées:
- j'aimerai pouvoir en cliquant sur l'icone "membres" voir la liste complète des membres. (l'annuaire affiche les comptes en vrac avec tous les essais, erreur, doublons...etc...)
- j'aimerai en cliquant sur la fiche d'un membre avoir une idée de son identité réelle. pourquoi pas la possibilité de se présenter: un vrai nom, une photo, des liens, enfin le moyen de reconnaitre qui "se cache" derrière un speudo.
- j'aimerai pouvoir consulter les "fiches" des membres qui ont fait une demande d'adhésion et qui sont "en attente". icône "demandes d'adhésions"
- il serait commode également que l'annuaire range dans une espèce de "corbeille" les comptes inactifs, morts, vieux comptes jamais certifiés ...(les essais et les erreurs: les blabla, les ssss et autres azerty)
- et aussi avoir une vue de l'état de la toile de confiance dans l'instant. ex: qui est en mesure de certifier des nouveau membres? (si c'est moi, il est important que je le sache pour faire mon travail d'inclusion)

Très humblement...(je n'ai aucune idée de ce qu'implique en pratique de ces suggestions)...
et par ailleurs très reconnaissant pour le travail accompli, dans l'intention, toujours, de faire fructifier le test.

**Comment by blavenie** [comment]
Toutes ces idées sont excellentes ! 
Rassures toi, j'ai encore plein de trucs en cours sur Cesium, mais tes remarques me conforte dans ma démarche ;)

C'est une bonne synthèse !
Merci l'ami !
