### ISSUE TITLE
DU = 1%/jour...

### ISSUE THREAD

**Issue by PierreYvesC** [duniter/cesium#73]
le DU s'affiche à 1%/jour :
![du 1](https://cloud.githubusercontent.com/assets/19892806/16268952/b6b5b37a-3890-11e6-974c-464c83aabc00.jpg)

**Comment by M5oul** [comment]
Oui, la monnaie de test a une croissance de 1 % / jour.
Il ne s’agit pas d’une monnaie libre :smiling_imp:

**Comment by PierreYvesC** [comment]
salut Moul!
...mais non, le DU de la monnaie test est de 10%/jour ! :

![capt3](https://cloud.githubusercontent.com/assets/19892806/16269909/9bbde192-3894-11e6-80b9-66a388666f79.jpg)
 C'est le "DU actuel" qui est planté.

**Comment by M5oul** [comment]
Ok, je pense que c’est lié au changement de `Base`.

**Comment by c-geek** [comment]
A l'affût le @PierreYvesC, on lui fait pas à l'envers ! :smile:

**Comment by blavenie** [comment]
Bravo @PierreYvesC !

**Comment by M5oul** [comment]
Corrigé dans la 0.1.20.
