### ISSUE TITLE
Nouveaux membres !??

### ISSUE THREAD

**Issue by galuel** [duniter/cesium#81]
Dans Cesium on peut lire : 

Membres : 82
Nouveaux membres : +1

Pourquoi +1 ? Pourquoi pas +10, +50 ou +82 ? Ca n'a aucun sens !

**Comment by M5oul** [comment]
Il me semble que ça signifie le nombre de membre qui sont dans la piscine à devenir membres.

**Comment by galuel** [comment]
Peu importe ce que ça signifie ou pas. Ca n'a aucun sens tel qu'écrit.

**Comment by M5oul** [comment]
En effet, ça manque de précision.

**Comment by blavenie** [comment]
@c-geek : tu as dans l'idée d'y afficher le nombre de membre depuis le dernier DU, non ?

**Comment by blavenie** [comment]
De mon côté je trouve ca pas mal, comme indicateur (si on trouve un moyen de le préciser). Je pensais aussi le rendre cliquable, pour voir la liste des nouveaux membres concernés

**Comment by c-geek** [comment]
Le "+X" ou "-X" signifie le nombre de membres arrivés/partis depuis le dernier DU. J'avais mis ce champ dans le prototype, pour se rendre compte du flux de membres.

Depuis c'est resté.

**Comment by mcl1234** [comment]
Je propose plutôt un graphique en JavaScript pour illustrer l'arrivée de nouveaux membres dans la communauté

**Comment by blavenie** [comment]
Je propose de renommer en "Nouveaux membre depuis 1 mois" (en remontant sur un mois et non plus depuis le dernier DU)

Dans la version que j'ai déployé aujourd'hui, si on clic sur le "nouveaux membres" on arrive sur la liste des derniers arrivants.
