### ISSUE TITLE
Wallet : tx.comment truncated, if too long

### ISSUE THREAD

**Issue by JeanFe** [duniter/cesium#84]
J'ai publié un texte trop long avec ma transaction. Maintenant les montants sont hors écran. Il faut allonger la fenètre vers la droite hors écran pour les consulter. C'est bête car je viens ainsi de polluer l'arrivé d'un nouveau utilisateur de duniter…
![cesium texte trop long](https://cloud.githubusercontent.com/assets/19825127/16466788/c60e148e-3e44-11e6-9ec6-8e4bfbe3cb80.png)

**Comment by blavenie** [comment]
@JeanFe merci pour cette remontée d'anomalie.
Peux tu me faire un paiement avec un texte aussi long pour que je corrige à l'aide d'une cas concret ? ;)

**Comment by JeanFe** [comment]
send 3 min ago

**Comment by blavenie** [comment]
Résolu dans la prochaine version (0.1.24)

**Comment by vincentux** [comment]
Effectivement y a du mieux, mais c'est encore un peut juste pour afficher la bulle verte, non ?


![30-06-2016-38-55](https://cloud.githubusercontent.com/assets/11737560/16482171/e6065dea-3eae-11e6-8f4e-072a3a47491f.png)
