### ISSUE TITLE
Tutoriel « Contribuer au code de Cesium »

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#88]
Ce serait bien que le tutoriel soit ajouté au code source.

Autre chose : j'ai fait le test avec Node.js 4 (c'est la [version stable officielle](https://nodejs.org/en/) actuellement) et ça fonctionne. Tu peux donc proposer son utilisation.

Par contre, il faut juste faire précéder la commande `npm install` de`npm install chalk event-stream`, car il n'arrive pas à résoudre ces  2 dépendances.

A part ça, tout baigne !

**Comment by blavenie** [comment]
Le tuto a été ajouté au code source : dans doc/fr
