### ISSUE TITLE
Wallet: Add link "share" with URL for web site integration

### ISSUE THREAD

**Issue by blavenie** [duniter/cesium#9]
Penser à ajouter un lien "share" dans l'écran wallet
qui donne le lien HTML <a href="..."  ou un truc du genre

cf ce qui se fait FaceBook

**Comment by blavenie** [comment]
Ajouter un générateur QR code qui porte l'URL de paiement

**Comment by M5oul** [comment]
Ou comme [Liberapay](https://liberapay.com/Moul/widgets).

**Comment by blavenie** [comment]
A yes : donc avoir un JS accessible (sur un site Cesium par exemple) avec un interface minimaliste

**Comment by blavenie** [comment]
Exemple de lien de partage: 
`

    <a class="twitter" href="https://twitter.com/share?text=New%20Elasticsearch%20Site%20Plugins%20at%20Compose&amp;url=https://www.compose.com/articles/new-elasticsearch-site-plugins-at-compose/&amp;via=composeio" onclick="window.open(this.href, 'twitter-share', 'width=550,height=235');return false;">
      <span class="hidden">Share on Twitter</span>
      <svg><use xlink:href="#twitter"></use></svg>
    </a>

    <a href="https://www.facebook.com/sharer/sharer.php?u=https://www.compose.com/articles/new-elasticsearch-site-plugins-at-compose/" onclick="window.open(this.href, 'facebook-share','width=580,height=296');return false;">
      <span class="hidden">Share on Facebook</span>
      <svg><use xlink:href="#facebook"></use></svg>
    </a>

    <a href="https://plus.google.com/share?url=https://www.compose.com/articles/new-elasticsearch-site-plugins-at-compose/" onclick="window.open(this.href, 'google-plus-share', 'width=490,height=530');return false;">
      <span class="hidden">Share on Google+</span>
      <svg><use xlink:href="#google-plus"></use></svg>
    </a>

    <a href="http://news.ycombinator.com/submitlink?u=https://www.compose.com/articles/new-elasticsearch-site-plugins-at-compose/&amp;t=New Elasticsearch Site Plugins at Compose" onclick="window.open(this.href, 'hacker-news-share','width=580,height=296');return false;">
      <span class="hidden">Vote on Hacker News</span>
      <svg><use xlink:href="#y-combinator"></use></svg>
    </a>

    <a class="subscribe-btn" href="https://www.compose.com/articles/rss/">
      <svg><use xlink:href="#subscribe"></use></svg> Subscribe
    </a>
  `

**Comment by blavenie** [comment]
Fixed in v0.3.3
