### ISSUE TITLE
Transaction list alignment broken after a transaction

### ISSUE THREAD

**Issue by M5oul** [duniter/cesium#90]
![capture d ecran 2016-07-04 a 17 12 22](https://cloud.githubusercontent.com/assets/4758871/16564978/9d8c47f0-420a-11e6-9eb0-cfef067dde03.png)

If I reload the page, the alignment return well :smile:

**Comment by blavenie** [comment]
@M5oul Do you still have the problem ?
If yes, could you tell me your browser version ?

**Comment by M5oul** [comment]
I can't reproduce it.
