### ISSUE TITLE
Changing node leads to an error

### ISSUE THREAD

**Issue by M5oul** [duniter/cesium#91]
I tried from http://cesium.duniter.fr and https://moul.re/cesium
![capture du 2016-07-04 22-33-18](https://cloud.githubusercontent.com/assets/4758871/16569495/761cedb4-4237-11e6-9a35-0c9533544668.png)
(erreur sur la capture d’écran, ça ne fonctionne pas avec `duniter.org:8999`.)
I have also tried with my node.
![capture du 2016-07-04 22-33-29](https://cloud.githubusercontent.com/assets/4758871/16569494/76147170-4237-11e6-8f18-cffd19222d4a.png)

**Comment by blavenie** [comment]
@M5oul tu es sur que ton noeud est bon ? 
Moi je n'ai rien sur : http://duniter.org:9330/node/summary

**Comment by M5oul** [comment]
Oui, la capture n’est pas bonne :sweat_smile: 
Je viens de réessayer sur `duniter.org:8999`.

**Comment by blavenie** [comment]
@M5oul et ca amrche du coup ou pas ? On peut fermer le bug ?

**Comment by M5oul** [comment]
Non, ça ne fonctionne pas.

**Comment by M5oul** [comment]
Oui, ma machine a bien accès à `duniter.org:8999` via curl. Avec Firefox, ça passe en https, et j’y aie pas accès.
C’est dû au fait que j’accède à duniter.org via https.
Ça fonctionne avec `test-net.duniter.fr:9201` étant donné que je n’accède pas à ce nom de domaine en https.
Il n’y a rien dans la cosole de Firefox.
![capture du 2016-07-05 12-04-01](https://cloud.githubusercontent.com/assets/4758871/16582166/7ada8778-42ad-11e6-94f7-43ad9aafe46b.png)

J’ai tenté avec un nouveau profil Firefox n’ayant pas visité `duniter.org` avant. Le changement de nom de domaine fonctionne.

Pour résumer, le problème vient du fait que Firefox ayant visité le nom de domaine en HTTPS au préalable, ne laisse pas accès au nœud.

---
J’ai tenté en désactivant toutes les extensions de mon navigateur Firefox, ça n’est pas la source du problème.
J’ai également tenté avec GNOME Web 3.20 et GNU IceCat 38.8, sur lequels Césium ne fonctionne pas pour des raisons que j’ignore. J’ai pas fouillé plus :smile:
J’ai aussi tenté avec le Tor Browser.
Il n’y a pas Chromium sous Fedora.

**Comment by blavenie** [comment]
> J’ai tenté avec un nouveau profil Firefox n’ayant pas visité duniter.org avant. Le changement de nom de domaine fonctionne.
Donc je peux fermer le bug ?

**Comment by M5oul** [comment]
Je comprends que tu veuilles fermer ce bug qui t’embête.
Le problème c’est que je le reproduis toujours.
On peut le décaler dans la millestone. On est pas obligé de s’en occuper.
Personnellement, il ne me dérange pas.
Je pense qu’il faut au moins garder une trace dans le bugtracker.

**Comment by blavenie** [comment]
@M5oul en v0.2.6, j'ai introduit une détection du protocole dans les requetes REST (http ou http**s**) en fonction du port (443 -> https).
Mais pour ton cas, pas sur que cela t'aide. Peux tu tester ?

Si le problème persiste, as-tu une idée d'une solution à mettre en oeuvre ?
Au final, c'est un problème firefox, c'est ca ? (en fait j'ai pas bien pigé le truc qui cloche)

**Comment by M5oul** [comment]
Je reproduis toujours le bug.
Je n’ai pas d’idée.
Je ne sais pas très bien d’où vient le bug. Ça semble être firefox/extension.
Je laisse tombé pour ce bug, il est chiant…

**Comment by c-geek** [comment]
Non moi j'ai bien reproduis un truc : je commence par vouloir changer de noeud, par exemple de `cgeek:9330` vers `duniter.org:8999`, et je reçois la même erreur que dans l'impression écran de Moul initialement (sauf qu'il a vraiment tapé une mauvaise adresse de noeud ce bougre !). Mais pourtant dans mon cas, l'adresse est correcte et je reçois l'erreur.

**Sauf que si l'on insiste un 2ème coup, alors ça passe.**

**Comment by M5oul** [comment]
En effet, j’ai réussit avec `duniter.org:8999` en insistant une seconde fois.
Objectif, que ça fonctionne dès le premier clic ?

**Comment by blavenie** [comment]
ca devrait etre bon en v0.2.7

**Comment by M5oul** [comment]
Thanks, gracie.
