### ISSUE TITLE
TX failed: wrong unit base for outputs

### ISSUE THREAD

**Issue by blavenie** [duniter/cesium#92]
JeanF raised this error :  wrong unit base for outputs

**Comment by JeanFe** [comment]
j'ai tenté un versement qui m'a donné le message du titre, j'ai tenté de changer la somme puis le destinataire et aussi rafrachissement de la page (F5) avec le même résultat. Au final après une déco / reco, la transaction a fini par passer.

**Comment by JeanFe** [comment]
À noter que j'ai effectué une transaction via Sakia qui a fonctionné au premier coups, Je ne sais pas si c'est ce qui a débloqué les Tx juste après sur cesium…

**Comment by JeanFe** [comment]
![capture du 2016-07-09 02-04-35](https://cloud.githubusercontent.com/assets/19825127/16704631/e4006e6a-4579-11e6-8dca-6fd51e88147c.png)
Crédit suffisant pourtant, j'ai à ce moment une tx en attente de paiement de 3DU

**Comment by JeanFe** [comment]
nouvelle tentative d'envoi:
![capture du 2016-07-09 13-10-32](https://cloud.githubusercontent.com/assets/19825127/16707667/f038d2d2-45d6-11e6-8187-a03f5ba09945.png)
Pour info j'avais fait un paiement de 2 DU à filb environ une heure plus tôt sans problème.

**Comment by blavenie** [comment]
see #107
