### ISSUE TITLE
Changer de noeud laisse des requêtes sur le noeud par défaut

### ISSUE THREAD

**Issue by c-geek** [duniter/cesium#94]
J'ai tenté de modifier le noeud interrogé, et dans la majorité des requêtes cela fonctionne : le nouveau noeud est interrogé en lieu et place de l'ancien.

Mais, des requêtes de type `/blockchain/current` continuent de passer sur `cgeek.fr:9330`. Je pense que cela est dû à ce code : 

https://github.com/duniter/cesium/blob/master/www/js/services/bma-services.js#L237

Cela ne presse pas, mais si l'on souhaite intégrer Cesium dans Duniter (bon, en fait je viens juste de terminer cette évolution justement) alors il faudrait que ce point soit corrigé pour avoir Cesium pleinement piloté par Duniter Desktop qui le force à interroger le noeud local.

**Comment by blavenie** [comment]
> bon, en fait je viens juste de terminer cette évolution justement

Extra ca !!

ok je vais regarder le problème assez vite

**Comment by blavenie** [comment]
Should be corrected on cesium v0.2.7
