### ISSUE TITLE
Can't send money to remuniter

### ISSUE THREAD

**Issue by cuckooland** [duniter/cesium#95]
We can send money to remuniter thanks to Sakia, but not with Cesium:
when we enter the key "TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS", the response is "Result not found".

**Comment by blavenie** [comment]
Add a pubkey regex detection inside the "wot lookup view" : if no result found BUT pubkey regex match, then display one result with the given pubkey
