### ISSUE TITLE
ES: Contacts window

### ISSUE THREAD

**Issue by mcl1234** [duniter/cesium#96]
Hi,

Is it possible to add a "window" - "frame" to see the locally added contacts like in Sakia ?

**Comment by blavenie** [comment]
I should be possible : 
 - to store contacts in the local storage : BUT you will lost this list after a logout !
 - to store contacts (as encrypted data) into a ES datastore. I plan to do such a features for settings, to be able to retrieve it on another computer.

**Comment by blavenie** [comment]
duplicate #381
