### ISSUE TITLE
Connected after identity creation fail

### ISSUE THREAD

**Issue by M5oul** [duniter/cesium#98]
When I create a new account which fail.
For instance, with an UID already existing in the blockchain.
I stay connected.
For a newcomer, it has to understand it have to logout to recreate a new identity.

I am using [Cesium on Duniter desktop package](https://github.com/duniter/duniter/issues/487).
That could be the issue. I don't if credentials are automatically added in Cesium from the ones in Duniter node or if there is any conflict.
@c-geek any idea?

**Comment by c-geek** [comment]
Currently only the `host` field is taken from Duniter Desktop to Cesium.

**Comment by M5oul** [comment]
Ok, I could reproduce it on http://cesium.duniter.fr

**Comment by blavenie** [comment]
@M5oul peux tu réessayer ta manip en v0.2.6 ?
Le cas échéant, peux tu me rédire la procédure exacte ?

merci ;)

**Comment by M5oul** [comment]
Il est toujours présent.
Essaye de créer un compte avec une identité existant comme `moul`, la création échoue, et je me retrouve connecté avec ce compte.
